// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package backend

import mock "github.com/stretchr/testify/mock"

// MockReaderMock is an autogenerated mock type for the ReaderMock type
type MockReaderMock struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockReaderMock) Close() error { _ = "STUB: not implemented"; return nil }

// Read provides a mock function with given fields: p
func (_m *MockReaderMock) Read(p []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }
