// Code generated by mockery v2.28.1. DO NOT EDIT.

package github

import mock "github.com/stretchr/testify/mock"

// MockGithubRepository is an autogenerated mock type for the GithubRepository type
type MockGithubRepository struct {
	mock.Mock
}

// ListBranchProtection provides a mock function with given fields:
func (_m *MockGithubRepository) ListBranchProtection() ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMembership provides a mock function with given fields:
func (_m *MockGithubRepository) ListMembership() ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRepositories provides a mock function with given fields:
func (_m *MockGithubRepository) ListRepositories() ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTeamMemberships provides a mock function with given fields:
func (_m *MockGithubRepository) ListTeamMemberships() ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTeams provides a mock function with given fields:
func (_m *MockGithubRepository) ListTeams() ([]Team, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockGithubRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockGithubRepository creates a new instance of MockGithubRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGithubRepository(t mockConstructorTestingTNewMockGithubRepository) *MockGithubRepository {
	_ = "STUB: not implemented"
	return nil
}
