// Code generated by mockery v2.28.1. DO NOT EDIT.

package aws

import (
	context "context"

	cloudfront "github.com/aws/aws-sdk-go/service/cloudfront"

	mock "github.com/stretchr/testify/mock"

	request "github.com/aws/aws-sdk-go/aws/request"
)

// MockFakeCloudFront is an autogenerated mock type for the FakeCloudFront type
type MockFakeCloudFront struct {
	mock.Mock
}

// AssociateAlias provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) AssociateAlias(_a0 *cloudfront.AssociateAliasInput) (*cloudfront.AssociateAliasOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AssociateAliasRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) AssociateAliasRequest(_a0 *cloudfront.AssociateAliasInput) (*request.Request, *cloudfront.AssociateAliasOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AssociateAliasWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) AssociateAliasWithContext(_a0 context.Context, _a1 *cloudfront.AssociateAliasInput, _a2 ...request.Option) (*cloudfront.AssociateAliasOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateCachePolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateCachePolicy(_a0 *cloudfront.CreateCachePolicyInput) (*cloudfront.CreateCachePolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateCachePolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateCachePolicyRequest(_a0 *cloudfront.CreateCachePolicyInput) (*request.Request, *cloudfront.CreateCachePolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateCachePolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateCachePolicyWithContext(_a0 context.Context, _a1 *cloudfront.CreateCachePolicyInput, _a2 ...request.Option) (*cloudfront.CreateCachePolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateCloudFrontOriginAccessIdentity provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateCloudFrontOriginAccessIdentity(_a0 *cloudfront.CreateCloudFrontOriginAccessIdentityInput) (*cloudfront.CreateCloudFrontOriginAccessIdentityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateCloudFrontOriginAccessIdentityRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateCloudFrontOriginAccessIdentityRequest(_a0 *cloudfront.CreateCloudFrontOriginAccessIdentityInput) (*request.Request, *cloudfront.CreateCloudFrontOriginAccessIdentityOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateCloudFrontOriginAccessIdentityWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateCloudFrontOriginAccessIdentityWithContext(_a0 context.Context, _a1 *cloudfront.CreateCloudFrontOriginAccessIdentityInput, _a2 ...request.Option) (*cloudfront.CreateCloudFrontOriginAccessIdentityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDistribution provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateDistribution(_a0 *cloudfront.CreateDistributionInput) (*cloudfront.CreateDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDistributionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateDistributionRequest(_a0 *cloudfront.CreateDistributionInput) (*request.Request, *cloudfront.CreateDistributionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDistributionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateDistributionWithContext(_a0 context.Context, _a1 *cloudfront.CreateDistributionInput, _a2 ...request.Option) (*cloudfront.CreateDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDistributionWithTags provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateDistributionWithTags(_a0 *cloudfront.CreateDistributionWithTagsInput) (*cloudfront.CreateDistributionWithTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDistributionWithTagsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateDistributionWithTagsRequest(_a0 *cloudfront.CreateDistributionWithTagsInput) (*request.Request, *cloudfront.CreateDistributionWithTagsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDistributionWithTagsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateDistributionWithTagsWithContext(_a0 context.Context, _a1 *cloudfront.CreateDistributionWithTagsInput, _a2 ...request.Option) (*cloudfront.CreateDistributionWithTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateFieldLevelEncryptionConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateFieldLevelEncryptionConfig(_a0 *cloudfront.CreateFieldLevelEncryptionConfigInput) (*cloudfront.CreateFieldLevelEncryptionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateFieldLevelEncryptionConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateFieldLevelEncryptionConfigRequest(_a0 *cloudfront.CreateFieldLevelEncryptionConfigInput) (*request.Request, *cloudfront.CreateFieldLevelEncryptionConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateFieldLevelEncryptionConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateFieldLevelEncryptionConfigWithContext(_a0 context.Context, _a1 *cloudfront.CreateFieldLevelEncryptionConfigInput, _a2 ...request.Option) (*cloudfront.CreateFieldLevelEncryptionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateFieldLevelEncryptionProfile provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateFieldLevelEncryptionProfile(_a0 *cloudfront.CreateFieldLevelEncryptionProfileInput) (*cloudfront.CreateFieldLevelEncryptionProfileOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateFieldLevelEncryptionProfileRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateFieldLevelEncryptionProfileRequest(_a0 *cloudfront.CreateFieldLevelEncryptionProfileInput) (*request.Request, *cloudfront.CreateFieldLevelEncryptionProfileOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateFieldLevelEncryptionProfileWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateFieldLevelEncryptionProfileWithContext(_a0 context.Context, _a1 *cloudfront.CreateFieldLevelEncryptionProfileInput, _a2 ...request.Option) (*cloudfront.CreateFieldLevelEncryptionProfileOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateFunction provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateFunction(_a0 *cloudfront.CreateFunctionInput) (*cloudfront.CreateFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateFunctionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateFunctionRequest(_a0 *cloudfront.CreateFunctionInput) (*request.Request, *cloudfront.CreateFunctionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateFunctionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateFunctionWithContext(_a0 context.Context, _a1 *cloudfront.CreateFunctionInput, _a2 ...request.Option) (*cloudfront.CreateFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateInvalidation provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateInvalidation(_a0 *cloudfront.CreateInvalidationInput) (*cloudfront.CreateInvalidationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateInvalidationRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateInvalidationRequest(_a0 *cloudfront.CreateInvalidationInput) (*request.Request, *cloudfront.CreateInvalidationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateInvalidationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateInvalidationWithContext(_a0 context.Context, _a1 *cloudfront.CreateInvalidationInput, _a2 ...request.Option) (*cloudfront.CreateInvalidationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateKeyGroup provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateKeyGroup(_a0 *cloudfront.CreateKeyGroupInput) (*cloudfront.CreateKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateKeyGroupRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateKeyGroupRequest(_a0 *cloudfront.CreateKeyGroupInput) (*request.Request, *cloudfront.CreateKeyGroupOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateKeyGroupWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateKeyGroupWithContext(_a0 context.Context, _a1 *cloudfront.CreateKeyGroupInput, _a2 ...request.Option) (*cloudfront.CreateKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMonitoringSubscription provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateMonitoringSubscription(_a0 *cloudfront.CreateMonitoringSubscriptionInput) (*cloudfront.CreateMonitoringSubscriptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMonitoringSubscriptionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateMonitoringSubscriptionRequest(_a0 *cloudfront.CreateMonitoringSubscriptionInput) (*request.Request, *cloudfront.CreateMonitoringSubscriptionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMonitoringSubscriptionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateMonitoringSubscriptionWithContext(_a0 context.Context, _a1 *cloudfront.CreateMonitoringSubscriptionInput, _a2 ...request.Option) (*cloudfront.CreateMonitoringSubscriptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateOriginAccessControl provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateOriginAccessControl(_a0 *cloudfront.CreateOriginAccessControlInput) (*cloudfront.CreateOriginAccessControlOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateOriginAccessControlRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateOriginAccessControlRequest(_a0 *cloudfront.CreateOriginAccessControlInput) (*request.Request, *cloudfront.CreateOriginAccessControlOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateOriginAccessControlWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateOriginAccessControlWithContext(_a0 context.Context, _a1 *cloudfront.CreateOriginAccessControlInput, _a2 ...request.Option) (*cloudfront.CreateOriginAccessControlOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateOriginRequestPolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateOriginRequestPolicy(_a0 *cloudfront.CreateOriginRequestPolicyInput) (*cloudfront.CreateOriginRequestPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateOriginRequestPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateOriginRequestPolicyRequest(_a0 *cloudfront.CreateOriginRequestPolicyInput) (*request.Request, *cloudfront.CreateOriginRequestPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateOriginRequestPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateOriginRequestPolicyWithContext(_a0 context.Context, _a1 *cloudfront.CreateOriginRequestPolicyInput, _a2 ...request.Option) (*cloudfront.CreateOriginRequestPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePublicKey provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreatePublicKey(_a0 *cloudfront.CreatePublicKeyInput) (*cloudfront.CreatePublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePublicKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreatePublicKeyRequest(_a0 *cloudfront.CreatePublicKeyInput) (*request.Request, *cloudfront.CreatePublicKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePublicKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreatePublicKeyWithContext(_a0 context.Context, _a1 *cloudfront.CreatePublicKeyInput, _a2 ...request.Option) (*cloudfront.CreatePublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRealtimeLogConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateRealtimeLogConfig(_a0 *cloudfront.CreateRealtimeLogConfigInput) (*cloudfront.CreateRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRealtimeLogConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateRealtimeLogConfigRequest(_a0 *cloudfront.CreateRealtimeLogConfigInput) (*request.Request, *cloudfront.CreateRealtimeLogConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRealtimeLogConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateRealtimeLogConfigWithContext(_a0 context.Context, _a1 *cloudfront.CreateRealtimeLogConfigInput, _a2 ...request.Option) (*cloudfront.CreateRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateResponseHeadersPolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateResponseHeadersPolicy(_a0 *cloudfront.CreateResponseHeadersPolicyInput) (*cloudfront.CreateResponseHeadersPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateResponseHeadersPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateResponseHeadersPolicyRequest(_a0 *cloudfront.CreateResponseHeadersPolicyInput) (*request.Request, *cloudfront.CreateResponseHeadersPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateResponseHeadersPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateResponseHeadersPolicyWithContext(_a0 context.Context, _a1 *cloudfront.CreateResponseHeadersPolicyInput, _a2 ...request.Option) (*cloudfront.CreateResponseHeadersPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateStreamingDistribution provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateStreamingDistribution(_a0 *cloudfront.CreateStreamingDistributionInput) (*cloudfront.CreateStreamingDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateStreamingDistributionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateStreamingDistributionRequest(_a0 *cloudfront.CreateStreamingDistributionInput) (*request.Request, *cloudfront.CreateStreamingDistributionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateStreamingDistributionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateStreamingDistributionWithContext(_a0 context.Context, _a1 *cloudfront.CreateStreamingDistributionInput, _a2 ...request.Option) (*cloudfront.CreateStreamingDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateStreamingDistributionWithTags provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateStreamingDistributionWithTags(_a0 *cloudfront.CreateStreamingDistributionWithTagsInput) (*cloudfront.CreateStreamingDistributionWithTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateStreamingDistributionWithTagsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) CreateStreamingDistributionWithTagsRequest(_a0 *cloudfront.CreateStreamingDistributionWithTagsInput) (*request.Request, *cloudfront.CreateStreamingDistributionWithTagsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateStreamingDistributionWithTagsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) CreateStreamingDistributionWithTagsWithContext(_a0 context.Context, _a1 *cloudfront.CreateStreamingDistributionWithTagsInput, _a2 ...request.Option) (*cloudfront.CreateStreamingDistributionWithTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCachePolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteCachePolicy(_a0 *cloudfront.DeleteCachePolicyInput) (*cloudfront.DeleteCachePolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCachePolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteCachePolicyRequest(_a0 *cloudfront.DeleteCachePolicyInput) (*request.Request, *cloudfront.DeleteCachePolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCachePolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteCachePolicyWithContext(_a0 context.Context, _a1 *cloudfront.DeleteCachePolicyInput, _a2 ...request.Option) (*cloudfront.DeleteCachePolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCloudFrontOriginAccessIdentity provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteCloudFrontOriginAccessIdentity(_a0 *cloudfront.DeleteCloudFrontOriginAccessIdentityInput) (*cloudfront.DeleteCloudFrontOriginAccessIdentityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCloudFrontOriginAccessIdentityRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteCloudFrontOriginAccessIdentityRequest(_a0 *cloudfront.DeleteCloudFrontOriginAccessIdentityInput) (*request.Request, *cloudfront.DeleteCloudFrontOriginAccessIdentityOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCloudFrontOriginAccessIdentityWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteCloudFrontOriginAccessIdentityWithContext(_a0 context.Context, _a1 *cloudfront.DeleteCloudFrontOriginAccessIdentityInput, _a2 ...request.Option) (*cloudfront.DeleteCloudFrontOriginAccessIdentityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteDistribution provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteDistribution(_a0 *cloudfront.DeleteDistributionInput) (*cloudfront.DeleteDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteDistributionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteDistributionRequest(_a0 *cloudfront.DeleteDistributionInput) (*request.Request, *cloudfront.DeleteDistributionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteDistributionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteDistributionWithContext(_a0 context.Context, _a1 *cloudfront.DeleteDistributionInput, _a2 ...request.Option) (*cloudfront.DeleteDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteFieldLevelEncryptionConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteFieldLevelEncryptionConfig(_a0 *cloudfront.DeleteFieldLevelEncryptionConfigInput) (*cloudfront.DeleteFieldLevelEncryptionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteFieldLevelEncryptionConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteFieldLevelEncryptionConfigRequest(_a0 *cloudfront.DeleteFieldLevelEncryptionConfigInput) (*request.Request, *cloudfront.DeleteFieldLevelEncryptionConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteFieldLevelEncryptionConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteFieldLevelEncryptionConfigWithContext(_a0 context.Context, _a1 *cloudfront.DeleteFieldLevelEncryptionConfigInput, _a2 ...request.Option) (*cloudfront.DeleteFieldLevelEncryptionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteFieldLevelEncryptionProfile provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteFieldLevelEncryptionProfile(_a0 *cloudfront.DeleteFieldLevelEncryptionProfileInput) (*cloudfront.DeleteFieldLevelEncryptionProfileOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteFieldLevelEncryptionProfileRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteFieldLevelEncryptionProfileRequest(_a0 *cloudfront.DeleteFieldLevelEncryptionProfileInput) (*request.Request, *cloudfront.DeleteFieldLevelEncryptionProfileOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteFieldLevelEncryptionProfileWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteFieldLevelEncryptionProfileWithContext(_a0 context.Context, _a1 *cloudfront.DeleteFieldLevelEncryptionProfileInput, _a2 ...request.Option) (*cloudfront.DeleteFieldLevelEncryptionProfileOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteFunction provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteFunction(_a0 *cloudfront.DeleteFunctionInput) (*cloudfront.DeleteFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteFunctionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteFunctionRequest(_a0 *cloudfront.DeleteFunctionInput) (*request.Request, *cloudfront.DeleteFunctionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteFunctionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteFunctionWithContext(_a0 context.Context, _a1 *cloudfront.DeleteFunctionInput, _a2 ...request.Option) (*cloudfront.DeleteFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteKeyGroup provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteKeyGroup(_a0 *cloudfront.DeleteKeyGroupInput) (*cloudfront.DeleteKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteKeyGroupRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteKeyGroupRequest(_a0 *cloudfront.DeleteKeyGroupInput) (*request.Request, *cloudfront.DeleteKeyGroupOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteKeyGroupWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteKeyGroupWithContext(_a0 context.Context, _a1 *cloudfront.DeleteKeyGroupInput, _a2 ...request.Option) (*cloudfront.DeleteKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteMonitoringSubscription provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteMonitoringSubscription(_a0 *cloudfront.DeleteMonitoringSubscriptionInput) (*cloudfront.DeleteMonitoringSubscriptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteMonitoringSubscriptionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteMonitoringSubscriptionRequest(_a0 *cloudfront.DeleteMonitoringSubscriptionInput) (*request.Request, *cloudfront.DeleteMonitoringSubscriptionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteMonitoringSubscriptionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteMonitoringSubscriptionWithContext(_a0 context.Context, _a1 *cloudfront.DeleteMonitoringSubscriptionInput, _a2 ...request.Option) (*cloudfront.DeleteMonitoringSubscriptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteOriginAccessControl provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteOriginAccessControl(_a0 *cloudfront.DeleteOriginAccessControlInput) (*cloudfront.DeleteOriginAccessControlOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteOriginAccessControlRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteOriginAccessControlRequest(_a0 *cloudfront.DeleteOriginAccessControlInput) (*request.Request, *cloudfront.DeleteOriginAccessControlOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteOriginAccessControlWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteOriginAccessControlWithContext(_a0 context.Context, _a1 *cloudfront.DeleteOriginAccessControlInput, _a2 ...request.Option) (*cloudfront.DeleteOriginAccessControlOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteOriginRequestPolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteOriginRequestPolicy(_a0 *cloudfront.DeleteOriginRequestPolicyInput) (*cloudfront.DeleteOriginRequestPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteOriginRequestPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteOriginRequestPolicyRequest(_a0 *cloudfront.DeleteOriginRequestPolicyInput) (*request.Request, *cloudfront.DeleteOriginRequestPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteOriginRequestPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteOriginRequestPolicyWithContext(_a0 context.Context, _a1 *cloudfront.DeleteOriginRequestPolicyInput, _a2 ...request.Option) (*cloudfront.DeleteOriginRequestPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePublicKey provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeletePublicKey(_a0 *cloudfront.DeletePublicKeyInput) (*cloudfront.DeletePublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePublicKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeletePublicKeyRequest(_a0 *cloudfront.DeletePublicKeyInput) (*request.Request, *cloudfront.DeletePublicKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePublicKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeletePublicKeyWithContext(_a0 context.Context, _a1 *cloudfront.DeletePublicKeyInput, _a2 ...request.Option) (*cloudfront.DeletePublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRealtimeLogConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteRealtimeLogConfig(_a0 *cloudfront.DeleteRealtimeLogConfigInput) (*cloudfront.DeleteRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRealtimeLogConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteRealtimeLogConfigRequest(_a0 *cloudfront.DeleteRealtimeLogConfigInput) (*request.Request, *cloudfront.DeleteRealtimeLogConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRealtimeLogConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteRealtimeLogConfigWithContext(_a0 context.Context, _a1 *cloudfront.DeleteRealtimeLogConfigInput, _a2 ...request.Option) (*cloudfront.DeleteRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteResponseHeadersPolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteResponseHeadersPolicy(_a0 *cloudfront.DeleteResponseHeadersPolicyInput) (*cloudfront.DeleteResponseHeadersPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteResponseHeadersPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteResponseHeadersPolicyRequest(_a0 *cloudfront.DeleteResponseHeadersPolicyInput) (*request.Request, *cloudfront.DeleteResponseHeadersPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteResponseHeadersPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteResponseHeadersPolicyWithContext(_a0 context.Context, _a1 *cloudfront.DeleteResponseHeadersPolicyInput, _a2 ...request.Option) (*cloudfront.DeleteResponseHeadersPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStreamingDistribution provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteStreamingDistribution(_a0 *cloudfront.DeleteStreamingDistributionInput) (*cloudfront.DeleteStreamingDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStreamingDistributionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DeleteStreamingDistributionRequest(_a0 *cloudfront.DeleteStreamingDistributionInput) (*request.Request, *cloudfront.DeleteStreamingDistributionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStreamingDistributionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DeleteStreamingDistributionWithContext(_a0 context.Context, _a1 *cloudfront.DeleteStreamingDistributionInput, _a2 ...request.Option) (*cloudfront.DeleteStreamingDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeFunction provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DescribeFunction(_a0 *cloudfront.DescribeFunctionInput) (*cloudfront.DescribeFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeFunctionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) DescribeFunctionRequest(_a0 *cloudfront.DescribeFunctionInput) (*request.Request, *cloudfront.DescribeFunctionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeFunctionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) DescribeFunctionWithContext(_a0 context.Context, _a1 *cloudfront.DescribeFunctionInput, _a2 ...request.Option) (*cloudfront.DescribeFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCachePolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetCachePolicy(_a0 *cloudfront.GetCachePolicyInput) (*cloudfront.GetCachePolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCachePolicyConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetCachePolicyConfig(_a0 *cloudfront.GetCachePolicyConfigInput) (*cloudfront.GetCachePolicyConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCachePolicyConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetCachePolicyConfigRequest(_a0 *cloudfront.GetCachePolicyConfigInput) (*request.Request, *cloudfront.GetCachePolicyConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCachePolicyConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetCachePolicyConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetCachePolicyConfigInput, _a2 ...request.Option) (*cloudfront.GetCachePolicyConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCachePolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetCachePolicyRequest(_a0 *cloudfront.GetCachePolicyInput) (*request.Request, *cloudfront.GetCachePolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCachePolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetCachePolicyWithContext(_a0 context.Context, _a1 *cloudfront.GetCachePolicyInput, _a2 ...request.Option) (*cloudfront.GetCachePolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCloudFrontOriginAccessIdentity provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetCloudFrontOriginAccessIdentity(_a0 *cloudfront.GetCloudFrontOriginAccessIdentityInput) (*cloudfront.GetCloudFrontOriginAccessIdentityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCloudFrontOriginAccessIdentityConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetCloudFrontOriginAccessIdentityConfig(_a0 *cloudfront.GetCloudFrontOriginAccessIdentityConfigInput) (*cloudfront.GetCloudFrontOriginAccessIdentityConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCloudFrontOriginAccessIdentityConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetCloudFrontOriginAccessIdentityConfigRequest(_a0 *cloudfront.GetCloudFrontOriginAccessIdentityConfigInput) (*request.Request, *cloudfront.GetCloudFrontOriginAccessIdentityConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCloudFrontOriginAccessIdentityConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetCloudFrontOriginAccessIdentityConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetCloudFrontOriginAccessIdentityConfigInput, _a2 ...request.Option) (*cloudfront.GetCloudFrontOriginAccessIdentityConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCloudFrontOriginAccessIdentityRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetCloudFrontOriginAccessIdentityRequest(_a0 *cloudfront.GetCloudFrontOriginAccessIdentityInput) (*request.Request, *cloudfront.GetCloudFrontOriginAccessIdentityOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCloudFrontOriginAccessIdentityWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetCloudFrontOriginAccessIdentityWithContext(_a0 context.Context, _a1 *cloudfront.GetCloudFrontOriginAccessIdentityInput, _a2 ...request.Option) (*cloudfront.GetCloudFrontOriginAccessIdentityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDistribution provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetDistribution(_a0 *cloudfront.GetDistributionInput) (*cloudfront.GetDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDistributionConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetDistributionConfig(_a0 *cloudfront.GetDistributionConfigInput) (*cloudfront.GetDistributionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDistributionConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetDistributionConfigRequest(_a0 *cloudfront.GetDistributionConfigInput) (*request.Request, *cloudfront.GetDistributionConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDistributionConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetDistributionConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetDistributionConfigInput, _a2 ...request.Option) (*cloudfront.GetDistributionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDistributionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetDistributionRequest(_a0 *cloudfront.GetDistributionInput) (*request.Request, *cloudfront.GetDistributionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDistributionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetDistributionWithContext(_a0 context.Context, _a1 *cloudfront.GetDistributionInput, _a2 ...request.Option) (*cloudfront.GetDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryption provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFieldLevelEncryption(_a0 *cloudfront.GetFieldLevelEncryptionInput) (*cloudfront.GetFieldLevelEncryptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionConfig(_a0 *cloudfront.GetFieldLevelEncryptionConfigInput) (*cloudfront.GetFieldLevelEncryptionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionConfigRequest(_a0 *cloudfront.GetFieldLevelEncryptionConfigInput) (*request.Request, *cloudfront.GetFieldLevelEncryptionConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetFieldLevelEncryptionConfigInput, _a2 ...request.Option) (*cloudfront.GetFieldLevelEncryptionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionProfile provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionProfile(_a0 *cloudfront.GetFieldLevelEncryptionProfileInput) (*cloudfront.GetFieldLevelEncryptionProfileOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionProfileConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionProfileConfig(_a0 *cloudfront.GetFieldLevelEncryptionProfileConfigInput) (*cloudfront.GetFieldLevelEncryptionProfileConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionProfileConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionProfileConfigRequest(_a0 *cloudfront.GetFieldLevelEncryptionProfileConfigInput) (*request.Request, *cloudfront.GetFieldLevelEncryptionProfileConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionProfileConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionProfileConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetFieldLevelEncryptionProfileConfigInput, _a2 ...request.Option) (*cloudfront.GetFieldLevelEncryptionProfileConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionProfileRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionProfileRequest(_a0 *cloudfront.GetFieldLevelEncryptionProfileInput) (*request.Request, *cloudfront.GetFieldLevelEncryptionProfileOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionProfileWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionProfileWithContext(_a0 context.Context, _a1 *cloudfront.GetFieldLevelEncryptionProfileInput, _a2 ...request.Option) (*cloudfront.GetFieldLevelEncryptionProfileOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionRequest(_a0 *cloudfront.GetFieldLevelEncryptionInput) (*request.Request, *cloudfront.GetFieldLevelEncryptionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFieldLevelEncryptionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetFieldLevelEncryptionWithContext(_a0 context.Context, _a1 *cloudfront.GetFieldLevelEncryptionInput, _a2 ...request.Option) (*cloudfront.GetFieldLevelEncryptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFunction provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFunction(_a0 *cloudfront.GetFunctionInput) (*cloudfront.GetFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFunctionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetFunctionRequest(_a0 *cloudfront.GetFunctionInput) (*request.Request, *cloudfront.GetFunctionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFunctionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetFunctionWithContext(_a0 context.Context, _a1 *cloudfront.GetFunctionInput, _a2 ...request.Option) (*cloudfront.GetFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetInvalidation provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetInvalidation(_a0 *cloudfront.GetInvalidationInput) (*cloudfront.GetInvalidationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetInvalidationRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetInvalidationRequest(_a0 *cloudfront.GetInvalidationInput) (*request.Request, *cloudfront.GetInvalidationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetInvalidationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetInvalidationWithContext(_a0 context.Context, _a1 *cloudfront.GetInvalidationInput, _a2 ...request.Option) (*cloudfront.GetInvalidationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyGroup provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetKeyGroup(_a0 *cloudfront.GetKeyGroupInput) (*cloudfront.GetKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyGroupConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetKeyGroupConfig(_a0 *cloudfront.GetKeyGroupConfigInput) (*cloudfront.GetKeyGroupConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyGroupConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetKeyGroupConfigRequest(_a0 *cloudfront.GetKeyGroupConfigInput) (*request.Request, *cloudfront.GetKeyGroupConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyGroupConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetKeyGroupConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetKeyGroupConfigInput, _a2 ...request.Option) (*cloudfront.GetKeyGroupConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyGroupRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetKeyGroupRequest(_a0 *cloudfront.GetKeyGroupInput) (*request.Request, *cloudfront.GetKeyGroupOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyGroupWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetKeyGroupWithContext(_a0 context.Context, _a1 *cloudfront.GetKeyGroupInput, _a2 ...request.Option) (*cloudfront.GetKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMonitoringSubscription provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetMonitoringSubscription(_a0 *cloudfront.GetMonitoringSubscriptionInput) (*cloudfront.GetMonitoringSubscriptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMonitoringSubscriptionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetMonitoringSubscriptionRequest(_a0 *cloudfront.GetMonitoringSubscriptionInput) (*request.Request, *cloudfront.GetMonitoringSubscriptionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMonitoringSubscriptionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetMonitoringSubscriptionWithContext(_a0 context.Context, _a1 *cloudfront.GetMonitoringSubscriptionInput, _a2 ...request.Option) (*cloudfront.GetMonitoringSubscriptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginAccessControl provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetOriginAccessControl(_a0 *cloudfront.GetOriginAccessControlInput) (*cloudfront.GetOriginAccessControlOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginAccessControlConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetOriginAccessControlConfig(_a0 *cloudfront.GetOriginAccessControlConfigInput) (*cloudfront.GetOriginAccessControlConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginAccessControlConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetOriginAccessControlConfigRequest(_a0 *cloudfront.GetOriginAccessControlConfigInput) (*request.Request, *cloudfront.GetOriginAccessControlConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginAccessControlConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetOriginAccessControlConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetOriginAccessControlConfigInput, _a2 ...request.Option) (*cloudfront.GetOriginAccessControlConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginAccessControlRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetOriginAccessControlRequest(_a0 *cloudfront.GetOriginAccessControlInput) (*request.Request, *cloudfront.GetOriginAccessControlOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginAccessControlWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetOriginAccessControlWithContext(_a0 context.Context, _a1 *cloudfront.GetOriginAccessControlInput, _a2 ...request.Option) (*cloudfront.GetOriginAccessControlOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginRequestPolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetOriginRequestPolicy(_a0 *cloudfront.GetOriginRequestPolicyInput) (*cloudfront.GetOriginRequestPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginRequestPolicyConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetOriginRequestPolicyConfig(_a0 *cloudfront.GetOriginRequestPolicyConfigInput) (*cloudfront.GetOriginRequestPolicyConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginRequestPolicyConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetOriginRequestPolicyConfigRequest(_a0 *cloudfront.GetOriginRequestPolicyConfigInput) (*request.Request, *cloudfront.GetOriginRequestPolicyConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginRequestPolicyConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetOriginRequestPolicyConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetOriginRequestPolicyConfigInput, _a2 ...request.Option) (*cloudfront.GetOriginRequestPolicyConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginRequestPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetOriginRequestPolicyRequest(_a0 *cloudfront.GetOriginRequestPolicyInput) (*request.Request, *cloudfront.GetOriginRequestPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetOriginRequestPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetOriginRequestPolicyWithContext(_a0 context.Context, _a1 *cloudfront.GetOriginRequestPolicyInput, _a2 ...request.Option) (*cloudfront.GetOriginRequestPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicKey provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetPublicKey(_a0 *cloudfront.GetPublicKeyInput) (*cloudfront.GetPublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicKeyConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetPublicKeyConfig(_a0 *cloudfront.GetPublicKeyConfigInput) (*cloudfront.GetPublicKeyConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicKeyConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetPublicKeyConfigRequest(_a0 *cloudfront.GetPublicKeyConfigInput) (*request.Request, *cloudfront.GetPublicKeyConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicKeyConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetPublicKeyConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetPublicKeyConfigInput, _a2 ...request.Option) (*cloudfront.GetPublicKeyConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetPublicKeyRequest(_a0 *cloudfront.GetPublicKeyInput) (*request.Request, *cloudfront.GetPublicKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetPublicKeyWithContext(_a0 context.Context, _a1 *cloudfront.GetPublicKeyInput, _a2 ...request.Option) (*cloudfront.GetPublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRealtimeLogConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetRealtimeLogConfig(_a0 *cloudfront.GetRealtimeLogConfigInput) (*cloudfront.GetRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRealtimeLogConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetRealtimeLogConfigRequest(_a0 *cloudfront.GetRealtimeLogConfigInput) (*request.Request, *cloudfront.GetRealtimeLogConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRealtimeLogConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetRealtimeLogConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetRealtimeLogConfigInput, _a2 ...request.Option) (*cloudfront.GetRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResponseHeadersPolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetResponseHeadersPolicy(_a0 *cloudfront.GetResponseHeadersPolicyInput) (*cloudfront.GetResponseHeadersPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResponseHeadersPolicyConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetResponseHeadersPolicyConfig(_a0 *cloudfront.GetResponseHeadersPolicyConfigInput) (*cloudfront.GetResponseHeadersPolicyConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResponseHeadersPolicyConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetResponseHeadersPolicyConfigRequest(_a0 *cloudfront.GetResponseHeadersPolicyConfigInput) (*request.Request, *cloudfront.GetResponseHeadersPolicyConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResponseHeadersPolicyConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetResponseHeadersPolicyConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetResponseHeadersPolicyConfigInput, _a2 ...request.Option) (*cloudfront.GetResponseHeadersPolicyConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResponseHeadersPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetResponseHeadersPolicyRequest(_a0 *cloudfront.GetResponseHeadersPolicyInput) (*request.Request, *cloudfront.GetResponseHeadersPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResponseHeadersPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetResponseHeadersPolicyWithContext(_a0 context.Context, _a1 *cloudfront.GetResponseHeadersPolicyInput, _a2 ...request.Option) (*cloudfront.GetResponseHeadersPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStreamingDistribution provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetStreamingDistribution(_a0 *cloudfront.GetStreamingDistributionInput) (*cloudfront.GetStreamingDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStreamingDistributionConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetStreamingDistributionConfig(_a0 *cloudfront.GetStreamingDistributionConfigInput) (*cloudfront.GetStreamingDistributionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStreamingDistributionConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetStreamingDistributionConfigRequest(_a0 *cloudfront.GetStreamingDistributionConfigInput) (*request.Request, *cloudfront.GetStreamingDistributionConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStreamingDistributionConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetStreamingDistributionConfigWithContext(_a0 context.Context, _a1 *cloudfront.GetStreamingDistributionConfigInput, _a2 ...request.Option) (*cloudfront.GetStreamingDistributionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStreamingDistributionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) GetStreamingDistributionRequest(_a0 *cloudfront.GetStreamingDistributionInput) (*request.Request, *cloudfront.GetStreamingDistributionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStreamingDistributionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) GetStreamingDistributionWithContext(_a0 context.Context, _a1 *cloudfront.GetStreamingDistributionInput, _a2 ...request.Option) (*cloudfront.GetStreamingDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListCachePolicies provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListCachePolicies(_a0 *cloudfront.ListCachePoliciesInput) (*cloudfront.ListCachePoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListCachePoliciesRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListCachePoliciesRequest(_a0 *cloudfront.ListCachePoliciesInput) (*request.Request, *cloudfront.ListCachePoliciesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListCachePoliciesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListCachePoliciesWithContext(_a0 context.Context, _a1 *cloudfront.ListCachePoliciesInput, _a2 ...request.Option) (*cloudfront.ListCachePoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListCloudFrontOriginAccessIdentities provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListCloudFrontOriginAccessIdentities(_a0 *cloudfront.ListCloudFrontOriginAccessIdentitiesInput) (*cloudfront.ListCloudFrontOriginAccessIdentitiesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListCloudFrontOriginAccessIdentitiesPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeCloudFront) ListCloudFrontOriginAccessIdentitiesPages(_a0 *cloudfront.ListCloudFrontOriginAccessIdentitiesInput, _a1 func(*cloudfront.ListCloudFrontOriginAccessIdentitiesOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListCloudFrontOriginAccessIdentitiesPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeCloudFront) ListCloudFrontOriginAccessIdentitiesPagesWithContext(_a0 context.Context, _a1 *cloudfront.ListCloudFrontOriginAccessIdentitiesInput, _a2 func(*cloudfront.ListCloudFrontOriginAccessIdentitiesOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListCloudFrontOriginAccessIdentitiesRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListCloudFrontOriginAccessIdentitiesRequest(_a0 *cloudfront.ListCloudFrontOriginAccessIdentitiesInput) (*request.Request, *cloudfront.ListCloudFrontOriginAccessIdentitiesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListCloudFrontOriginAccessIdentitiesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListCloudFrontOriginAccessIdentitiesWithContext(_a0 context.Context, _a1 *cloudfront.ListCloudFrontOriginAccessIdentitiesInput, _a2 ...request.Option) (*cloudfront.ListCloudFrontOriginAccessIdentitiesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListConflictingAliases provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListConflictingAliases(_a0 *cloudfront.ListConflictingAliasesInput) (*cloudfront.ListConflictingAliasesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListConflictingAliasesRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListConflictingAliasesRequest(_a0 *cloudfront.ListConflictingAliasesInput) (*request.Request, *cloudfront.ListConflictingAliasesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListConflictingAliasesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListConflictingAliasesWithContext(_a0 context.Context, _a1 *cloudfront.ListConflictingAliasesInput, _a2 ...request.Option) (*cloudfront.ListConflictingAliasesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributions provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributions(_a0 *cloudfront.ListDistributionsInput) (*cloudfront.ListDistributionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByCachePolicyId provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByCachePolicyId(_a0 *cloudfront.ListDistributionsByCachePolicyIdInput) (*cloudfront.ListDistributionsByCachePolicyIdOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByCachePolicyIdRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByCachePolicyIdRequest(_a0 *cloudfront.ListDistributionsByCachePolicyIdInput) (*request.Request, *cloudfront.ListDistributionsByCachePolicyIdOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByCachePolicyIdWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListDistributionsByCachePolicyIdWithContext(_a0 context.Context, _a1 *cloudfront.ListDistributionsByCachePolicyIdInput, _a2 ...request.Option) (*cloudfront.ListDistributionsByCachePolicyIdOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByKeyGroup provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByKeyGroup(_a0 *cloudfront.ListDistributionsByKeyGroupInput) (*cloudfront.ListDistributionsByKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByKeyGroupRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByKeyGroupRequest(_a0 *cloudfront.ListDistributionsByKeyGroupInput) (*request.Request, *cloudfront.ListDistributionsByKeyGroupOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByKeyGroupWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListDistributionsByKeyGroupWithContext(_a0 context.Context, _a1 *cloudfront.ListDistributionsByKeyGroupInput, _a2 ...request.Option) (*cloudfront.ListDistributionsByKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByOriginRequestPolicyId provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByOriginRequestPolicyId(_a0 *cloudfront.ListDistributionsByOriginRequestPolicyIdInput) (*cloudfront.ListDistributionsByOriginRequestPolicyIdOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByOriginRequestPolicyIdRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByOriginRequestPolicyIdRequest(_a0 *cloudfront.ListDistributionsByOriginRequestPolicyIdInput) (*request.Request, *cloudfront.ListDistributionsByOriginRequestPolicyIdOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByOriginRequestPolicyIdWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListDistributionsByOriginRequestPolicyIdWithContext(_a0 context.Context, _a1 *cloudfront.ListDistributionsByOriginRequestPolicyIdInput, _a2 ...request.Option) (*cloudfront.ListDistributionsByOriginRequestPolicyIdOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByRealtimeLogConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByRealtimeLogConfig(_a0 *cloudfront.ListDistributionsByRealtimeLogConfigInput) (*cloudfront.ListDistributionsByRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByRealtimeLogConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByRealtimeLogConfigRequest(_a0 *cloudfront.ListDistributionsByRealtimeLogConfigInput) (*request.Request, *cloudfront.ListDistributionsByRealtimeLogConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByRealtimeLogConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListDistributionsByRealtimeLogConfigWithContext(_a0 context.Context, _a1 *cloudfront.ListDistributionsByRealtimeLogConfigInput, _a2 ...request.Option) (*cloudfront.ListDistributionsByRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByResponseHeadersPolicyId provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByResponseHeadersPolicyId(_a0 *cloudfront.ListDistributionsByResponseHeadersPolicyIdInput) (*cloudfront.ListDistributionsByResponseHeadersPolicyIdOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByResponseHeadersPolicyIdRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByResponseHeadersPolicyIdRequest(_a0 *cloudfront.ListDistributionsByResponseHeadersPolicyIdInput) (*request.Request, *cloudfront.ListDistributionsByResponseHeadersPolicyIdOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByResponseHeadersPolicyIdWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListDistributionsByResponseHeadersPolicyIdWithContext(_a0 context.Context, _a1 *cloudfront.ListDistributionsByResponseHeadersPolicyIdInput, _a2 ...request.Option) (*cloudfront.ListDistributionsByResponseHeadersPolicyIdOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByWebACLId provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByWebACLId(_a0 *cloudfront.ListDistributionsByWebACLIdInput) (*cloudfront.ListDistributionsByWebACLIdOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByWebACLIdRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsByWebACLIdRequest(_a0 *cloudfront.ListDistributionsByWebACLIdInput) (*request.Request, *cloudfront.ListDistributionsByWebACLIdOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsByWebACLIdWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListDistributionsByWebACLIdWithContext(_a0 context.Context, _a1 *cloudfront.ListDistributionsByWebACLIdInput, _a2 ...request.Option) (*cloudfront.ListDistributionsByWebACLIdOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeCloudFront) ListDistributionsPages(_a0 *cloudfront.ListDistributionsInput, _a1 func(*cloudfront.ListDistributionsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListDistributionsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeCloudFront) ListDistributionsPagesWithContext(_a0 context.Context, _a1 *cloudfront.ListDistributionsInput, _a2 func(*cloudfront.ListDistributionsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListDistributionsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListDistributionsRequest(_a0 *cloudfront.ListDistributionsInput) (*request.Request, *cloudfront.ListDistributionsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListDistributionsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListDistributionsWithContext(_a0 context.Context, _a1 *cloudfront.ListDistributionsInput, _a2 ...request.Option) (*cloudfront.ListDistributionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFieldLevelEncryptionConfigs provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListFieldLevelEncryptionConfigs(_a0 *cloudfront.ListFieldLevelEncryptionConfigsInput) (*cloudfront.ListFieldLevelEncryptionConfigsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFieldLevelEncryptionConfigsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListFieldLevelEncryptionConfigsRequest(_a0 *cloudfront.ListFieldLevelEncryptionConfigsInput) (*request.Request, *cloudfront.ListFieldLevelEncryptionConfigsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFieldLevelEncryptionConfigsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListFieldLevelEncryptionConfigsWithContext(_a0 context.Context, _a1 *cloudfront.ListFieldLevelEncryptionConfigsInput, _a2 ...request.Option) (*cloudfront.ListFieldLevelEncryptionConfigsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFieldLevelEncryptionProfiles provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListFieldLevelEncryptionProfiles(_a0 *cloudfront.ListFieldLevelEncryptionProfilesInput) (*cloudfront.ListFieldLevelEncryptionProfilesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFieldLevelEncryptionProfilesRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListFieldLevelEncryptionProfilesRequest(_a0 *cloudfront.ListFieldLevelEncryptionProfilesInput) (*request.Request, *cloudfront.ListFieldLevelEncryptionProfilesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFieldLevelEncryptionProfilesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListFieldLevelEncryptionProfilesWithContext(_a0 context.Context, _a1 *cloudfront.ListFieldLevelEncryptionProfilesInput, _a2 ...request.Option) (*cloudfront.ListFieldLevelEncryptionProfilesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFunctions provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListFunctions(_a0 *cloudfront.ListFunctionsInput) (*cloudfront.ListFunctionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFunctionsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListFunctionsRequest(_a0 *cloudfront.ListFunctionsInput) (*request.Request, *cloudfront.ListFunctionsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFunctionsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListFunctionsWithContext(_a0 context.Context, _a1 *cloudfront.ListFunctionsInput, _a2 ...request.Option) (*cloudfront.ListFunctionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListInvalidations provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListInvalidations(_a0 *cloudfront.ListInvalidationsInput) (*cloudfront.ListInvalidationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListInvalidationsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeCloudFront) ListInvalidationsPages(_a0 *cloudfront.ListInvalidationsInput, _a1 func(*cloudfront.ListInvalidationsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListInvalidationsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeCloudFront) ListInvalidationsPagesWithContext(_a0 context.Context, _a1 *cloudfront.ListInvalidationsInput, _a2 func(*cloudfront.ListInvalidationsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListInvalidationsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListInvalidationsRequest(_a0 *cloudfront.ListInvalidationsInput) (*request.Request, *cloudfront.ListInvalidationsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListInvalidationsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListInvalidationsWithContext(_a0 context.Context, _a1 *cloudfront.ListInvalidationsInput, _a2 ...request.Option) (*cloudfront.ListInvalidationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListKeyGroups provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListKeyGroups(_a0 *cloudfront.ListKeyGroupsInput) (*cloudfront.ListKeyGroupsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListKeyGroupsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListKeyGroupsRequest(_a0 *cloudfront.ListKeyGroupsInput) (*request.Request, *cloudfront.ListKeyGroupsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListKeyGroupsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListKeyGroupsWithContext(_a0 context.Context, _a1 *cloudfront.ListKeyGroupsInput, _a2 ...request.Option) (*cloudfront.ListKeyGroupsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListOriginAccessControls provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListOriginAccessControls(_a0 *cloudfront.ListOriginAccessControlsInput) (*cloudfront.ListOriginAccessControlsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListOriginAccessControlsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListOriginAccessControlsRequest(_a0 *cloudfront.ListOriginAccessControlsInput) (*request.Request, *cloudfront.ListOriginAccessControlsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListOriginAccessControlsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListOriginAccessControlsWithContext(_a0 context.Context, _a1 *cloudfront.ListOriginAccessControlsInput, _a2 ...request.Option) (*cloudfront.ListOriginAccessControlsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListOriginRequestPolicies provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListOriginRequestPolicies(_a0 *cloudfront.ListOriginRequestPoliciesInput) (*cloudfront.ListOriginRequestPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListOriginRequestPoliciesRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListOriginRequestPoliciesRequest(_a0 *cloudfront.ListOriginRequestPoliciesInput) (*request.Request, *cloudfront.ListOriginRequestPoliciesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListOriginRequestPoliciesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListOriginRequestPoliciesWithContext(_a0 context.Context, _a1 *cloudfront.ListOriginRequestPoliciesInput, _a2 ...request.Option) (*cloudfront.ListOriginRequestPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPublicKeys provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListPublicKeys(_a0 *cloudfront.ListPublicKeysInput) (*cloudfront.ListPublicKeysOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPublicKeysRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListPublicKeysRequest(_a0 *cloudfront.ListPublicKeysInput) (*request.Request, *cloudfront.ListPublicKeysOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPublicKeysWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListPublicKeysWithContext(_a0 context.Context, _a1 *cloudfront.ListPublicKeysInput, _a2 ...request.Option) (*cloudfront.ListPublicKeysOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRealtimeLogConfigs provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListRealtimeLogConfigs(_a0 *cloudfront.ListRealtimeLogConfigsInput) (*cloudfront.ListRealtimeLogConfigsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRealtimeLogConfigsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListRealtimeLogConfigsRequest(_a0 *cloudfront.ListRealtimeLogConfigsInput) (*request.Request, *cloudfront.ListRealtimeLogConfigsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRealtimeLogConfigsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListRealtimeLogConfigsWithContext(_a0 context.Context, _a1 *cloudfront.ListRealtimeLogConfigsInput, _a2 ...request.Option) (*cloudfront.ListRealtimeLogConfigsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListResponseHeadersPolicies provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListResponseHeadersPolicies(_a0 *cloudfront.ListResponseHeadersPoliciesInput) (*cloudfront.ListResponseHeadersPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListResponseHeadersPoliciesRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListResponseHeadersPoliciesRequest(_a0 *cloudfront.ListResponseHeadersPoliciesInput) (*request.Request, *cloudfront.ListResponseHeadersPoliciesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListResponseHeadersPoliciesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListResponseHeadersPoliciesWithContext(_a0 context.Context, _a1 *cloudfront.ListResponseHeadersPoliciesInput, _a2 ...request.Option) (*cloudfront.ListResponseHeadersPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListStreamingDistributions provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListStreamingDistributions(_a0 *cloudfront.ListStreamingDistributionsInput) (*cloudfront.ListStreamingDistributionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListStreamingDistributionsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeCloudFront) ListStreamingDistributionsPages(_a0 *cloudfront.ListStreamingDistributionsInput, _a1 func(*cloudfront.ListStreamingDistributionsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListStreamingDistributionsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeCloudFront) ListStreamingDistributionsPagesWithContext(_a0 context.Context, _a1 *cloudfront.ListStreamingDistributionsInput, _a2 func(*cloudfront.ListStreamingDistributionsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListStreamingDistributionsRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListStreamingDistributionsRequest(_a0 *cloudfront.ListStreamingDistributionsInput) (*request.Request, *cloudfront.ListStreamingDistributionsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListStreamingDistributionsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListStreamingDistributionsWithContext(_a0 context.Context, _a1 *cloudfront.ListStreamingDistributionsInput, _a2 ...request.Option) (*cloudfront.ListStreamingDistributionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTagsForResource provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListTagsForResource(_a0 *cloudfront.ListTagsForResourceInput) (*cloudfront.ListTagsForResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTagsForResourceRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) ListTagsForResourceRequest(_a0 *cloudfront.ListTagsForResourceInput) (*request.Request, *cloudfront.ListTagsForResourceOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTagsForResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) ListTagsForResourceWithContext(_a0 context.Context, _a1 *cloudfront.ListTagsForResourceInput, _a2 ...request.Option) (*cloudfront.ListTagsForResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PublishFunction provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) PublishFunction(_a0 *cloudfront.PublishFunctionInput) (*cloudfront.PublishFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PublishFunctionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) PublishFunctionRequest(_a0 *cloudfront.PublishFunctionInput) (*request.Request, *cloudfront.PublishFunctionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PublishFunctionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) PublishFunctionWithContext(_a0 context.Context, _a1 *cloudfront.PublishFunctionInput, _a2 ...request.Option) (*cloudfront.PublishFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TagResource provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) TagResource(_a0 *cloudfront.TagResourceInput) (*cloudfront.TagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TagResourceRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) TagResourceRequest(_a0 *cloudfront.TagResourceInput) (*request.Request, *cloudfront.TagResourceOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TagResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) TagResourceWithContext(_a0 context.Context, _a1 *cloudfront.TagResourceInput, _a2 ...request.Option) (*cloudfront.TagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TestFunction provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) TestFunction(_a0 *cloudfront.TestFunctionInput) (*cloudfront.TestFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TestFunctionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) TestFunctionRequest(_a0 *cloudfront.TestFunctionInput) (*request.Request, *cloudfront.TestFunctionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TestFunctionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) TestFunctionWithContext(_a0 context.Context, _a1 *cloudfront.TestFunctionInput, _a2 ...request.Option) (*cloudfront.TestFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UntagResource provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UntagResource(_a0 *cloudfront.UntagResourceInput) (*cloudfront.UntagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UntagResourceRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UntagResourceRequest(_a0 *cloudfront.UntagResourceInput) (*request.Request, *cloudfront.UntagResourceOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UntagResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UntagResourceWithContext(_a0 context.Context, _a1 *cloudfront.UntagResourceInput, _a2 ...request.Option) (*cloudfront.UntagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateCachePolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateCachePolicy(_a0 *cloudfront.UpdateCachePolicyInput) (*cloudfront.UpdateCachePolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateCachePolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateCachePolicyRequest(_a0 *cloudfront.UpdateCachePolicyInput) (*request.Request, *cloudfront.UpdateCachePolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateCachePolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateCachePolicyWithContext(_a0 context.Context, _a1 *cloudfront.UpdateCachePolicyInput, _a2 ...request.Option) (*cloudfront.UpdateCachePolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateCloudFrontOriginAccessIdentity provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateCloudFrontOriginAccessIdentity(_a0 *cloudfront.UpdateCloudFrontOriginAccessIdentityInput) (*cloudfront.UpdateCloudFrontOriginAccessIdentityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateCloudFrontOriginAccessIdentityRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateCloudFrontOriginAccessIdentityRequest(_a0 *cloudfront.UpdateCloudFrontOriginAccessIdentityInput) (*request.Request, *cloudfront.UpdateCloudFrontOriginAccessIdentityOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateCloudFrontOriginAccessIdentityWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateCloudFrontOriginAccessIdentityWithContext(_a0 context.Context, _a1 *cloudfront.UpdateCloudFrontOriginAccessIdentityInput, _a2 ...request.Option) (*cloudfront.UpdateCloudFrontOriginAccessIdentityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDistribution provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateDistribution(_a0 *cloudfront.UpdateDistributionInput) (*cloudfront.UpdateDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDistributionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateDistributionRequest(_a0 *cloudfront.UpdateDistributionInput) (*request.Request, *cloudfront.UpdateDistributionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDistributionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateDistributionWithContext(_a0 context.Context, _a1 *cloudfront.UpdateDistributionInput, _a2 ...request.Option) (*cloudfront.UpdateDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateFieldLevelEncryptionConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateFieldLevelEncryptionConfig(_a0 *cloudfront.UpdateFieldLevelEncryptionConfigInput) (*cloudfront.UpdateFieldLevelEncryptionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateFieldLevelEncryptionConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateFieldLevelEncryptionConfigRequest(_a0 *cloudfront.UpdateFieldLevelEncryptionConfigInput) (*request.Request, *cloudfront.UpdateFieldLevelEncryptionConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateFieldLevelEncryptionConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateFieldLevelEncryptionConfigWithContext(_a0 context.Context, _a1 *cloudfront.UpdateFieldLevelEncryptionConfigInput, _a2 ...request.Option) (*cloudfront.UpdateFieldLevelEncryptionConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateFieldLevelEncryptionProfile provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateFieldLevelEncryptionProfile(_a0 *cloudfront.UpdateFieldLevelEncryptionProfileInput) (*cloudfront.UpdateFieldLevelEncryptionProfileOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateFieldLevelEncryptionProfileRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateFieldLevelEncryptionProfileRequest(_a0 *cloudfront.UpdateFieldLevelEncryptionProfileInput) (*request.Request, *cloudfront.UpdateFieldLevelEncryptionProfileOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateFieldLevelEncryptionProfileWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateFieldLevelEncryptionProfileWithContext(_a0 context.Context, _a1 *cloudfront.UpdateFieldLevelEncryptionProfileInput, _a2 ...request.Option) (*cloudfront.UpdateFieldLevelEncryptionProfileOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateFunction provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateFunction(_a0 *cloudfront.UpdateFunctionInput) (*cloudfront.UpdateFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateFunctionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateFunctionRequest(_a0 *cloudfront.UpdateFunctionInput) (*request.Request, *cloudfront.UpdateFunctionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateFunctionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateFunctionWithContext(_a0 context.Context, _a1 *cloudfront.UpdateFunctionInput, _a2 ...request.Option) (*cloudfront.UpdateFunctionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateKeyGroup provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateKeyGroup(_a0 *cloudfront.UpdateKeyGroupInput) (*cloudfront.UpdateKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateKeyGroupRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateKeyGroupRequest(_a0 *cloudfront.UpdateKeyGroupInput) (*request.Request, *cloudfront.UpdateKeyGroupOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateKeyGroupWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateKeyGroupWithContext(_a0 context.Context, _a1 *cloudfront.UpdateKeyGroupInput, _a2 ...request.Option) (*cloudfront.UpdateKeyGroupOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateOriginAccessControl provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateOriginAccessControl(_a0 *cloudfront.UpdateOriginAccessControlInput) (*cloudfront.UpdateOriginAccessControlOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateOriginAccessControlRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateOriginAccessControlRequest(_a0 *cloudfront.UpdateOriginAccessControlInput) (*request.Request, *cloudfront.UpdateOriginAccessControlOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateOriginAccessControlWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateOriginAccessControlWithContext(_a0 context.Context, _a1 *cloudfront.UpdateOriginAccessControlInput, _a2 ...request.Option) (*cloudfront.UpdateOriginAccessControlOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateOriginRequestPolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateOriginRequestPolicy(_a0 *cloudfront.UpdateOriginRequestPolicyInput) (*cloudfront.UpdateOriginRequestPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateOriginRequestPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateOriginRequestPolicyRequest(_a0 *cloudfront.UpdateOriginRequestPolicyInput) (*request.Request, *cloudfront.UpdateOriginRequestPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateOriginRequestPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateOriginRequestPolicyWithContext(_a0 context.Context, _a1 *cloudfront.UpdateOriginRequestPolicyInput, _a2 ...request.Option) (*cloudfront.UpdateOriginRequestPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdatePublicKey provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdatePublicKey(_a0 *cloudfront.UpdatePublicKeyInput) (*cloudfront.UpdatePublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdatePublicKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdatePublicKeyRequest(_a0 *cloudfront.UpdatePublicKeyInput) (*request.Request, *cloudfront.UpdatePublicKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdatePublicKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdatePublicKeyWithContext(_a0 context.Context, _a1 *cloudfront.UpdatePublicKeyInput, _a2 ...request.Option) (*cloudfront.UpdatePublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRealtimeLogConfig provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateRealtimeLogConfig(_a0 *cloudfront.UpdateRealtimeLogConfigInput) (*cloudfront.UpdateRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRealtimeLogConfigRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateRealtimeLogConfigRequest(_a0 *cloudfront.UpdateRealtimeLogConfigInput) (*request.Request, *cloudfront.UpdateRealtimeLogConfigOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRealtimeLogConfigWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateRealtimeLogConfigWithContext(_a0 context.Context, _a1 *cloudfront.UpdateRealtimeLogConfigInput, _a2 ...request.Option) (*cloudfront.UpdateRealtimeLogConfigOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateResponseHeadersPolicy provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateResponseHeadersPolicy(_a0 *cloudfront.UpdateResponseHeadersPolicyInput) (*cloudfront.UpdateResponseHeadersPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateResponseHeadersPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateResponseHeadersPolicyRequest(_a0 *cloudfront.UpdateResponseHeadersPolicyInput) (*request.Request, *cloudfront.UpdateResponseHeadersPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateResponseHeadersPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateResponseHeadersPolicyWithContext(_a0 context.Context, _a1 *cloudfront.UpdateResponseHeadersPolicyInput, _a2 ...request.Option) (*cloudfront.UpdateResponseHeadersPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateStreamingDistribution provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateStreamingDistribution(_a0 *cloudfront.UpdateStreamingDistributionInput) (*cloudfront.UpdateStreamingDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateStreamingDistributionRequest provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) UpdateStreamingDistributionRequest(_a0 *cloudfront.UpdateStreamingDistributionInput) (*request.Request, *cloudfront.UpdateStreamingDistributionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateStreamingDistributionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) UpdateStreamingDistributionWithContext(_a0 context.Context, _a1 *cloudfront.UpdateStreamingDistributionInput, _a2 ...request.Option) (*cloudfront.UpdateStreamingDistributionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WaitUntilDistributionDeployed provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) WaitUntilDistributionDeployed(_a0 *cloudfront.GetDistributionInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilDistributionDeployedWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) WaitUntilDistributionDeployedWithContext(_a0 context.Context, _a1 *cloudfront.GetDistributionInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilInvalidationCompleted provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) WaitUntilInvalidationCompleted(_a0 *cloudfront.GetInvalidationInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilInvalidationCompletedWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) WaitUntilInvalidationCompletedWithContext(_a0 context.Context, _a1 *cloudfront.GetInvalidationInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilStreamingDistributionDeployed provides a mock function with given fields: _a0
func (_m *MockFakeCloudFront) WaitUntilStreamingDistributionDeployed(_a0 *cloudfront.GetStreamingDistributionInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilStreamingDistributionDeployedWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeCloudFront) WaitUntilStreamingDistributionDeployedWithContext(_a0 context.Context, _a1 *cloudfront.GetStreamingDistributionInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

type mockConstructorTestingTNewMockFakeCloudFront interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFakeCloudFront creates a new instance of MockFakeCloudFront. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFakeCloudFront(t mockConstructorTestingTNewMockFakeCloudFront) *MockFakeCloudFront {
	_ = "STUB: not implemented"
	return nil
}
