// Code generated by mockery v2.28.1. DO NOT EDIT.

package aws

import (
	context "context"

	request "github.com/aws/aws-sdk-go/aws/request"
	mock "github.com/stretchr/testify/mock"

	s3 "github.com/aws/aws-sdk-go/service/s3"
)

// MockFakeS3 is an autogenerated mock type for the FakeS3 type
type MockFakeS3 struct {
	mock.Mock
}

// AbortMultipartUpload provides a mock function with given fields: _a0
func (_m *MockFakeS3) AbortMultipartUpload(_a0 *s3.AbortMultipartUploadInput) (*s3.AbortMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AbortMultipartUploadRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) AbortMultipartUploadRequest(_a0 *s3.AbortMultipartUploadInput) (*request.Request, *s3.AbortMultipartUploadOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AbortMultipartUploadWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) AbortMultipartUploadWithContext(_a0 context.Context, _a1 *s3.AbortMultipartUploadInput, _a2 ...request.Option) (*s3.AbortMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteMultipartUpload provides a mock function with given fields: _a0
func (_m *MockFakeS3) CompleteMultipartUpload(_a0 *s3.CompleteMultipartUploadInput) (*s3.CompleteMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteMultipartUploadRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) CompleteMultipartUploadRequest(_a0 *s3.CompleteMultipartUploadInput) (*request.Request, *s3.CompleteMultipartUploadOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteMultipartUploadWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) CompleteMultipartUploadWithContext(_a0 context.Context, _a1 *s3.CompleteMultipartUploadInput, _a2 ...request.Option) (*s3.CompleteMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CopyObject provides a mock function with given fields: _a0
func (_m *MockFakeS3) CopyObject(_a0 *s3.CopyObjectInput) (*s3.CopyObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CopyObjectRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) CopyObjectRequest(_a0 *s3.CopyObjectInput) (*request.Request, *s3.CopyObjectOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CopyObjectWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) CopyObjectWithContext(_a0 context.Context, _a1 *s3.CopyObjectInput, _a2 ...request.Option) (*s3.CopyObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateBucket provides a mock function with given fields: _a0
func (_m *MockFakeS3) CreateBucket(_a0 *s3.CreateBucketInput) (*s3.CreateBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateBucketRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) CreateBucketRequest(_a0 *s3.CreateBucketInput) (*request.Request, *s3.CreateBucketOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateBucketWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) CreateBucketWithContext(_a0 context.Context, _a1 *s3.CreateBucketInput, _a2 ...request.Option) (*s3.CreateBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMultipartUpload provides a mock function with given fields: _a0
func (_m *MockFakeS3) CreateMultipartUpload(_a0 *s3.CreateMultipartUploadInput) (*s3.CreateMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMultipartUploadRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) CreateMultipartUploadRequest(_a0 *s3.CreateMultipartUploadInput) (*request.Request, *s3.CreateMultipartUploadOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMultipartUploadWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) CreateMultipartUploadWithContext(_a0 context.Context, _a1 *s3.CreateMultipartUploadInput, _a2 ...request.Option) (*s3.CreateMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucket provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucket(_a0 *s3.DeleteBucketInput) (*s3.DeleteBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketAnalyticsConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketAnalyticsConfiguration(_a0 *s3.DeleteBucketAnalyticsConfigurationInput) (*s3.DeleteBucketAnalyticsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketAnalyticsConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketAnalyticsConfigurationRequest(_a0 *s3.DeleteBucketAnalyticsConfigurationInput) (*request.Request, *s3.DeleteBucketAnalyticsConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketAnalyticsConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketAnalyticsConfigurationWithContext(_a0 context.Context, _a1 *s3.DeleteBucketAnalyticsConfigurationInput, _a2 ...request.Option) (*s3.DeleteBucketAnalyticsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketCors provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketCors(_a0 *s3.DeleteBucketCorsInput) (*s3.DeleteBucketCorsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketCorsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketCorsRequest(_a0 *s3.DeleteBucketCorsInput) (*request.Request, *s3.DeleteBucketCorsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketCorsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketCorsWithContext(_a0 context.Context, _a1 *s3.DeleteBucketCorsInput, _a2 ...request.Option) (*s3.DeleteBucketCorsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketEncryption provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketEncryption(_a0 *s3.DeleteBucketEncryptionInput) (*s3.DeleteBucketEncryptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketEncryptionRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketEncryptionRequest(_a0 *s3.DeleteBucketEncryptionInput) (*request.Request, *s3.DeleteBucketEncryptionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketEncryptionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketEncryptionWithContext(_a0 context.Context, _a1 *s3.DeleteBucketEncryptionInput, _a2 ...request.Option) (*s3.DeleteBucketEncryptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketIntelligentTieringConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketIntelligentTieringConfiguration(_a0 *s3.DeleteBucketIntelligentTieringConfigurationInput) (*s3.DeleteBucketIntelligentTieringConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketIntelligentTieringConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketIntelligentTieringConfigurationRequest(_a0 *s3.DeleteBucketIntelligentTieringConfigurationInput) (*request.Request, *s3.DeleteBucketIntelligentTieringConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketIntelligentTieringConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketIntelligentTieringConfigurationWithContext(_a0 context.Context, _a1 *s3.DeleteBucketIntelligentTieringConfigurationInput, _a2 ...request.Option) (*s3.DeleteBucketIntelligentTieringConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketInventoryConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketInventoryConfiguration(_a0 *s3.DeleteBucketInventoryConfigurationInput) (*s3.DeleteBucketInventoryConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketInventoryConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketInventoryConfigurationRequest(_a0 *s3.DeleteBucketInventoryConfigurationInput) (*request.Request, *s3.DeleteBucketInventoryConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketInventoryConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketInventoryConfigurationWithContext(_a0 context.Context, _a1 *s3.DeleteBucketInventoryConfigurationInput, _a2 ...request.Option) (*s3.DeleteBucketInventoryConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketLifecycle provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketLifecycle(_a0 *s3.DeleteBucketLifecycleInput) (*s3.DeleteBucketLifecycleOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketLifecycleRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketLifecycleRequest(_a0 *s3.DeleteBucketLifecycleInput) (*request.Request, *s3.DeleteBucketLifecycleOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketLifecycleWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketLifecycleWithContext(_a0 context.Context, _a1 *s3.DeleteBucketLifecycleInput, _a2 ...request.Option) (*s3.DeleteBucketLifecycleOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketMetricsConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketMetricsConfiguration(_a0 *s3.DeleteBucketMetricsConfigurationInput) (*s3.DeleteBucketMetricsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketMetricsConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketMetricsConfigurationRequest(_a0 *s3.DeleteBucketMetricsConfigurationInput) (*request.Request, *s3.DeleteBucketMetricsConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketMetricsConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketMetricsConfigurationWithContext(_a0 context.Context, _a1 *s3.DeleteBucketMetricsConfigurationInput, _a2 ...request.Option) (*s3.DeleteBucketMetricsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketOwnershipControls provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketOwnershipControls(_a0 *s3.DeleteBucketOwnershipControlsInput) (*s3.DeleteBucketOwnershipControlsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketOwnershipControlsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketOwnershipControlsRequest(_a0 *s3.DeleteBucketOwnershipControlsInput) (*request.Request, *s3.DeleteBucketOwnershipControlsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketOwnershipControlsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketOwnershipControlsWithContext(_a0 context.Context, _a1 *s3.DeleteBucketOwnershipControlsInput, _a2 ...request.Option) (*s3.DeleteBucketOwnershipControlsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketPolicy(_a0 *s3.DeleteBucketPolicyInput) (*s3.DeleteBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketPolicyRequest(_a0 *s3.DeleteBucketPolicyInput) (*request.Request, *s3.DeleteBucketPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketPolicyWithContext(_a0 context.Context, _a1 *s3.DeleteBucketPolicyInput, _a2 ...request.Option) (*s3.DeleteBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketReplication provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketReplication(_a0 *s3.DeleteBucketReplicationInput) (*s3.DeleteBucketReplicationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketReplicationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketReplicationRequest(_a0 *s3.DeleteBucketReplicationInput) (*request.Request, *s3.DeleteBucketReplicationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketReplicationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketReplicationWithContext(_a0 context.Context, _a1 *s3.DeleteBucketReplicationInput, _a2 ...request.Option) (*s3.DeleteBucketReplicationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketRequest(_a0 *s3.DeleteBucketInput) (*request.Request, *s3.DeleteBucketOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketTagging(_a0 *s3.DeleteBucketTaggingInput) (*s3.DeleteBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketTaggingRequest(_a0 *s3.DeleteBucketTaggingInput) (*request.Request, *s3.DeleteBucketTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketTaggingWithContext(_a0 context.Context, _a1 *s3.DeleteBucketTaggingInput, _a2 ...request.Option) (*s3.DeleteBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketWebsite provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketWebsite(_a0 *s3.DeleteBucketWebsiteInput) (*s3.DeleteBucketWebsiteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketWebsiteRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteBucketWebsiteRequest(_a0 *s3.DeleteBucketWebsiteInput) (*request.Request, *s3.DeleteBucketWebsiteOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketWebsiteWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketWebsiteWithContext(_a0 context.Context, _a1 *s3.DeleteBucketWebsiteInput, _a2 ...request.Option) (*s3.DeleteBucketWebsiteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteBucketWithContext(_a0 context.Context, _a1 *s3.DeleteBucketInput, _a2 ...request.Option) (*s3.DeleteBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObject provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteObject(_a0 *s3.DeleteObjectInput) (*s3.DeleteObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteObjectRequest(_a0 *s3.DeleteObjectInput) (*request.Request, *s3.DeleteObjectOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteObjectTagging(_a0 *s3.DeleteObjectTaggingInput) (*s3.DeleteObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteObjectTaggingRequest(_a0 *s3.DeleteObjectTaggingInput) (*request.Request, *s3.DeleteObjectTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteObjectTaggingWithContext(_a0 context.Context, _a1 *s3.DeleteObjectTaggingInput, _a2 ...request.Option) (*s3.DeleteObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteObjectWithContext(_a0 context.Context, _a1 *s3.DeleteObjectInput, _a2 ...request.Option) (*s3.DeleteObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjects provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteObjects(_a0 *s3.DeleteObjectsInput) (*s3.DeleteObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeleteObjectsRequest(_a0 *s3.DeleteObjectsInput) (*request.Request, *s3.DeleteObjectsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeleteObjectsWithContext(_a0 context.Context, _a1 *s3.DeleteObjectsInput, _a2 ...request.Option) (*s3.DeleteObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePublicAccessBlock provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeletePublicAccessBlock(_a0 *s3.DeletePublicAccessBlockInput) (*s3.DeletePublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePublicAccessBlockRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) DeletePublicAccessBlockRequest(_a0 *s3.DeletePublicAccessBlockInput) (*request.Request, *s3.DeletePublicAccessBlockOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePublicAccessBlockWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) DeletePublicAccessBlockWithContext(_a0 context.Context, _a1 *s3.DeletePublicAccessBlockInput, _a2 ...request.Option) (*s3.DeletePublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketAccelerateConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketAccelerateConfiguration(_a0 *s3.GetBucketAccelerateConfigurationInput) (*s3.GetBucketAccelerateConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketAccelerateConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketAccelerateConfigurationRequest(_a0 *s3.GetBucketAccelerateConfigurationInput) (*request.Request, *s3.GetBucketAccelerateConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketAccelerateConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketAccelerateConfigurationWithContext(_a0 context.Context, _a1 *s3.GetBucketAccelerateConfigurationInput, _a2 ...request.Option) (*s3.GetBucketAccelerateConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketAcl provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketAcl(_a0 *s3.GetBucketAclInput) (*s3.GetBucketAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketAclRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketAclRequest(_a0 *s3.GetBucketAclInput) (*request.Request, *s3.GetBucketAclOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketAclWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketAclWithContext(_a0 context.Context, _a1 *s3.GetBucketAclInput, _a2 ...request.Option) (*s3.GetBucketAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketAnalyticsConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketAnalyticsConfiguration(_a0 *s3.GetBucketAnalyticsConfigurationInput) (*s3.GetBucketAnalyticsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketAnalyticsConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketAnalyticsConfigurationRequest(_a0 *s3.GetBucketAnalyticsConfigurationInput) (*request.Request, *s3.GetBucketAnalyticsConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketAnalyticsConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketAnalyticsConfigurationWithContext(_a0 context.Context, _a1 *s3.GetBucketAnalyticsConfigurationInput, _a2 ...request.Option) (*s3.GetBucketAnalyticsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketCors provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketCors(_a0 *s3.GetBucketCorsInput) (*s3.GetBucketCorsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketCorsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketCorsRequest(_a0 *s3.GetBucketCorsInput) (*request.Request, *s3.GetBucketCorsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketCorsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketCorsWithContext(_a0 context.Context, _a1 *s3.GetBucketCorsInput, _a2 ...request.Option) (*s3.GetBucketCorsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketEncryption provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketEncryption(_a0 *s3.GetBucketEncryptionInput) (*s3.GetBucketEncryptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketEncryptionRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketEncryptionRequest(_a0 *s3.GetBucketEncryptionInput) (*request.Request, *s3.GetBucketEncryptionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketEncryptionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketEncryptionWithContext(_a0 context.Context, _a1 *s3.GetBucketEncryptionInput, _a2 ...request.Option) (*s3.GetBucketEncryptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketIntelligentTieringConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketIntelligentTieringConfiguration(_a0 *s3.GetBucketIntelligentTieringConfigurationInput) (*s3.GetBucketIntelligentTieringConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketIntelligentTieringConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketIntelligentTieringConfigurationRequest(_a0 *s3.GetBucketIntelligentTieringConfigurationInput) (*request.Request, *s3.GetBucketIntelligentTieringConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketIntelligentTieringConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketIntelligentTieringConfigurationWithContext(_a0 context.Context, _a1 *s3.GetBucketIntelligentTieringConfigurationInput, _a2 ...request.Option) (*s3.GetBucketIntelligentTieringConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketInventoryConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketInventoryConfiguration(_a0 *s3.GetBucketInventoryConfigurationInput) (*s3.GetBucketInventoryConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketInventoryConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketInventoryConfigurationRequest(_a0 *s3.GetBucketInventoryConfigurationInput) (*request.Request, *s3.GetBucketInventoryConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketInventoryConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketInventoryConfigurationWithContext(_a0 context.Context, _a1 *s3.GetBucketInventoryConfigurationInput, _a2 ...request.Option) (*s3.GetBucketInventoryConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLifecycle provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketLifecycle(_a0 *s3.GetBucketLifecycleInput) (*s3.GetBucketLifecycleOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLifecycleConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketLifecycleConfiguration(_a0 *s3.GetBucketLifecycleConfigurationInput) (*s3.GetBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLifecycleConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketLifecycleConfigurationRequest(_a0 *s3.GetBucketLifecycleConfigurationInput) (*request.Request, *s3.GetBucketLifecycleConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLifecycleConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketLifecycleConfigurationWithContext(_a0 context.Context, _a1 *s3.GetBucketLifecycleConfigurationInput, _a2 ...request.Option) (*s3.GetBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLifecycleRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketLifecycleRequest(_a0 *s3.GetBucketLifecycleInput) (*request.Request, *s3.GetBucketLifecycleOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLifecycleWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketLifecycleWithContext(_a0 context.Context, _a1 *s3.GetBucketLifecycleInput, _a2 ...request.Option) (*s3.GetBucketLifecycleOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLocation provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketLocation(_a0 *s3.GetBucketLocationInput) (*s3.GetBucketLocationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLocationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketLocationRequest(_a0 *s3.GetBucketLocationInput) (*request.Request, *s3.GetBucketLocationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLocationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketLocationWithContext(_a0 context.Context, _a1 *s3.GetBucketLocationInput, _a2 ...request.Option) (*s3.GetBucketLocationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLogging provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketLogging(_a0 *s3.GetBucketLoggingInput) (*s3.GetBucketLoggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLoggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketLoggingRequest(_a0 *s3.GetBucketLoggingInput) (*request.Request, *s3.GetBucketLoggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLoggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketLoggingWithContext(_a0 context.Context, _a1 *s3.GetBucketLoggingInput, _a2 ...request.Option) (*s3.GetBucketLoggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketMetricsConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketMetricsConfiguration(_a0 *s3.GetBucketMetricsConfigurationInput) (*s3.GetBucketMetricsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketMetricsConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketMetricsConfigurationRequest(_a0 *s3.GetBucketMetricsConfigurationInput) (*request.Request, *s3.GetBucketMetricsConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketMetricsConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketMetricsConfigurationWithContext(_a0 context.Context, _a1 *s3.GetBucketMetricsConfigurationInput, _a2 ...request.Option) (*s3.GetBucketMetricsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketNotification provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketNotification(_a0 *s3.GetBucketNotificationConfigurationRequest) (*s3.NotificationConfigurationDeprecated, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketNotificationConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketNotificationConfiguration(_a0 *s3.GetBucketNotificationConfigurationRequest) (*s3.NotificationConfiguration, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketNotificationConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketNotificationConfigurationRequest(_a0 *s3.GetBucketNotificationConfigurationRequest) (*request.Request, *s3.NotificationConfiguration) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketNotificationConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketNotificationConfigurationWithContext(_a0 context.Context, _a1 *s3.GetBucketNotificationConfigurationRequest, _a2 ...request.Option) (*s3.NotificationConfiguration, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketNotificationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketNotificationRequest(_a0 *s3.GetBucketNotificationConfigurationRequest) (*request.Request, *s3.NotificationConfigurationDeprecated) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketNotificationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketNotificationWithContext(_a0 context.Context, _a1 *s3.GetBucketNotificationConfigurationRequest, _a2 ...request.Option) (*s3.NotificationConfigurationDeprecated, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketOwnershipControls provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketOwnershipControls(_a0 *s3.GetBucketOwnershipControlsInput) (*s3.GetBucketOwnershipControlsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketOwnershipControlsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketOwnershipControlsRequest(_a0 *s3.GetBucketOwnershipControlsInput) (*request.Request, *s3.GetBucketOwnershipControlsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketOwnershipControlsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketOwnershipControlsWithContext(_a0 context.Context, _a1 *s3.GetBucketOwnershipControlsInput, _a2 ...request.Option) (*s3.GetBucketOwnershipControlsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketPolicy(_a0 *s3.GetBucketPolicyInput) (*s3.GetBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketPolicyRequest(_a0 *s3.GetBucketPolicyInput) (*request.Request, *s3.GetBucketPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicyStatus provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketPolicyStatus(_a0 *s3.GetBucketPolicyStatusInput) (*s3.GetBucketPolicyStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicyStatusRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketPolicyStatusRequest(_a0 *s3.GetBucketPolicyStatusInput) (*request.Request, *s3.GetBucketPolicyStatusOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicyStatusWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketPolicyStatusWithContext(_a0 context.Context, _a1 *s3.GetBucketPolicyStatusInput, _a2 ...request.Option) (*s3.GetBucketPolicyStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketPolicyWithContext(_a0 context.Context, _a1 *s3.GetBucketPolicyInput, _a2 ...request.Option) (*s3.GetBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketReplication provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketReplication(_a0 *s3.GetBucketReplicationInput) (*s3.GetBucketReplicationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketReplicationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketReplicationRequest(_a0 *s3.GetBucketReplicationInput) (*request.Request, *s3.GetBucketReplicationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketReplicationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketReplicationWithContext(_a0 context.Context, _a1 *s3.GetBucketReplicationInput, _a2 ...request.Option) (*s3.GetBucketReplicationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketRequestPayment provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketRequestPayment(_a0 *s3.GetBucketRequestPaymentInput) (*s3.GetBucketRequestPaymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketRequestPaymentRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketRequestPaymentRequest(_a0 *s3.GetBucketRequestPaymentInput) (*request.Request, *s3.GetBucketRequestPaymentOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketRequestPaymentWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketRequestPaymentWithContext(_a0 context.Context, _a1 *s3.GetBucketRequestPaymentInput, _a2 ...request.Option) (*s3.GetBucketRequestPaymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketTagging(_a0 *s3.GetBucketTaggingInput) (*s3.GetBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketTaggingRequest(_a0 *s3.GetBucketTaggingInput) (*request.Request, *s3.GetBucketTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketTaggingWithContext(_a0 context.Context, _a1 *s3.GetBucketTaggingInput, _a2 ...request.Option) (*s3.GetBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketVersioning provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketVersioning(_a0 *s3.GetBucketVersioningInput) (*s3.GetBucketVersioningOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketVersioningRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketVersioningRequest(_a0 *s3.GetBucketVersioningInput) (*request.Request, *s3.GetBucketVersioningOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketVersioningWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketVersioningWithContext(_a0 context.Context, _a1 *s3.GetBucketVersioningInput, _a2 ...request.Option) (*s3.GetBucketVersioningOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketWebsite provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketWebsite(_a0 *s3.GetBucketWebsiteInput) (*s3.GetBucketWebsiteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketWebsiteRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetBucketWebsiteRequest(_a0 *s3.GetBucketWebsiteInput) (*request.Request, *s3.GetBucketWebsiteOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketWebsiteWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetBucketWebsiteWithContext(_a0 context.Context, _a1 *s3.GetBucketWebsiteInput, _a2 ...request.Option) (*s3.GetBucketWebsiteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObject provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObject(_a0 *s3.GetObjectInput) (*s3.GetObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectAcl provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectAcl(_a0 *s3.GetObjectAclInput) (*s3.GetObjectAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectAclRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectAclRequest(_a0 *s3.GetObjectAclInput) (*request.Request, *s3.GetObjectAclOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectAclWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetObjectAclWithContext(_a0 context.Context, _a1 *s3.GetObjectAclInput, _a2 ...request.Option) (*s3.GetObjectAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectAttributes provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectAttributes(_a0 *s3.GetObjectAttributesInput) (*s3.GetObjectAttributesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectAttributesRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectAttributesRequest(_a0 *s3.GetObjectAttributesInput) (*request.Request, *s3.GetObjectAttributesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectAttributesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetObjectAttributesWithContext(_a0 context.Context, _a1 *s3.GetObjectAttributesInput, _a2 ...request.Option) (*s3.GetObjectAttributesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectLegalHold provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectLegalHold(_a0 *s3.GetObjectLegalHoldInput) (*s3.GetObjectLegalHoldOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectLegalHoldRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectLegalHoldRequest(_a0 *s3.GetObjectLegalHoldInput) (*request.Request, *s3.GetObjectLegalHoldOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectLegalHoldWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetObjectLegalHoldWithContext(_a0 context.Context, _a1 *s3.GetObjectLegalHoldInput, _a2 ...request.Option) (*s3.GetObjectLegalHoldOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectLockConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectLockConfiguration(_a0 *s3.GetObjectLockConfigurationInput) (*s3.GetObjectLockConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectLockConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectLockConfigurationRequest(_a0 *s3.GetObjectLockConfigurationInput) (*request.Request, *s3.GetObjectLockConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectLockConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetObjectLockConfigurationWithContext(_a0 context.Context, _a1 *s3.GetObjectLockConfigurationInput, _a2 ...request.Option) (*s3.GetObjectLockConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectRequest(_a0 *s3.GetObjectInput) (*request.Request, *s3.GetObjectOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectRetention provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectRetention(_a0 *s3.GetObjectRetentionInput) (*s3.GetObjectRetentionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectRetentionRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectRetentionRequest(_a0 *s3.GetObjectRetentionInput) (*request.Request, *s3.GetObjectRetentionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectRetentionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetObjectRetentionWithContext(_a0 context.Context, _a1 *s3.GetObjectRetentionInput, _a2 ...request.Option) (*s3.GetObjectRetentionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectTagging(_a0 *s3.GetObjectTaggingInput) (*s3.GetObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectTaggingRequest(_a0 *s3.GetObjectTaggingInput) (*request.Request, *s3.GetObjectTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetObjectTaggingWithContext(_a0 context.Context, _a1 *s3.GetObjectTaggingInput, _a2 ...request.Option) (*s3.GetObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectTorrent provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectTorrent(_a0 *s3.GetObjectTorrentInput) (*s3.GetObjectTorrentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectTorrentRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetObjectTorrentRequest(_a0 *s3.GetObjectTorrentInput) (*request.Request, *s3.GetObjectTorrentOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectTorrentWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetObjectTorrentWithContext(_a0 context.Context, _a1 *s3.GetObjectTorrentInput, _a2 ...request.Option) (*s3.GetObjectTorrentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetObjectWithContext(_a0 context.Context, _a1 *s3.GetObjectInput, _a2 ...request.Option) (*s3.GetObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicAccessBlock provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetPublicAccessBlock(_a0 *s3.GetPublicAccessBlockInput) (*s3.GetPublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicAccessBlockRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) GetPublicAccessBlockRequest(_a0 *s3.GetPublicAccessBlockInput) (*request.Request, *s3.GetPublicAccessBlockOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicAccessBlockWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) GetPublicAccessBlockWithContext(_a0 context.Context, _a1 *s3.GetPublicAccessBlockInput, _a2 ...request.Option) (*s3.GetPublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeadBucket provides a mock function with given fields: _a0
func (_m *MockFakeS3) HeadBucket(_a0 *s3.HeadBucketInput) (*s3.HeadBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeadBucketRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) HeadBucketRequest(_a0 *s3.HeadBucketInput) (*request.Request, *s3.HeadBucketOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeadBucketWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) HeadBucketWithContext(_a0 context.Context, _a1 *s3.HeadBucketInput, _a2 ...request.Option) (*s3.HeadBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeadObject provides a mock function with given fields: _a0
func (_m *MockFakeS3) HeadObject(_a0 *s3.HeadObjectInput) (*s3.HeadObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeadObjectRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) HeadObjectRequest(_a0 *s3.HeadObjectInput) (*request.Request, *s3.HeadObjectOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeadObjectWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) HeadObjectWithContext(_a0 context.Context, _a1 *s3.HeadObjectInput, _a2 ...request.Option) (*s3.HeadObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketAnalyticsConfigurations provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBucketAnalyticsConfigurations(_a0 *s3.ListBucketAnalyticsConfigurationsInput) (*s3.ListBucketAnalyticsConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketAnalyticsConfigurationsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBucketAnalyticsConfigurationsRequest(_a0 *s3.ListBucketAnalyticsConfigurationsInput) (*request.Request, *s3.ListBucketAnalyticsConfigurationsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketAnalyticsConfigurationsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListBucketAnalyticsConfigurationsWithContext(_a0 context.Context, _a1 *s3.ListBucketAnalyticsConfigurationsInput, _a2 ...request.Option) (*s3.ListBucketAnalyticsConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketIntelligentTieringConfigurations provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBucketIntelligentTieringConfigurations(_a0 *s3.ListBucketIntelligentTieringConfigurationsInput) (*s3.ListBucketIntelligentTieringConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketIntelligentTieringConfigurationsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBucketIntelligentTieringConfigurationsRequest(_a0 *s3.ListBucketIntelligentTieringConfigurationsInput) (*request.Request, *s3.ListBucketIntelligentTieringConfigurationsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketIntelligentTieringConfigurationsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListBucketIntelligentTieringConfigurationsWithContext(_a0 context.Context, _a1 *s3.ListBucketIntelligentTieringConfigurationsInput, _a2 ...request.Option) (*s3.ListBucketIntelligentTieringConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketInventoryConfigurations provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBucketInventoryConfigurations(_a0 *s3.ListBucketInventoryConfigurationsInput) (*s3.ListBucketInventoryConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketInventoryConfigurationsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBucketInventoryConfigurationsRequest(_a0 *s3.ListBucketInventoryConfigurationsInput) (*request.Request, *s3.ListBucketInventoryConfigurationsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketInventoryConfigurationsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListBucketInventoryConfigurationsWithContext(_a0 context.Context, _a1 *s3.ListBucketInventoryConfigurationsInput, _a2 ...request.Option) (*s3.ListBucketInventoryConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketMetricsConfigurations provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBucketMetricsConfigurations(_a0 *s3.ListBucketMetricsConfigurationsInput) (*s3.ListBucketMetricsConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketMetricsConfigurationsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBucketMetricsConfigurationsRequest(_a0 *s3.ListBucketMetricsConfigurationsInput) (*request.Request, *s3.ListBucketMetricsConfigurationsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketMetricsConfigurationsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListBucketMetricsConfigurationsWithContext(_a0 context.Context, _a1 *s3.ListBucketMetricsConfigurationsInput, _a2 ...request.Option) (*s3.ListBucketMetricsConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBuckets provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBuckets(_a0 *s3.ListBucketsInput) (*s3.ListBucketsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListBucketsRequest(_a0 *s3.ListBucketsInput) (*request.Request, *s3.ListBucketsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListBucketsWithContext(_a0 context.Context, _a1 *s3.ListBucketsInput, _a2 ...request.Option) (*s3.ListBucketsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMultipartUploads provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListMultipartUploads(_a0 *s3.ListMultipartUploadsInput) (*s3.ListMultipartUploadsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMultipartUploadsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3) ListMultipartUploadsPages(_a0 *s3.ListMultipartUploadsInput, _a1 func(*s3.ListMultipartUploadsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListMultipartUploadsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3) ListMultipartUploadsPagesWithContext(_a0 context.Context, _a1 *s3.ListMultipartUploadsInput, _a2 func(*s3.ListMultipartUploadsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListMultipartUploadsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListMultipartUploadsRequest(_a0 *s3.ListMultipartUploadsInput) (*request.Request, *s3.ListMultipartUploadsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMultipartUploadsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListMultipartUploadsWithContext(_a0 context.Context, _a1 *s3.ListMultipartUploadsInput, _a2 ...request.Option) (*s3.ListMultipartUploadsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectVersions provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListObjectVersions(_a0 *s3.ListObjectVersionsInput) (*s3.ListObjectVersionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectVersionsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3) ListObjectVersionsPages(_a0 *s3.ListObjectVersionsInput, _a1 func(*s3.ListObjectVersionsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectVersionsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3) ListObjectVersionsPagesWithContext(_a0 context.Context, _a1 *s3.ListObjectVersionsInput, _a2 func(*s3.ListObjectVersionsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectVersionsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListObjectVersionsRequest(_a0 *s3.ListObjectVersionsInput) (*request.Request, *s3.ListObjectVersionsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectVersionsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListObjectVersionsWithContext(_a0 context.Context, _a1 *s3.ListObjectVersionsInput, _a2 ...request.Option) (*s3.ListObjectVersionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjects provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListObjects(_a0 *s3.ListObjectsInput) (*s3.ListObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3) ListObjectsPages(_a0 *s3.ListObjectsInput, _a1 func(*s3.ListObjectsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3) ListObjectsPagesWithContext(_a0 context.Context, _a1 *s3.ListObjectsInput, _a2 func(*s3.ListObjectsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListObjectsRequest(_a0 *s3.ListObjectsInput) (*request.Request, *s3.ListObjectsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectsV2 provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListObjectsV2(_a0 *s3.ListObjectsV2Input) (*s3.ListObjectsV2Output, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectsV2Pages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3) ListObjectsV2Pages(_a0 *s3.ListObjectsV2Input, _a1 func(*s3.ListObjectsV2Output, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectsV2PagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3) ListObjectsV2PagesWithContext(_a0 context.Context, _a1 *s3.ListObjectsV2Input, _a2 func(*s3.ListObjectsV2Output, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectsV2Request provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListObjectsV2Request(_a0 *s3.ListObjectsV2Input) (*request.Request, *s3.ListObjectsV2Output) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectsV2WithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListObjectsV2WithContext(_a0 context.Context, _a1 *s3.ListObjectsV2Input, _a2 ...request.Option) (*s3.ListObjectsV2Output, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListObjectsWithContext(_a0 context.Context, _a1 *s3.ListObjectsInput, _a2 ...request.Option) (*s3.ListObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListParts provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListParts(_a0 *s3.ListPartsInput) (*s3.ListPartsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPartsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3) ListPartsPages(_a0 *s3.ListPartsInput, _a1 func(*s3.ListPartsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListPartsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3) ListPartsPagesWithContext(_a0 context.Context, _a1 *s3.ListPartsInput, _a2 func(*s3.ListPartsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListPartsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) ListPartsRequest(_a0 *s3.ListPartsInput) (*request.Request, *s3.ListPartsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPartsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) ListPartsWithContext(_a0 context.Context, _a1 *s3.ListPartsInput, _a2 ...request.Option) (*s3.ListPartsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketAccelerateConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketAccelerateConfiguration(_a0 *s3.PutBucketAccelerateConfigurationInput) (*s3.PutBucketAccelerateConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketAccelerateConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketAccelerateConfigurationRequest(_a0 *s3.PutBucketAccelerateConfigurationInput) (*request.Request, *s3.PutBucketAccelerateConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketAccelerateConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketAccelerateConfigurationWithContext(_a0 context.Context, _a1 *s3.PutBucketAccelerateConfigurationInput, _a2 ...request.Option) (*s3.PutBucketAccelerateConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketAcl provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketAcl(_a0 *s3.PutBucketAclInput) (*s3.PutBucketAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketAclRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketAclRequest(_a0 *s3.PutBucketAclInput) (*request.Request, *s3.PutBucketAclOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketAclWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketAclWithContext(_a0 context.Context, _a1 *s3.PutBucketAclInput, _a2 ...request.Option) (*s3.PutBucketAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketAnalyticsConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketAnalyticsConfiguration(_a0 *s3.PutBucketAnalyticsConfigurationInput) (*s3.PutBucketAnalyticsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketAnalyticsConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketAnalyticsConfigurationRequest(_a0 *s3.PutBucketAnalyticsConfigurationInput) (*request.Request, *s3.PutBucketAnalyticsConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketAnalyticsConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketAnalyticsConfigurationWithContext(_a0 context.Context, _a1 *s3.PutBucketAnalyticsConfigurationInput, _a2 ...request.Option) (*s3.PutBucketAnalyticsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketCors provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketCors(_a0 *s3.PutBucketCorsInput) (*s3.PutBucketCorsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketCorsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketCorsRequest(_a0 *s3.PutBucketCorsInput) (*request.Request, *s3.PutBucketCorsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketCorsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketCorsWithContext(_a0 context.Context, _a1 *s3.PutBucketCorsInput, _a2 ...request.Option) (*s3.PutBucketCorsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketEncryption provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketEncryption(_a0 *s3.PutBucketEncryptionInput) (*s3.PutBucketEncryptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketEncryptionRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketEncryptionRequest(_a0 *s3.PutBucketEncryptionInput) (*request.Request, *s3.PutBucketEncryptionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketEncryptionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketEncryptionWithContext(_a0 context.Context, _a1 *s3.PutBucketEncryptionInput, _a2 ...request.Option) (*s3.PutBucketEncryptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketIntelligentTieringConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketIntelligentTieringConfiguration(_a0 *s3.PutBucketIntelligentTieringConfigurationInput) (*s3.PutBucketIntelligentTieringConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketIntelligentTieringConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketIntelligentTieringConfigurationRequest(_a0 *s3.PutBucketIntelligentTieringConfigurationInput) (*request.Request, *s3.PutBucketIntelligentTieringConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketIntelligentTieringConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketIntelligentTieringConfigurationWithContext(_a0 context.Context, _a1 *s3.PutBucketIntelligentTieringConfigurationInput, _a2 ...request.Option) (*s3.PutBucketIntelligentTieringConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketInventoryConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketInventoryConfiguration(_a0 *s3.PutBucketInventoryConfigurationInput) (*s3.PutBucketInventoryConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketInventoryConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketInventoryConfigurationRequest(_a0 *s3.PutBucketInventoryConfigurationInput) (*request.Request, *s3.PutBucketInventoryConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketInventoryConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketInventoryConfigurationWithContext(_a0 context.Context, _a1 *s3.PutBucketInventoryConfigurationInput, _a2 ...request.Option) (*s3.PutBucketInventoryConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLifecycle provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketLifecycle(_a0 *s3.PutBucketLifecycleInput) (*s3.PutBucketLifecycleOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLifecycleConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketLifecycleConfiguration(_a0 *s3.PutBucketLifecycleConfigurationInput) (*s3.PutBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLifecycleConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketLifecycleConfigurationRequest(_a0 *s3.PutBucketLifecycleConfigurationInput) (*request.Request, *s3.PutBucketLifecycleConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLifecycleConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketLifecycleConfigurationWithContext(_a0 context.Context, _a1 *s3.PutBucketLifecycleConfigurationInput, _a2 ...request.Option) (*s3.PutBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLifecycleRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketLifecycleRequest(_a0 *s3.PutBucketLifecycleInput) (*request.Request, *s3.PutBucketLifecycleOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLifecycleWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketLifecycleWithContext(_a0 context.Context, _a1 *s3.PutBucketLifecycleInput, _a2 ...request.Option) (*s3.PutBucketLifecycleOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLogging provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketLogging(_a0 *s3.PutBucketLoggingInput) (*s3.PutBucketLoggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLoggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketLoggingRequest(_a0 *s3.PutBucketLoggingInput) (*request.Request, *s3.PutBucketLoggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLoggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketLoggingWithContext(_a0 context.Context, _a1 *s3.PutBucketLoggingInput, _a2 ...request.Option) (*s3.PutBucketLoggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketMetricsConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketMetricsConfiguration(_a0 *s3.PutBucketMetricsConfigurationInput) (*s3.PutBucketMetricsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketMetricsConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketMetricsConfigurationRequest(_a0 *s3.PutBucketMetricsConfigurationInput) (*request.Request, *s3.PutBucketMetricsConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketMetricsConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketMetricsConfigurationWithContext(_a0 context.Context, _a1 *s3.PutBucketMetricsConfigurationInput, _a2 ...request.Option) (*s3.PutBucketMetricsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketNotification provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketNotification(_a0 *s3.PutBucketNotificationInput) (*s3.PutBucketNotificationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketNotificationConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketNotificationConfiguration(_a0 *s3.PutBucketNotificationConfigurationInput) (*s3.PutBucketNotificationConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketNotificationConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketNotificationConfigurationRequest(_a0 *s3.PutBucketNotificationConfigurationInput) (*request.Request, *s3.PutBucketNotificationConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketNotificationConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketNotificationConfigurationWithContext(_a0 context.Context, _a1 *s3.PutBucketNotificationConfigurationInput, _a2 ...request.Option) (*s3.PutBucketNotificationConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketNotificationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketNotificationRequest(_a0 *s3.PutBucketNotificationInput) (*request.Request, *s3.PutBucketNotificationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketNotificationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketNotificationWithContext(_a0 context.Context, _a1 *s3.PutBucketNotificationInput, _a2 ...request.Option) (*s3.PutBucketNotificationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketOwnershipControls provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketOwnershipControls(_a0 *s3.PutBucketOwnershipControlsInput) (*s3.PutBucketOwnershipControlsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketOwnershipControlsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketOwnershipControlsRequest(_a0 *s3.PutBucketOwnershipControlsInput) (*request.Request, *s3.PutBucketOwnershipControlsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketOwnershipControlsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketOwnershipControlsWithContext(_a0 context.Context, _a1 *s3.PutBucketOwnershipControlsInput, _a2 ...request.Option) (*s3.PutBucketOwnershipControlsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketPolicy(_a0 *s3.PutBucketPolicyInput) (*s3.PutBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketPolicyRequest(_a0 *s3.PutBucketPolicyInput) (*request.Request, *s3.PutBucketPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketPolicyWithContext(_a0 context.Context, _a1 *s3.PutBucketPolicyInput, _a2 ...request.Option) (*s3.PutBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketReplication provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketReplication(_a0 *s3.PutBucketReplicationInput) (*s3.PutBucketReplicationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketReplicationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketReplicationRequest(_a0 *s3.PutBucketReplicationInput) (*request.Request, *s3.PutBucketReplicationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketReplicationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketReplicationWithContext(_a0 context.Context, _a1 *s3.PutBucketReplicationInput, _a2 ...request.Option) (*s3.PutBucketReplicationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketRequestPayment provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketRequestPayment(_a0 *s3.PutBucketRequestPaymentInput) (*s3.PutBucketRequestPaymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketRequestPaymentRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketRequestPaymentRequest(_a0 *s3.PutBucketRequestPaymentInput) (*request.Request, *s3.PutBucketRequestPaymentOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketRequestPaymentWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketRequestPaymentWithContext(_a0 context.Context, _a1 *s3.PutBucketRequestPaymentInput, _a2 ...request.Option) (*s3.PutBucketRequestPaymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketTagging(_a0 *s3.PutBucketTaggingInput) (*s3.PutBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketTaggingRequest(_a0 *s3.PutBucketTaggingInput) (*request.Request, *s3.PutBucketTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketTaggingWithContext(_a0 context.Context, _a1 *s3.PutBucketTaggingInput, _a2 ...request.Option) (*s3.PutBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketVersioning provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketVersioning(_a0 *s3.PutBucketVersioningInput) (*s3.PutBucketVersioningOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketVersioningRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketVersioningRequest(_a0 *s3.PutBucketVersioningInput) (*request.Request, *s3.PutBucketVersioningOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketVersioningWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketVersioningWithContext(_a0 context.Context, _a1 *s3.PutBucketVersioningInput, _a2 ...request.Option) (*s3.PutBucketVersioningOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketWebsite provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketWebsite(_a0 *s3.PutBucketWebsiteInput) (*s3.PutBucketWebsiteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketWebsiteRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutBucketWebsiteRequest(_a0 *s3.PutBucketWebsiteInput) (*request.Request, *s3.PutBucketWebsiteOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketWebsiteWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutBucketWebsiteWithContext(_a0 context.Context, _a1 *s3.PutBucketWebsiteInput, _a2 ...request.Option) (*s3.PutBucketWebsiteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObject provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObject(_a0 *s3.PutObjectInput) (*s3.PutObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectAcl provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectAcl(_a0 *s3.PutObjectAclInput) (*s3.PutObjectAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectAclRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectAclRequest(_a0 *s3.PutObjectAclInput) (*request.Request, *s3.PutObjectAclOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectAclWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutObjectAclWithContext(_a0 context.Context, _a1 *s3.PutObjectAclInput, _a2 ...request.Option) (*s3.PutObjectAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectLegalHold provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectLegalHold(_a0 *s3.PutObjectLegalHoldInput) (*s3.PutObjectLegalHoldOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectLegalHoldRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectLegalHoldRequest(_a0 *s3.PutObjectLegalHoldInput) (*request.Request, *s3.PutObjectLegalHoldOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectLegalHoldWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutObjectLegalHoldWithContext(_a0 context.Context, _a1 *s3.PutObjectLegalHoldInput, _a2 ...request.Option) (*s3.PutObjectLegalHoldOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectLockConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectLockConfiguration(_a0 *s3.PutObjectLockConfigurationInput) (*s3.PutObjectLockConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectLockConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectLockConfigurationRequest(_a0 *s3.PutObjectLockConfigurationInput) (*request.Request, *s3.PutObjectLockConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectLockConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutObjectLockConfigurationWithContext(_a0 context.Context, _a1 *s3.PutObjectLockConfigurationInput, _a2 ...request.Option) (*s3.PutObjectLockConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectRequest(_a0 *s3.PutObjectInput) (*request.Request, *s3.PutObjectOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectRetention provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectRetention(_a0 *s3.PutObjectRetentionInput) (*s3.PutObjectRetentionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectRetentionRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectRetentionRequest(_a0 *s3.PutObjectRetentionInput) (*request.Request, *s3.PutObjectRetentionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectRetentionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutObjectRetentionWithContext(_a0 context.Context, _a1 *s3.PutObjectRetentionInput, _a2 ...request.Option) (*s3.PutObjectRetentionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectTagging(_a0 *s3.PutObjectTaggingInput) (*s3.PutObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutObjectTaggingRequest(_a0 *s3.PutObjectTaggingInput) (*request.Request, *s3.PutObjectTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutObjectTaggingWithContext(_a0 context.Context, _a1 *s3.PutObjectTaggingInput, _a2 ...request.Option) (*s3.PutObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutObjectWithContext(_a0 context.Context, _a1 *s3.PutObjectInput, _a2 ...request.Option) (*s3.PutObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutPublicAccessBlock provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutPublicAccessBlock(_a0 *s3.PutPublicAccessBlockInput) (*s3.PutPublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutPublicAccessBlockRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) PutPublicAccessBlockRequest(_a0 *s3.PutPublicAccessBlockInput) (*request.Request, *s3.PutPublicAccessBlockOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutPublicAccessBlockWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) PutPublicAccessBlockWithContext(_a0 context.Context, _a1 *s3.PutPublicAccessBlockInput, _a2 ...request.Option) (*s3.PutPublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RestoreObject provides a mock function with given fields: _a0
func (_m *MockFakeS3) RestoreObject(_a0 *s3.RestoreObjectInput) (*s3.RestoreObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RestoreObjectRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) RestoreObjectRequest(_a0 *s3.RestoreObjectInput) (*request.Request, *s3.RestoreObjectOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RestoreObjectWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) RestoreObjectWithContext(_a0 context.Context, _a1 *s3.RestoreObjectInput, _a2 ...request.Option) (*s3.RestoreObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SelectObjectContent provides a mock function with given fields: _a0
func (_m *MockFakeS3) SelectObjectContent(_a0 *s3.SelectObjectContentInput) (*s3.SelectObjectContentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SelectObjectContentRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) SelectObjectContentRequest(_a0 *s3.SelectObjectContentInput) (*request.Request, *s3.SelectObjectContentOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SelectObjectContentWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) SelectObjectContentWithContext(_a0 context.Context, _a1 *s3.SelectObjectContentInput, _a2 ...request.Option) (*s3.SelectObjectContentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPart provides a mock function with given fields: _a0
func (_m *MockFakeS3) UploadPart(_a0 *s3.UploadPartInput) (*s3.UploadPartOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPartCopy provides a mock function with given fields: _a0
func (_m *MockFakeS3) UploadPartCopy(_a0 *s3.UploadPartCopyInput) (*s3.UploadPartCopyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPartCopyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) UploadPartCopyRequest(_a0 *s3.UploadPartCopyInput) (*request.Request, *s3.UploadPartCopyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPartCopyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) UploadPartCopyWithContext(_a0 context.Context, _a1 *s3.UploadPartCopyInput, _a2 ...request.Option) (*s3.UploadPartCopyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPartRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) UploadPartRequest(_a0 *s3.UploadPartInput) (*request.Request, *s3.UploadPartOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPartWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) UploadPartWithContext(_a0 context.Context, _a1 *s3.UploadPartInput, _a2 ...request.Option) (*s3.UploadPartOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WaitUntilBucketExists provides a mock function with given fields: _a0
func (_m *MockFakeS3) WaitUntilBucketExists(_a0 *s3.HeadBucketInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilBucketExistsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) WaitUntilBucketExistsWithContext(_a0 context.Context, _a1 *s3.HeadBucketInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilBucketNotExists provides a mock function with given fields: _a0
func (_m *MockFakeS3) WaitUntilBucketNotExists(_a0 *s3.HeadBucketInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilBucketNotExistsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) WaitUntilBucketNotExistsWithContext(_a0 context.Context, _a1 *s3.HeadBucketInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilObjectExists provides a mock function with given fields: _a0
func (_m *MockFakeS3) WaitUntilObjectExists(_a0 *s3.HeadObjectInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilObjectExistsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) WaitUntilObjectExistsWithContext(_a0 context.Context, _a1 *s3.HeadObjectInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilObjectNotExists provides a mock function with given fields: _a0
func (_m *MockFakeS3) WaitUntilObjectNotExists(_a0 *s3.HeadObjectInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilObjectNotExistsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) WaitUntilObjectNotExistsWithContext(_a0 context.Context, _a1 *s3.HeadObjectInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

// WriteGetObjectResponse provides a mock function with given fields: _a0
func (_m *MockFakeS3) WriteGetObjectResponse(_a0 *s3.WriteGetObjectResponseInput) (*s3.WriteGetObjectResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WriteGetObjectResponseRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3) WriteGetObjectResponseRequest(_a0 *s3.WriteGetObjectResponseInput) (*request.Request, *s3.WriteGetObjectResponseOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WriteGetObjectResponseWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3) WriteGetObjectResponseWithContext(_a0 context.Context, _a1 *s3.WriteGetObjectResponseInput, _a2 ...request.Option) (*s3.WriteGetObjectResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockFakeS3 interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFakeS3 creates a new instance of MockFakeS3. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFakeS3(t mockConstructorTestingTNewMockFakeS3) *MockFakeS3 {
	_ = "STUB: not implemented"
	return nil
}
