// Code generated by mockery v2.28.1. DO NOT EDIT.

package aws

import (
	context "context"

	kms "github.com/aws/aws-sdk-go/service/kms"
	mock "github.com/stretchr/testify/mock"

	request "github.com/aws/aws-sdk-go/aws/request"
)

// MockFakeKMS is an autogenerated mock type for the FakeKMS type
type MockFakeKMS struct {
	mock.Mock
}

// CancelKeyDeletion provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CancelKeyDeletion(_a0 *kms.CancelKeyDeletionInput) (*kms.CancelKeyDeletionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CancelKeyDeletionRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CancelKeyDeletionRequest(_a0 *kms.CancelKeyDeletionInput) (*request.Request, *kms.CancelKeyDeletionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CancelKeyDeletionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) CancelKeyDeletionWithContext(_a0 context.Context, _a1 *kms.CancelKeyDeletionInput, _a2 ...request.Option) (*kms.CancelKeyDeletionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ConnectCustomKeyStore provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ConnectCustomKeyStore(_a0 *kms.ConnectCustomKeyStoreInput) (*kms.ConnectCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ConnectCustomKeyStoreRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ConnectCustomKeyStoreRequest(_a0 *kms.ConnectCustomKeyStoreInput) (*request.Request, *kms.ConnectCustomKeyStoreOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ConnectCustomKeyStoreWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ConnectCustomKeyStoreWithContext(_a0 context.Context, _a1 *kms.ConnectCustomKeyStoreInput, _a2 ...request.Option) (*kms.ConnectCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAlias provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CreateAlias(_a0 *kms.CreateAliasInput) (*kms.CreateAliasOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAliasRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CreateAliasRequest(_a0 *kms.CreateAliasInput) (*request.Request, *kms.CreateAliasOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAliasWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) CreateAliasWithContext(_a0 context.Context, _a1 *kms.CreateAliasInput, _a2 ...request.Option) (*kms.CreateAliasOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateCustomKeyStore provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CreateCustomKeyStore(_a0 *kms.CreateCustomKeyStoreInput) (*kms.CreateCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateCustomKeyStoreRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CreateCustomKeyStoreRequest(_a0 *kms.CreateCustomKeyStoreInput) (*request.Request, *kms.CreateCustomKeyStoreOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateCustomKeyStoreWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) CreateCustomKeyStoreWithContext(_a0 context.Context, _a1 *kms.CreateCustomKeyStoreInput, _a2 ...request.Option) (*kms.CreateCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateGrant provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CreateGrant(_a0 *kms.CreateGrantInput) (*kms.CreateGrantOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateGrantRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CreateGrantRequest(_a0 *kms.CreateGrantInput) (*request.Request, *kms.CreateGrantOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateGrantWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) CreateGrantWithContext(_a0 context.Context, _a1 *kms.CreateGrantInput, _a2 ...request.Option) (*kms.CreateGrantOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateKey provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CreateKey(_a0 *kms.CreateKeyInput) (*kms.CreateKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) CreateKeyRequest(_a0 *kms.CreateKeyInput) (*request.Request, *kms.CreateKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) CreateKeyWithContext(_a0 context.Context, _a1 *kms.CreateKeyInput, _a2 ...request.Option) (*kms.CreateKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Decrypt provides a mock function with given fields: _a0
func (_m *MockFakeKMS) Decrypt(_a0 *kms.DecryptInput) (*kms.DecryptOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DecryptRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DecryptRequest(_a0 *kms.DecryptInput) (*request.Request, *kms.DecryptOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DecryptWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) DecryptWithContext(_a0 context.Context, _a1 *kms.DecryptInput, _a2 ...request.Option) (*kms.DecryptOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAlias provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DeleteAlias(_a0 *kms.DeleteAliasInput) (*kms.DeleteAliasOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAliasRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DeleteAliasRequest(_a0 *kms.DeleteAliasInput) (*request.Request, *kms.DeleteAliasOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAliasWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) DeleteAliasWithContext(_a0 context.Context, _a1 *kms.DeleteAliasInput, _a2 ...request.Option) (*kms.DeleteAliasOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCustomKeyStore provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DeleteCustomKeyStore(_a0 *kms.DeleteCustomKeyStoreInput) (*kms.DeleteCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCustomKeyStoreRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DeleteCustomKeyStoreRequest(_a0 *kms.DeleteCustomKeyStoreInput) (*request.Request, *kms.DeleteCustomKeyStoreOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCustomKeyStoreWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) DeleteCustomKeyStoreWithContext(_a0 context.Context, _a1 *kms.DeleteCustomKeyStoreInput, _a2 ...request.Option) (*kms.DeleteCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteImportedKeyMaterial provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DeleteImportedKeyMaterial(_a0 *kms.DeleteImportedKeyMaterialInput) (*kms.DeleteImportedKeyMaterialOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteImportedKeyMaterialRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DeleteImportedKeyMaterialRequest(_a0 *kms.DeleteImportedKeyMaterialInput) (*request.Request, *kms.DeleteImportedKeyMaterialOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteImportedKeyMaterialWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) DeleteImportedKeyMaterialWithContext(_a0 context.Context, _a1 *kms.DeleteImportedKeyMaterialInput, _a2 ...request.Option) (*kms.DeleteImportedKeyMaterialOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeCustomKeyStores provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DescribeCustomKeyStores(_a0 *kms.DescribeCustomKeyStoresInput) (*kms.DescribeCustomKeyStoresOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeCustomKeyStoresPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeKMS) DescribeCustomKeyStoresPages(_a0 *kms.DescribeCustomKeyStoresInput, _a1 func(*kms.DescribeCustomKeyStoresOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeCustomKeyStoresPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeKMS) DescribeCustomKeyStoresPagesWithContext(_a0 context.Context, _a1 *kms.DescribeCustomKeyStoresInput, _a2 func(*kms.DescribeCustomKeyStoresOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeCustomKeyStoresRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DescribeCustomKeyStoresRequest(_a0 *kms.DescribeCustomKeyStoresInput) (*request.Request, *kms.DescribeCustomKeyStoresOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeCustomKeyStoresWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) DescribeCustomKeyStoresWithContext(_a0 context.Context, _a1 *kms.DescribeCustomKeyStoresInput, _a2 ...request.Option) (*kms.DescribeCustomKeyStoresOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeKey provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DescribeKey(_a0 *kms.DescribeKeyInput) (*kms.DescribeKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DescribeKeyRequest(_a0 *kms.DescribeKeyInput) (*request.Request, *kms.DescribeKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) DescribeKeyWithContext(_a0 context.Context, _a1 *kms.DescribeKeyInput, _a2 ...request.Option) (*kms.DescribeKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableKey provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DisableKey(_a0 *kms.DisableKeyInput) (*kms.DisableKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DisableKeyRequest(_a0 *kms.DisableKeyInput) (*request.Request, *kms.DisableKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableKeyRotation provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DisableKeyRotation(_a0 *kms.DisableKeyRotationInput) (*kms.DisableKeyRotationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableKeyRotationRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DisableKeyRotationRequest(_a0 *kms.DisableKeyRotationInput) (*request.Request, *kms.DisableKeyRotationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableKeyRotationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) DisableKeyRotationWithContext(_a0 context.Context, _a1 *kms.DisableKeyRotationInput, _a2 ...request.Option) (*kms.DisableKeyRotationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) DisableKeyWithContext(_a0 context.Context, _a1 *kms.DisableKeyInput, _a2 ...request.Option) (*kms.DisableKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisconnectCustomKeyStore provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DisconnectCustomKeyStore(_a0 *kms.DisconnectCustomKeyStoreInput) (*kms.DisconnectCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisconnectCustomKeyStoreRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) DisconnectCustomKeyStoreRequest(_a0 *kms.DisconnectCustomKeyStoreInput) (*request.Request, *kms.DisconnectCustomKeyStoreOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisconnectCustomKeyStoreWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) DisconnectCustomKeyStoreWithContext(_a0 context.Context, _a1 *kms.DisconnectCustomKeyStoreInput, _a2 ...request.Option) (*kms.DisconnectCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableKey provides a mock function with given fields: _a0
func (_m *MockFakeKMS) EnableKey(_a0 *kms.EnableKeyInput) (*kms.EnableKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) EnableKeyRequest(_a0 *kms.EnableKeyInput) (*request.Request, *kms.EnableKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableKeyRotation provides a mock function with given fields: _a0
func (_m *MockFakeKMS) EnableKeyRotation(_a0 *kms.EnableKeyRotationInput) (*kms.EnableKeyRotationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableKeyRotationRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) EnableKeyRotationRequest(_a0 *kms.EnableKeyRotationInput) (*request.Request, *kms.EnableKeyRotationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableKeyRotationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) EnableKeyRotationWithContext(_a0 context.Context, _a1 *kms.EnableKeyRotationInput, _a2 ...request.Option) (*kms.EnableKeyRotationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) EnableKeyWithContext(_a0 context.Context, _a1 *kms.EnableKeyInput, _a2 ...request.Option) (*kms.EnableKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Encrypt provides a mock function with given fields: _a0
func (_m *MockFakeKMS) Encrypt(_a0 *kms.EncryptInput) (*kms.EncryptOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EncryptRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) EncryptRequest(_a0 *kms.EncryptInput) (*request.Request, *kms.EncryptOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EncryptWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) EncryptWithContext(_a0 context.Context, _a1 *kms.EncryptInput, _a2 ...request.Option) (*kms.EncryptOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKey provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateDataKey(_a0 *kms.GenerateDataKeyInput) (*kms.GenerateDataKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyPair provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateDataKeyPair(_a0 *kms.GenerateDataKeyPairInput) (*kms.GenerateDataKeyPairOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyPairRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateDataKeyPairRequest(_a0 *kms.GenerateDataKeyPairInput) (*request.Request, *kms.GenerateDataKeyPairOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyPairWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GenerateDataKeyPairWithContext(_a0 context.Context, _a1 *kms.GenerateDataKeyPairInput, _a2 ...request.Option) (*kms.GenerateDataKeyPairOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyPairWithoutPlaintext provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateDataKeyPairWithoutPlaintext(_a0 *kms.GenerateDataKeyPairWithoutPlaintextInput) (*kms.GenerateDataKeyPairWithoutPlaintextOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyPairWithoutPlaintextRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateDataKeyPairWithoutPlaintextRequest(_a0 *kms.GenerateDataKeyPairWithoutPlaintextInput) (*request.Request, *kms.GenerateDataKeyPairWithoutPlaintextOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyPairWithoutPlaintextWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GenerateDataKeyPairWithoutPlaintextWithContext(_a0 context.Context, _a1 *kms.GenerateDataKeyPairWithoutPlaintextInput, _a2 ...request.Option) (*kms.GenerateDataKeyPairWithoutPlaintextOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateDataKeyRequest(_a0 *kms.GenerateDataKeyInput) (*request.Request, *kms.GenerateDataKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GenerateDataKeyWithContext(_a0 context.Context, _a1 *kms.GenerateDataKeyInput, _a2 ...request.Option) (*kms.GenerateDataKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyWithoutPlaintext provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateDataKeyWithoutPlaintext(_a0 *kms.GenerateDataKeyWithoutPlaintextInput) (*kms.GenerateDataKeyWithoutPlaintextOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyWithoutPlaintextRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateDataKeyWithoutPlaintextRequest(_a0 *kms.GenerateDataKeyWithoutPlaintextInput) (*request.Request, *kms.GenerateDataKeyWithoutPlaintextOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateDataKeyWithoutPlaintextWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GenerateDataKeyWithoutPlaintextWithContext(_a0 context.Context, _a1 *kms.GenerateDataKeyWithoutPlaintextInput, _a2 ...request.Option) (*kms.GenerateDataKeyWithoutPlaintextOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateMac provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateMac(_a0 *kms.GenerateMacInput) (*kms.GenerateMacOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateMacRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateMacRequest(_a0 *kms.GenerateMacInput) (*request.Request, *kms.GenerateMacOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateMacWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GenerateMacWithContext(_a0 context.Context, _a1 *kms.GenerateMacInput, _a2 ...request.Option) (*kms.GenerateMacOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateRandom provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateRandom(_a0 *kms.GenerateRandomInput) (*kms.GenerateRandomOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateRandomRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GenerateRandomRequest(_a0 *kms.GenerateRandomInput) (*request.Request, *kms.GenerateRandomOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GenerateRandomWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GenerateRandomWithContext(_a0 context.Context, _a1 *kms.GenerateRandomInput, _a2 ...request.Option) (*kms.GenerateRandomOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyPolicy provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GetKeyPolicy(_a0 *kms.GetKeyPolicyInput) (*kms.GetKeyPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GetKeyPolicyRequest(_a0 *kms.GetKeyPolicyInput) (*request.Request, *kms.GetKeyPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GetKeyPolicyWithContext(_a0 context.Context, _a1 *kms.GetKeyPolicyInput, _a2 ...request.Option) (*kms.GetKeyPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyRotationStatus provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GetKeyRotationStatus(_a0 *kms.GetKeyRotationStatusInput) (*kms.GetKeyRotationStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyRotationStatusRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GetKeyRotationStatusRequest(_a0 *kms.GetKeyRotationStatusInput) (*request.Request, *kms.GetKeyRotationStatusOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKeyRotationStatusWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GetKeyRotationStatusWithContext(_a0 context.Context, _a1 *kms.GetKeyRotationStatusInput, _a2 ...request.Option) (*kms.GetKeyRotationStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetParametersForImport provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GetParametersForImport(_a0 *kms.GetParametersForImportInput) (*kms.GetParametersForImportOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetParametersForImportRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GetParametersForImportRequest(_a0 *kms.GetParametersForImportInput) (*request.Request, *kms.GetParametersForImportOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetParametersForImportWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GetParametersForImportWithContext(_a0 context.Context, _a1 *kms.GetParametersForImportInput, _a2 ...request.Option) (*kms.GetParametersForImportOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicKey provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GetPublicKey(_a0 *kms.GetPublicKeyInput) (*kms.GetPublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) GetPublicKeyRequest(_a0 *kms.GetPublicKeyInput) (*request.Request, *kms.GetPublicKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) GetPublicKeyWithContext(_a0 context.Context, _a1 *kms.GetPublicKeyInput, _a2 ...request.Option) (*kms.GetPublicKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImportKeyMaterial provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ImportKeyMaterial(_a0 *kms.ImportKeyMaterialInput) (*kms.ImportKeyMaterialOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImportKeyMaterialRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ImportKeyMaterialRequest(_a0 *kms.ImportKeyMaterialInput) (*request.Request, *kms.ImportKeyMaterialOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImportKeyMaterialWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ImportKeyMaterialWithContext(_a0 context.Context, _a1 *kms.ImportKeyMaterialInput, _a2 ...request.Option) (*kms.ImportKeyMaterialOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAliases provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListAliases(_a0 *kms.ListAliasesInput) (*kms.ListAliasesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAliasesPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeKMS) ListAliasesPages(_a0 *kms.ListAliasesInput, _a1 func(*kms.ListAliasesOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListAliasesPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeKMS) ListAliasesPagesWithContext(_a0 context.Context, _a1 *kms.ListAliasesInput, _a2 func(*kms.ListAliasesOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListAliasesRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListAliasesRequest(_a0 *kms.ListAliasesInput) (*request.Request, *kms.ListAliasesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAliasesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ListAliasesWithContext(_a0 context.Context, _a1 *kms.ListAliasesInput, _a2 ...request.Option) (*kms.ListAliasesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListGrants provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListGrants(_a0 *kms.ListGrantsInput) (*kms.ListGrantsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListGrantsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeKMS) ListGrantsPages(_a0 *kms.ListGrantsInput, _a1 func(*kms.ListGrantsResponse, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListGrantsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeKMS) ListGrantsPagesWithContext(_a0 context.Context, _a1 *kms.ListGrantsInput, _a2 func(*kms.ListGrantsResponse, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListGrantsRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListGrantsRequest(_a0 *kms.ListGrantsInput) (*request.Request, *kms.ListGrantsResponse) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListGrantsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ListGrantsWithContext(_a0 context.Context, _a1 *kms.ListGrantsInput, _a2 ...request.Option) (*kms.ListGrantsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListKeyPolicies provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListKeyPolicies(_a0 *kms.ListKeyPoliciesInput) (*kms.ListKeyPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListKeyPoliciesPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeKMS) ListKeyPoliciesPages(_a0 *kms.ListKeyPoliciesInput, _a1 func(*kms.ListKeyPoliciesOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListKeyPoliciesPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeKMS) ListKeyPoliciesPagesWithContext(_a0 context.Context, _a1 *kms.ListKeyPoliciesInput, _a2 func(*kms.ListKeyPoliciesOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListKeyPoliciesRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListKeyPoliciesRequest(_a0 *kms.ListKeyPoliciesInput) (*request.Request, *kms.ListKeyPoliciesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListKeyPoliciesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ListKeyPoliciesWithContext(_a0 context.Context, _a1 *kms.ListKeyPoliciesInput, _a2 ...request.Option) (*kms.ListKeyPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListKeys provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListKeys(_a0 *kms.ListKeysInput) (*kms.ListKeysOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListKeysPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeKMS) ListKeysPages(_a0 *kms.ListKeysInput, _a1 func(*kms.ListKeysOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListKeysPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeKMS) ListKeysPagesWithContext(_a0 context.Context, _a1 *kms.ListKeysInput, _a2 func(*kms.ListKeysOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListKeysRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListKeysRequest(_a0 *kms.ListKeysInput) (*request.Request, *kms.ListKeysOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListKeysWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ListKeysWithContext(_a0 context.Context, _a1 *kms.ListKeysInput, _a2 ...request.Option) (*kms.ListKeysOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListResourceTags provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListResourceTags(_a0 *kms.ListResourceTagsInput) (*kms.ListResourceTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListResourceTagsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeKMS) ListResourceTagsPages(_a0 *kms.ListResourceTagsInput, _a1 func(*kms.ListResourceTagsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListResourceTagsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeKMS) ListResourceTagsPagesWithContext(_a0 context.Context, _a1 *kms.ListResourceTagsInput, _a2 func(*kms.ListResourceTagsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListResourceTagsRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListResourceTagsRequest(_a0 *kms.ListResourceTagsInput) (*request.Request, *kms.ListResourceTagsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListResourceTagsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ListResourceTagsWithContext(_a0 context.Context, _a1 *kms.ListResourceTagsInput, _a2 ...request.Option) (*kms.ListResourceTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRetirableGrants provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListRetirableGrants(_a0 *kms.ListRetirableGrantsInput) (*kms.ListGrantsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRetirableGrantsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeKMS) ListRetirableGrantsPages(_a0 *kms.ListRetirableGrantsInput, _a1 func(*kms.ListGrantsResponse, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListRetirableGrantsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeKMS) ListRetirableGrantsPagesWithContext(_a0 context.Context, _a1 *kms.ListRetirableGrantsInput, _a2 func(*kms.ListGrantsResponse, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListRetirableGrantsRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ListRetirableGrantsRequest(_a0 *kms.ListRetirableGrantsInput) (*request.Request, *kms.ListGrantsResponse) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRetirableGrantsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ListRetirableGrantsWithContext(_a0 context.Context, _a1 *kms.ListRetirableGrantsInput, _a2 ...request.Option) (*kms.ListGrantsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutKeyPolicy provides a mock function with given fields: _a0
func (_m *MockFakeKMS) PutKeyPolicy(_a0 *kms.PutKeyPolicyInput) (*kms.PutKeyPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutKeyPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) PutKeyPolicyRequest(_a0 *kms.PutKeyPolicyInput) (*request.Request, *kms.PutKeyPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutKeyPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) PutKeyPolicyWithContext(_a0 context.Context, _a1 *kms.PutKeyPolicyInput, _a2 ...request.Option) (*kms.PutKeyPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReEncrypt provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ReEncrypt(_a0 *kms.ReEncryptInput) (*kms.ReEncryptOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReEncryptRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ReEncryptRequest(_a0 *kms.ReEncryptInput) (*request.Request, *kms.ReEncryptOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReEncryptWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ReEncryptWithContext(_a0 context.Context, _a1 *kms.ReEncryptInput, _a2 ...request.Option) (*kms.ReEncryptOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReplicateKey provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ReplicateKey(_a0 *kms.ReplicateKeyInput) (*kms.ReplicateKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReplicateKeyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ReplicateKeyRequest(_a0 *kms.ReplicateKeyInput) (*request.Request, *kms.ReplicateKeyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReplicateKeyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ReplicateKeyWithContext(_a0 context.Context, _a1 *kms.ReplicateKeyInput, _a2 ...request.Option) (*kms.ReplicateKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RetireGrant provides a mock function with given fields: _a0
func (_m *MockFakeKMS) RetireGrant(_a0 *kms.RetireGrantInput) (*kms.RetireGrantOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RetireGrantRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) RetireGrantRequest(_a0 *kms.RetireGrantInput) (*request.Request, *kms.RetireGrantOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RetireGrantWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) RetireGrantWithContext(_a0 context.Context, _a1 *kms.RetireGrantInput, _a2 ...request.Option) (*kms.RetireGrantOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RevokeGrant provides a mock function with given fields: _a0
func (_m *MockFakeKMS) RevokeGrant(_a0 *kms.RevokeGrantInput) (*kms.RevokeGrantOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RevokeGrantRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) RevokeGrantRequest(_a0 *kms.RevokeGrantInput) (*request.Request, *kms.RevokeGrantOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RevokeGrantWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) RevokeGrantWithContext(_a0 context.Context, _a1 *kms.RevokeGrantInput, _a2 ...request.Option) (*kms.RevokeGrantOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ScheduleKeyDeletion provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ScheduleKeyDeletion(_a0 *kms.ScheduleKeyDeletionInput) (*kms.ScheduleKeyDeletionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ScheduleKeyDeletionRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) ScheduleKeyDeletionRequest(_a0 *kms.ScheduleKeyDeletionInput) (*request.Request, *kms.ScheduleKeyDeletionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ScheduleKeyDeletionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) ScheduleKeyDeletionWithContext(_a0 context.Context, _a1 *kms.ScheduleKeyDeletionInput, _a2 ...request.Option) (*kms.ScheduleKeyDeletionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Sign provides a mock function with given fields: _a0
func (_m *MockFakeKMS) Sign(_a0 *kms.SignInput) (*kms.SignOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SignRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) SignRequest(_a0 *kms.SignInput) (*request.Request, *kms.SignOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SignWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) SignWithContext(_a0 context.Context, _a1 *kms.SignInput, _a2 ...request.Option) (*kms.SignOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TagResource provides a mock function with given fields: _a0
func (_m *MockFakeKMS) TagResource(_a0 *kms.TagResourceInput) (*kms.TagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TagResourceRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) TagResourceRequest(_a0 *kms.TagResourceInput) (*request.Request, *kms.TagResourceOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TagResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) TagResourceWithContext(_a0 context.Context, _a1 *kms.TagResourceInput, _a2 ...request.Option) (*kms.TagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UntagResource provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UntagResource(_a0 *kms.UntagResourceInput) (*kms.UntagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UntagResourceRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UntagResourceRequest(_a0 *kms.UntagResourceInput) (*request.Request, *kms.UntagResourceOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UntagResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) UntagResourceWithContext(_a0 context.Context, _a1 *kms.UntagResourceInput, _a2 ...request.Option) (*kms.UntagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateAlias provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UpdateAlias(_a0 *kms.UpdateAliasInput) (*kms.UpdateAliasOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateAliasRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UpdateAliasRequest(_a0 *kms.UpdateAliasInput) (*request.Request, *kms.UpdateAliasOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateAliasWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) UpdateAliasWithContext(_a0 context.Context, _a1 *kms.UpdateAliasInput, _a2 ...request.Option) (*kms.UpdateAliasOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateCustomKeyStore provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UpdateCustomKeyStore(_a0 *kms.UpdateCustomKeyStoreInput) (*kms.UpdateCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateCustomKeyStoreRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UpdateCustomKeyStoreRequest(_a0 *kms.UpdateCustomKeyStoreInput) (*request.Request, *kms.UpdateCustomKeyStoreOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateCustomKeyStoreWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) UpdateCustomKeyStoreWithContext(_a0 context.Context, _a1 *kms.UpdateCustomKeyStoreInput, _a2 ...request.Option) (*kms.UpdateCustomKeyStoreOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateKeyDescription provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UpdateKeyDescription(_a0 *kms.UpdateKeyDescriptionInput) (*kms.UpdateKeyDescriptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateKeyDescriptionRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UpdateKeyDescriptionRequest(_a0 *kms.UpdateKeyDescriptionInput) (*request.Request, *kms.UpdateKeyDescriptionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateKeyDescriptionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) UpdateKeyDescriptionWithContext(_a0 context.Context, _a1 *kms.UpdateKeyDescriptionInput, _a2 ...request.Option) (*kms.UpdateKeyDescriptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdatePrimaryRegion provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UpdatePrimaryRegion(_a0 *kms.UpdatePrimaryRegionInput) (*kms.UpdatePrimaryRegionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdatePrimaryRegionRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) UpdatePrimaryRegionRequest(_a0 *kms.UpdatePrimaryRegionInput) (*request.Request, *kms.UpdatePrimaryRegionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdatePrimaryRegionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) UpdatePrimaryRegionWithContext(_a0 context.Context, _a1 *kms.UpdatePrimaryRegionInput, _a2 ...request.Option) (*kms.UpdatePrimaryRegionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Verify provides a mock function with given fields: _a0
func (_m *MockFakeKMS) Verify(_a0 *kms.VerifyInput) (*kms.VerifyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// VerifyMac provides a mock function with given fields: _a0
func (_m *MockFakeKMS) VerifyMac(_a0 *kms.VerifyMacInput) (*kms.VerifyMacOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// VerifyMacRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) VerifyMacRequest(_a0 *kms.VerifyMacInput) (*request.Request, *kms.VerifyMacOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// VerifyMacWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) VerifyMacWithContext(_a0 context.Context, _a1 *kms.VerifyMacInput, _a2 ...request.Option) (*kms.VerifyMacOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// VerifyRequest provides a mock function with given fields: _a0
func (_m *MockFakeKMS) VerifyRequest(_a0 *kms.VerifyInput) (*request.Request, *kms.VerifyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// VerifyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeKMS) VerifyWithContext(_a0 context.Context, _a1 *kms.VerifyInput, _a2 ...request.Option) (*kms.VerifyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockFakeKMS interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFakeKMS creates a new instance of MockFakeKMS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFakeKMS(t mockConstructorTestingTNewMockFakeKMS) *MockFakeKMS {
	_ = "STUB: not implemented"
	return nil
}
