// Code generated by mockery v2.28.1. DO NOT EDIT.

package aws

import (
	context "context"

	request "github.com/aws/aws-sdk-go/aws/request"
	mock "github.com/stretchr/testify/mock"

	s3control "github.com/aws/aws-sdk-go/service/s3control"
)

// MockFakeS3Control is an autogenerated mock type for the FakeS3Control type
type MockFakeS3Control struct {
	mock.Mock
}

// CreateAccessPoint provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateAccessPoint(_a0 *s3control.CreateAccessPointInput) (*s3control.CreateAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAccessPointForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateAccessPointForObjectLambda(_a0 *s3control.CreateAccessPointForObjectLambdaInput) (*s3control.CreateAccessPointForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAccessPointForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateAccessPointForObjectLambdaRequest(_a0 *s3control.CreateAccessPointForObjectLambdaInput) (*request.Request, *s3control.CreateAccessPointForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAccessPointForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) CreateAccessPointForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.CreateAccessPointForObjectLambdaInput, _a2 ...request.Option) (*s3control.CreateAccessPointForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAccessPointRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateAccessPointRequest(_a0 *s3control.CreateAccessPointInput) (*request.Request, *s3control.CreateAccessPointOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAccessPointWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) CreateAccessPointWithContext(_a0 context.Context, _a1 *s3control.CreateAccessPointInput, _a2 ...request.Option) (*s3control.CreateAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateBucket provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateBucket(_a0 *s3control.CreateBucketInput) (*s3control.CreateBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateBucketRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateBucketRequest(_a0 *s3control.CreateBucketInput) (*request.Request, *s3control.CreateBucketOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateBucketWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) CreateBucketWithContext(_a0 context.Context, _a1 *s3control.CreateBucketInput, _a2 ...request.Option) (*s3control.CreateBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateJob provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateJob(_a0 *s3control.CreateJobInput) (*s3control.CreateJobOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateJobRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateJobRequest(_a0 *s3control.CreateJobInput) (*request.Request, *s3control.CreateJobOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateJobWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) CreateJobWithContext(_a0 context.Context, _a1 *s3control.CreateJobInput, _a2 ...request.Option) (*s3control.CreateJobOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMultiRegionAccessPoint provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateMultiRegionAccessPoint(_a0 *s3control.CreateMultiRegionAccessPointInput) (*s3control.CreateMultiRegionAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMultiRegionAccessPointRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) CreateMultiRegionAccessPointRequest(_a0 *s3control.CreateMultiRegionAccessPointInput) (*request.Request, *s3control.CreateMultiRegionAccessPointOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMultiRegionAccessPointWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) CreateMultiRegionAccessPointWithContext(_a0 context.Context, _a1 *s3control.CreateMultiRegionAccessPointInput, _a2 ...request.Option) (*s3control.CreateMultiRegionAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPoint provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteAccessPoint(_a0 *s3control.DeleteAccessPointInput) (*s3control.DeleteAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteAccessPointForObjectLambda(_a0 *s3control.DeleteAccessPointForObjectLambdaInput) (*s3control.DeleteAccessPointForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteAccessPointForObjectLambdaRequest(_a0 *s3control.DeleteAccessPointForObjectLambdaInput) (*request.Request, *s3control.DeleteAccessPointForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteAccessPointForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.DeleteAccessPointForObjectLambdaInput, _a2 ...request.Option) (*s3control.DeleteAccessPointForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteAccessPointPolicy(_a0 *s3control.DeleteAccessPointPolicyInput) (*s3control.DeleteAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointPolicyForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteAccessPointPolicyForObjectLambda(_a0 *s3control.DeleteAccessPointPolicyForObjectLambdaInput) (*s3control.DeleteAccessPointPolicyForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointPolicyForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteAccessPointPolicyForObjectLambdaRequest(_a0 *s3control.DeleteAccessPointPolicyForObjectLambdaInput) (*request.Request, *s3control.DeleteAccessPointPolicyForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointPolicyForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteAccessPointPolicyForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.DeleteAccessPointPolicyForObjectLambdaInput, _a2 ...request.Option) (*s3control.DeleteAccessPointPolicyForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteAccessPointPolicyRequest(_a0 *s3control.DeleteAccessPointPolicyInput) (*request.Request, *s3control.DeleteAccessPointPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteAccessPointPolicyWithContext(_a0 context.Context, _a1 *s3control.DeleteAccessPointPolicyInput, _a2 ...request.Option) (*s3control.DeleteAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteAccessPointRequest(_a0 *s3control.DeleteAccessPointInput) (*request.Request, *s3control.DeleteAccessPointOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessPointWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteAccessPointWithContext(_a0 context.Context, _a1 *s3control.DeleteAccessPointInput, _a2 ...request.Option) (*s3control.DeleteAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucket provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteBucket(_a0 *s3control.DeleteBucketInput) (*s3control.DeleteBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketLifecycleConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteBucketLifecycleConfiguration(_a0 *s3control.DeleteBucketLifecycleConfigurationInput) (*s3control.DeleteBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketLifecycleConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteBucketLifecycleConfigurationRequest(_a0 *s3control.DeleteBucketLifecycleConfigurationInput) (*request.Request, *s3control.DeleteBucketLifecycleConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketLifecycleConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteBucketLifecycleConfigurationWithContext(_a0 context.Context, _a1 *s3control.DeleteBucketLifecycleConfigurationInput, _a2 ...request.Option) (*s3control.DeleteBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteBucketPolicy(_a0 *s3control.DeleteBucketPolicyInput) (*s3control.DeleteBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteBucketPolicyRequest(_a0 *s3control.DeleteBucketPolicyInput) (*request.Request, *s3control.DeleteBucketPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteBucketPolicyWithContext(_a0 context.Context, _a1 *s3control.DeleteBucketPolicyInput, _a2 ...request.Option) (*s3control.DeleteBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteBucketRequest(_a0 *s3control.DeleteBucketInput) (*request.Request, *s3control.DeleteBucketOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteBucketTagging(_a0 *s3control.DeleteBucketTaggingInput) (*s3control.DeleteBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteBucketTaggingRequest(_a0 *s3control.DeleteBucketTaggingInput) (*request.Request, *s3control.DeleteBucketTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteBucketTaggingWithContext(_a0 context.Context, _a1 *s3control.DeleteBucketTaggingInput, _a2 ...request.Option) (*s3control.DeleteBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBucketWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteBucketWithContext(_a0 context.Context, _a1 *s3control.DeleteBucketInput, _a2 ...request.Option) (*s3control.DeleteBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteJobTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteJobTagging(_a0 *s3control.DeleteJobTaggingInput) (*s3control.DeleteJobTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteJobTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteJobTaggingRequest(_a0 *s3control.DeleteJobTaggingInput) (*request.Request, *s3control.DeleteJobTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteJobTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteJobTaggingWithContext(_a0 context.Context, _a1 *s3control.DeleteJobTaggingInput, _a2 ...request.Option) (*s3control.DeleteJobTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteMultiRegionAccessPoint provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteMultiRegionAccessPoint(_a0 *s3control.DeleteMultiRegionAccessPointInput) (*s3control.DeleteMultiRegionAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteMultiRegionAccessPointRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteMultiRegionAccessPointRequest(_a0 *s3control.DeleteMultiRegionAccessPointInput) (*request.Request, *s3control.DeleteMultiRegionAccessPointOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteMultiRegionAccessPointWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteMultiRegionAccessPointWithContext(_a0 context.Context, _a1 *s3control.DeleteMultiRegionAccessPointInput, _a2 ...request.Option) (*s3control.DeleteMultiRegionAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePublicAccessBlock provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeletePublicAccessBlock(_a0 *s3control.DeletePublicAccessBlockInput) (*s3control.DeletePublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePublicAccessBlockRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeletePublicAccessBlockRequest(_a0 *s3control.DeletePublicAccessBlockInput) (*request.Request, *s3control.DeletePublicAccessBlockOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeletePublicAccessBlockWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeletePublicAccessBlockWithContext(_a0 context.Context, _a1 *s3control.DeletePublicAccessBlockInput, _a2 ...request.Option) (*s3control.DeletePublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStorageLensConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteStorageLensConfiguration(_a0 *s3control.DeleteStorageLensConfigurationInput) (*s3control.DeleteStorageLensConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStorageLensConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteStorageLensConfigurationRequest(_a0 *s3control.DeleteStorageLensConfigurationInput) (*request.Request, *s3control.DeleteStorageLensConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStorageLensConfigurationTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteStorageLensConfigurationTagging(_a0 *s3control.DeleteStorageLensConfigurationTaggingInput) (*s3control.DeleteStorageLensConfigurationTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStorageLensConfigurationTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DeleteStorageLensConfigurationTaggingRequest(_a0 *s3control.DeleteStorageLensConfigurationTaggingInput) (*request.Request, *s3control.DeleteStorageLensConfigurationTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStorageLensConfigurationTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteStorageLensConfigurationTaggingWithContext(_a0 context.Context, _a1 *s3control.DeleteStorageLensConfigurationTaggingInput, _a2 ...request.Option) (*s3control.DeleteStorageLensConfigurationTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStorageLensConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DeleteStorageLensConfigurationWithContext(_a0 context.Context, _a1 *s3control.DeleteStorageLensConfigurationInput, _a2 ...request.Option) (*s3control.DeleteStorageLensConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeJob provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DescribeJob(_a0 *s3control.DescribeJobInput) (*s3control.DescribeJobOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeJobRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DescribeJobRequest(_a0 *s3control.DescribeJobInput) (*request.Request, *s3control.DescribeJobOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeJobWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DescribeJobWithContext(_a0 context.Context, _a1 *s3control.DescribeJobInput, _a2 ...request.Option) (*s3control.DescribeJobOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeMultiRegionAccessPointOperation provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DescribeMultiRegionAccessPointOperation(_a0 *s3control.DescribeMultiRegionAccessPointOperationInput) (*s3control.DescribeMultiRegionAccessPointOperationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeMultiRegionAccessPointOperationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) DescribeMultiRegionAccessPointOperationRequest(_a0 *s3control.DescribeMultiRegionAccessPointOperationInput) (*request.Request, *s3control.DescribeMultiRegionAccessPointOperationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeMultiRegionAccessPointOperationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) DescribeMultiRegionAccessPointOperationWithContext(_a0 context.Context, _a1 *s3control.DescribeMultiRegionAccessPointOperationInput, _a2 ...request.Option) (*s3control.DescribeMultiRegionAccessPointOperationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPoint provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPoint(_a0 *s3control.GetAccessPointInput) (*s3control.GetAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointConfigurationForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointConfigurationForObjectLambda(_a0 *s3control.GetAccessPointConfigurationForObjectLambdaInput) (*s3control.GetAccessPointConfigurationForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointConfigurationForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointConfigurationForObjectLambdaRequest(_a0 *s3control.GetAccessPointConfigurationForObjectLambdaInput) (*request.Request, *s3control.GetAccessPointConfigurationForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointConfigurationForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetAccessPointConfigurationForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.GetAccessPointConfigurationForObjectLambdaInput, _a2 ...request.Option) (*s3control.GetAccessPointConfigurationForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointForObjectLambda(_a0 *s3control.GetAccessPointForObjectLambdaInput) (*s3control.GetAccessPointForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointForObjectLambdaRequest(_a0 *s3control.GetAccessPointForObjectLambdaInput) (*request.Request, *s3control.GetAccessPointForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetAccessPointForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.GetAccessPointForObjectLambdaInput, _a2 ...request.Option) (*s3control.GetAccessPointForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointPolicy(_a0 *s3control.GetAccessPointPolicyInput) (*s3control.GetAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointPolicyForObjectLambda(_a0 *s3control.GetAccessPointPolicyForObjectLambdaInput) (*s3control.GetAccessPointPolicyForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointPolicyForObjectLambdaRequest(_a0 *s3control.GetAccessPointPolicyForObjectLambdaInput) (*request.Request, *s3control.GetAccessPointPolicyForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetAccessPointPolicyForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.GetAccessPointPolicyForObjectLambdaInput, _a2 ...request.Option) (*s3control.GetAccessPointPolicyForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointPolicyRequest(_a0 *s3control.GetAccessPointPolicyInput) (*request.Request, *s3control.GetAccessPointPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyStatus provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointPolicyStatus(_a0 *s3control.GetAccessPointPolicyStatusInput) (*s3control.GetAccessPointPolicyStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyStatusForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointPolicyStatusForObjectLambda(_a0 *s3control.GetAccessPointPolicyStatusForObjectLambdaInput) (*s3control.GetAccessPointPolicyStatusForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyStatusForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointPolicyStatusForObjectLambdaRequest(_a0 *s3control.GetAccessPointPolicyStatusForObjectLambdaInput) (*request.Request, *s3control.GetAccessPointPolicyStatusForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyStatusForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetAccessPointPolicyStatusForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.GetAccessPointPolicyStatusForObjectLambdaInput, _a2 ...request.Option) (*s3control.GetAccessPointPolicyStatusForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyStatusRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointPolicyStatusRequest(_a0 *s3control.GetAccessPointPolicyStatusInput) (*request.Request, *s3control.GetAccessPointPolicyStatusOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyStatusWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetAccessPointPolicyStatusWithContext(_a0 context.Context, _a1 *s3control.GetAccessPointPolicyStatusInput, _a2 ...request.Option) (*s3control.GetAccessPointPolicyStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetAccessPointPolicyWithContext(_a0 context.Context, _a1 *s3control.GetAccessPointPolicyInput, _a2 ...request.Option) (*s3control.GetAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetAccessPointRequest(_a0 *s3control.GetAccessPointInput) (*request.Request, *s3control.GetAccessPointOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAccessPointWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetAccessPointWithContext(_a0 context.Context, _a1 *s3control.GetAccessPointInput, _a2 ...request.Option) (*s3control.GetAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucket provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucket(_a0 *s3control.GetBucketInput) (*s3control.GetBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLifecycleConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucketLifecycleConfiguration(_a0 *s3control.GetBucketLifecycleConfigurationInput) (*s3control.GetBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLifecycleConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucketLifecycleConfigurationRequest(_a0 *s3control.GetBucketLifecycleConfigurationInput) (*request.Request, *s3control.GetBucketLifecycleConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketLifecycleConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetBucketLifecycleConfigurationWithContext(_a0 context.Context, _a1 *s3control.GetBucketLifecycleConfigurationInput, _a2 ...request.Option) (*s3control.GetBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucketPolicy(_a0 *s3control.GetBucketPolicyInput) (*s3control.GetBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucketPolicyRequest(_a0 *s3control.GetBucketPolicyInput) (*request.Request, *s3control.GetBucketPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetBucketPolicyWithContext(_a0 context.Context, _a1 *s3control.GetBucketPolicyInput, _a2 ...request.Option) (*s3control.GetBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucketRequest(_a0 *s3control.GetBucketInput) (*request.Request, *s3control.GetBucketOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucketTagging(_a0 *s3control.GetBucketTaggingInput) (*s3control.GetBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucketTaggingRequest(_a0 *s3control.GetBucketTaggingInput) (*request.Request, *s3control.GetBucketTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetBucketTaggingWithContext(_a0 context.Context, _a1 *s3control.GetBucketTaggingInput, _a2 ...request.Option) (*s3control.GetBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketVersioning provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucketVersioning(_a0 *s3control.GetBucketVersioningInput) (*s3control.GetBucketVersioningOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketVersioningRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetBucketVersioningRequest(_a0 *s3control.GetBucketVersioningInput) (*request.Request, *s3control.GetBucketVersioningOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketVersioningWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetBucketVersioningWithContext(_a0 context.Context, _a1 *s3control.GetBucketVersioningInput, _a2 ...request.Option) (*s3control.GetBucketVersioningOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetBucketWithContext(_a0 context.Context, _a1 *s3control.GetBucketInput, _a2 ...request.Option) (*s3control.GetBucketOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetJobTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetJobTagging(_a0 *s3control.GetJobTaggingInput) (*s3control.GetJobTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetJobTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetJobTaggingRequest(_a0 *s3control.GetJobTaggingInput) (*request.Request, *s3control.GetJobTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetJobTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetJobTaggingWithContext(_a0 context.Context, _a1 *s3control.GetJobTaggingInput, _a2 ...request.Option) (*s3control.GetJobTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMultiRegionAccessPoint provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetMultiRegionAccessPoint(_a0 *s3control.GetMultiRegionAccessPointInput) (*s3control.GetMultiRegionAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMultiRegionAccessPointPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetMultiRegionAccessPointPolicy(_a0 *s3control.GetMultiRegionAccessPointPolicyInput) (*s3control.GetMultiRegionAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMultiRegionAccessPointPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetMultiRegionAccessPointPolicyRequest(_a0 *s3control.GetMultiRegionAccessPointPolicyInput) (*request.Request, *s3control.GetMultiRegionAccessPointPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMultiRegionAccessPointPolicyStatus provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetMultiRegionAccessPointPolicyStatus(_a0 *s3control.GetMultiRegionAccessPointPolicyStatusInput) (*s3control.GetMultiRegionAccessPointPolicyStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMultiRegionAccessPointPolicyStatusRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetMultiRegionAccessPointPolicyStatusRequest(_a0 *s3control.GetMultiRegionAccessPointPolicyStatusInput) (*request.Request, *s3control.GetMultiRegionAccessPointPolicyStatusOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMultiRegionAccessPointPolicyStatusWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetMultiRegionAccessPointPolicyStatusWithContext(_a0 context.Context, _a1 *s3control.GetMultiRegionAccessPointPolicyStatusInput, _a2 ...request.Option) (*s3control.GetMultiRegionAccessPointPolicyStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMultiRegionAccessPointPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetMultiRegionAccessPointPolicyWithContext(_a0 context.Context, _a1 *s3control.GetMultiRegionAccessPointPolicyInput, _a2 ...request.Option) (*s3control.GetMultiRegionAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMultiRegionAccessPointRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetMultiRegionAccessPointRequest(_a0 *s3control.GetMultiRegionAccessPointInput) (*request.Request, *s3control.GetMultiRegionAccessPointOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMultiRegionAccessPointWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetMultiRegionAccessPointWithContext(_a0 context.Context, _a1 *s3control.GetMultiRegionAccessPointInput, _a2 ...request.Option) (*s3control.GetMultiRegionAccessPointOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicAccessBlock provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetPublicAccessBlock(_a0 *s3control.GetPublicAccessBlockInput) (*s3control.GetPublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicAccessBlockRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetPublicAccessBlockRequest(_a0 *s3control.GetPublicAccessBlockInput) (*request.Request, *s3control.GetPublicAccessBlockOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetPublicAccessBlockWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetPublicAccessBlockWithContext(_a0 context.Context, _a1 *s3control.GetPublicAccessBlockInput, _a2 ...request.Option) (*s3control.GetPublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStorageLensConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetStorageLensConfiguration(_a0 *s3control.GetStorageLensConfigurationInput) (*s3control.GetStorageLensConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStorageLensConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetStorageLensConfigurationRequest(_a0 *s3control.GetStorageLensConfigurationInput) (*request.Request, *s3control.GetStorageLensConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStorageLensConfigurationTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetStorageLensConfigurationTagging(_a0 *s3control.GetStorageLensConfigurationTaggingInput) (*s3control.GetStorageLensConfigurationTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStorageLensConfigurationTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) GetStorageLensConfigurationTaggingRequest(_a0 *s3control.GetStorageLensConfigurationTaggingInput) (*request.Request, *s3control.GetStorageLensConfigurationTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStorageLensConfigurationTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetStorageLensConfigurationTaggingWithContext(_a0 context.Context, _a1 *s3control.GetStorageLensConfigurationTaggingInput, _a2 ...request.Option) (*s3control.GetStorageLensConfigurationTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStorageLensConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) GetStorageLensConfigurationWithContext(_a0 context.Context, _a1 *s3control.GetStorageLensConfigurationInput, _a2 ...request.Option) (*s3control.GetStorageLensConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAccessPoints provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListAccessPoints(_a0 *s3control.ListAccessPointsInput) (*s3control.ListAccessPointsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAccessPointsForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListAccessPointsForObjectLambda(_a0 *s3control.ListAccessPointsForObjectLambdaInput) (*s3control.ListAccessPointsForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAccessPointsForObjectLambdaPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3Control) ListAccessPointsForObjectLambdaPages(_a0 *s3control.ListAccessPointsForObjectLambdaInput, _a1 func(*s3control.ListAccessPointsForObjectLambdaOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListAccessPointsForObjectLambdaPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3Control) ListAccessPointsForObjectLambdaPagesWithContext(_a0 context.Context, _a1 *s3control.ListAccessPointsForObjectLambdaInput, _a2 func(*s3control.ListAccessPointsForObjectLambdaOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListAccessPointsForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListAccessPointsForObjectLambdaRequest(_a0 *s3control.ListAccessPointsForObjectLambdaInput) (*request.Request, *s3control.ListAccessPointsForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAccessPointsForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) ListAccessPointsForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.ListAccessPointsForObjectLambdaInput, _a2 ...request.Option) (*s3control.ListAccessPointsForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAccessPointsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3Control) ListAccessPointsPages(_a0 *s3control.ListAccessPointsInput, _a1 func(*s3control.ListAccessPointsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListAccessPointsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3Control) ListAccessPointsPagesWithContext(_a0 context.Context, _a1 *s3control.ListAccessPointsInput, _a2 func(*s3control.ListAccessPointsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListAccessPointsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListAccessPointsRequest(_a0 *s3control.ListAccessPointsInput) (*request.Request, *s3control.ListAccessPointsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAccessPointsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) ListAccessPointsWithContext(_a0 context.Context, _a1 *s3control.ListAccessPointsInput, _a2 ...request.Option) (*s3control.ListAccessPointsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListJobs provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListJobs(_a0 *s3control.ListJobsInput) (*s3control.ListJobsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListJobsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3Control) ListJobsPages(_a0 *s3control.ListJobsInput, _a1 func(*s3control.ListJobsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListJobsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3Control) ListJobsPagesWithContext(_a0 context.Context, _a1 *s3control.ListJobsInput, _a2 func(*s3control.ListJobsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListJobsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListJobsRequest(_a0 *s3control.ListJobsInput) (*request.Request, *s3control.ListJobsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListJobsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) ListJobsWithContext(_a0 context.Context, _a1 *s3control.ListJobsInput, _a2 ...request.Option) (*s3control.ListJobsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMultiRegionAccessPoints provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListMultiRegionAccessPoints(_a0 *s3control.ListMultiRegionAccessPointsInput) (*s3control.ListMultiRegionAccessPointsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMultiRegionAccessPointsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3Control) ListMultiRegionAccessPointsPages(_a0 *s3control.ListMultiRegionAccessPointsInput, _a1 func(*s3control.ListMultiRegionAccessPointsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListMultiRegionAccessPointsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3Control) ListMultiRegionAccessPointsPagesWithContext(_a0 context.Context, _a1 *s3control.ListMultiRegionAccessPointsInput, _a2 func(*s3control.ListMultiRegionAccessPointsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListMultiRegionAccessPointsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListMultiRegionAccessPointsRequest(_a0 *s3control.ListMultiRegionAccessPointsInput) (*request.Request, *s3control.ListMultiRegionAccessPointsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMultiRegionAccessPointsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) ListMultiRegionAccessPointsWithContext(_a0 context.Context, _a1 *s3control.ListMultiRegionAccessPointsInput, _a2 ...request.Option) (*s3control.ListMultiRegionAccessPointsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRegionalBuckets provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListRegionalBuckets(_a0 *s3control.ListRegionalBucketsInput) (*s3control.ListRegionalBucketsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRegionalBucketsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3Control) ListRegionalBucketsPages(_a0 *s3control.ListRegionalBucketsInput, _a1 func(*s3control.ListRegionalBucketsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListRegionalBucketsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3Control) ListRegionalBucketsPagesWithContext(_a0 context.Context, _a1 *s3control.ListRegionalBucketsInput, _a2 func(*s3control.ListRegionalBucketsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListRegionalBucketsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListRegionalBucketsRequest(_a0 *s3control.ListRegionalBucketsInput) (*request.Request, *s3control.ListRegionalBucketsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListRegionalBucketsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) ListRegionalBucketsWithContext(_a0 context.Context, _a1 *s3control.ListRegionalBucketsInput, _a2 ...request.Option) (*s3control.ListRegionalBucketsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListStorageLensConfigurations provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListStorageLensConfigurations(_a0 *s3control.ListStorageLensConfigurationsInput) (*s3control.ListStorageLensConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListStorageLensConfigurationsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeS3Control) ListStorageLensConfigurationsPages(_a0 *s3control.ListStorageLensConfigurationsInput, _a1 func(*s3control.ListStorageLensConfigurationsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ListStorageLensConfigurationsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeS3Control) ListStorageLensConfigurationsPagesWithContext(_a0 context.Context, _a1 *s3control.ListStorageLensConfigurationsInput, _a2 func(*s3control.ListStorageLensConfigurationsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// ListStorageLensConfigurationsRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) ListStorageLensConfigurationsRequest(_a0 *s3control.ListStorageLensConfigurationsInput) (*request.Request, *s3control.ListStorageLensConfigurationsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListStorageLensConfigurationsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) ListStorageLensConfigurationsWithContext(_a0 context.Context, _a1 *s3control.ListStorageLensConfigurationsInput, _a2 ...request.Option) (*s3control.ListStorageLensConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAccessPointConfigurationForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutAccessPointConfigurationForObjectLambda(_a0 *s3control.PutAccessPointConfigurationForObjectLambdaInput) (*s3control.PutAccessPointConfigurationForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAccessPointConfigurationForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutAccessPointConfigurationForObjectLambdaRequest(_a0 *s3control.PutAccessPointConfigurationForObjectLambdaInput) (*request.Request, *s3control.PutAccessPointConfigurationForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAccessPointConfigurationForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutAccessPointConfigurationForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.PutAccessPointConfigurationForObjectLambdaInput, _a2 ...request.Option) (*s3control.PutAccessPointConfigurationForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAccessPointPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutAccessPointPolicy(_a0 *s3control.PutAccessPointPolicyInput) (*s3control.PutAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAccessPointPolicyForObjectLambda provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutAccessPointPolicyForObjectLambda(_a0 *s3control.PutAccessPointPolicyForObjectLambdaInput) (*s3control.PutAccessPointPolicyForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAccessPointPolicyForObjectLambdaRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutAccessPointPolicyForObjectLambdaRequest(_a0 *s3control.PutAccessPointPolicyForObjectLambdaInput) (*request.Request, *s3control.PutAccessPointPolicyForObjectLambdaOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAccessPointPolicyForObjectLambdaWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutAccessPointPolicyForObjectLambdaWithContext(_a0 context.Context, _a1 *s3control.PutAccessPointPolicyForObjectLambdaInput, _a2 ...request.Option) (*s3control.PutAccessPointPolicyForObjectLambdaOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAccessPointPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutAccessPointPolicyRequest(_a0 *s3control.PutAccessPointPolicyInput) (*request.Request, *s3control.PutAccessPointPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAccessPointPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutAccessPointPolicyWithContext(_a0 context.Context, _a1 *s3control.PutAccessPointPolicyInput, _a2 ...request.Option) (*s3control.PutAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLifecycleConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutBucketLifecycleConfiguration(_a0 *s3control.PutBucketLifecycleConfigurationInput) (*s3control.PutBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLifecycleConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutBucketLifecycleConfigurationRequest(_a0 *s3control.PutBucketLifecycleConfigurationInput) (*request.Request, *s3control.PutBucketLifecycleConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketLifecycleConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutBucketLifecycleConfigurationWithContext(_a0 context.Context, _a1 *s3control.PutBucketLifecycleConfigurationInput, _a2 ...request.Option) (*s3control.PutBucketLifecycleConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutBucketPolicy(_a0 *s3control.PutBucketPolicyInput) (*s3control.PutBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutBucketPolicyRequest(_a0 *s3control.PutBucketPolicyInput) (*request.Request, *s3control.PutBucketPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutBucketPolicyWithContext(_a0 context.Context, _a1 *s3control.PutBucketPolicyInput, _a2 ...request.Option) (*s3control.PutBucketPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutBucketTagging(_a0 *s3control.PutBucketTaggingInput) (*s3control.PutBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutBucketTaggingRequest(_a0 *s3control.PutBucketTaggingInput) (*request.Request, *s3control.PutBucketTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutBucketTaggingWithContext(_a0 context.Context, _a1 *s3control.PutBucketTaggingInput, _a2 ...request.Option) (*s3control.PutBucketTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketVersioning provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutBucketVersioning(_a0 *s3control.PutBucketVersioningInput) (*s3control.PutBucketVersioningOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketVersioningRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutBucketVersioningRequest(_a0 *s3control.PutBucketVersioningInput) (*request.Request, *s3control.PutBucketVersioningOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutBucketVersioningWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutBucketVersioningWithContext(_a0 context.Context, _a1 *s3control.PutBucketVersioningInput, _a2 ...request.Option) (*s3control.PutBucketVersioningOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutJobTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutJobTagging(_a0 *s3control.PutJobTaggingInput) (*s3control.PutJobTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutJobTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutJobTaggingRequest(_a0 *s3control.PutJobTaggingInput) (*request.Request, *s3control.PutJobTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutJobTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutJobTaggingWithContext(_a0 context.Context, _a1 *s3control.PutJobTaggingInput, _a2 ...request.Option) (*s3control.PutJobTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutMultiRegionAccessPointPolicy provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutMultiRegionAccessPointPolicy(_a0 *s3control.PutMultiRegionAccessPointPolicyInput) (*s3control.PutMultiRegionAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutMultiRegionAccessPointPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutMultiRegionAccessPointPolicyRequest(_a0 *s3control.PutMultiRegionAccessPointPolicyInput) (*request.Request, *s3control.PutMultiRegionAccessPointPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutMultiRegionAccessPointPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutMultiRegionAccessPointPolicyWithContext(_a0 context.Context, _a1 *s3control.PutMultiRegionAccessPointPolicyInput, _a2 ...request.Option) (*s3control.PutMultiRegionAccessPointPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutPublicAccessBlock provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutPublicAccessBlock(_a0 *s3control.PutPublicAccessBlockInput) (*s3control.PutPublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutPublicAccessBlockRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutPublicAccessBlockRequest(_a0 *s3control.PutPublicAccessBlockInput) (*request.Request, *s3control.PutPublicAccessBlockOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutPublicAccessBlockWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutPublicAccessBlockWithContext(_a0 context.Context, _a1 *s3control.PutPublicAccessBlockInput, _a2 ...request.Option) (*s3control.PutPublicAccessBlockOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutStorageLensConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutStorageLensConfiguration(_a0 *s3control.PutStorageLensConfigurationInput) (*s3control.PutStorageLensConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutStorageLensConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutStorageLensConfigurationRequest(_a0 *s3control.PutStorageLensConfigurationInput) (*request.Request, *s3control.PutStorageLensConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutStorageLensConfigurationTagging provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutStorageLensConfigurationTagging(_a0 *s3control.PutStorageLensConfigurationTaggingInput) (*s3control.PutStorageLensConfigurationTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutStorageLensConfigurationTaggingRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) PutStorageLensConfigurationTaggingRequest(_a0 *s3control.PutStorageLensConfigurationTaggingInput) (*request.Request, *s3control.PutStorageLensConfigurationTaggingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutStorageLensConfigurationTaggingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutStorageLensConfigurationTaggingWithContext(_a0 context.Context, _a1 *s3control.PutStorageLensConfigurationTaggingInput, _a2 ...request.Option) (*s3control.PutStorageLensConfigurationTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutStorageLensConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) PutStorageLensConfigurationWithContext(_a0 context.Context, _a1 *s3control.PutStorageLensConfigurationInput, _a2 ...request.Option) (*s3control.PutStorageLensConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateJobPriority provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) UpdateJobPriority(_a0 *s3control.UpdateJobPriorityInput) (*s3control.UpdateJobPriorityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateJobPriorityRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) UpdateJobPriorityRequest(_a0 *s3control.UpdateJobPriorityInput) (*request.Request, *s3control.UpdateJobPriorityOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateJobPriorityWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) UpdateJobPriorityWithContext(_a0 context.Context, _a1 *s3control.UpdateJobPriorityInput, _a2 ...request.Option) (*s3control.UpdateJobPriorityOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateJobStatus provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) UpdateJobStatus(_a0 *s3control.UpdateJobStatusInput) (*s3control.UpdateJobStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateJobStatusRequest provides a mock function with given fields: _a0
func (_m *MockFakeS3Control) UpdateJobStatusRequest(_a0 *s3control.UpdateJobStatusInput) (*request.Request, *s3control.UpdateJobStatusOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateJobStatusWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeS3Control) UpdateJobStatusWithContext(_a0 context.Context, _a1 *s3control.UpdateJobStatusInput, _a2 ...request.Option) (*s3control.UpdateJobStatusOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockFakeS3Control interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFakeS3Control creates a new instance of MockFakeS3Control. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFakeS3Control(t mockConstructorTestingTNewMockFakeS3Control) *MockFakeS3Control {
	_ = "STUB: not implemented"
	return nil
}
