// Code generated by mockery v2.28.1. DO NOT EDIT.

package aws

import (
	context "context"

	elb "github.com/aws/aws-sdk-go/service/elb"
	mock "github.com/stretchr/testify/mock"

	request "github.com/aws/aws-sdk-go/aws/request"
)

// MockFakeELB is an autogenerated mock type for the FakeELB type
type MockFakeELB struct {
	mock.Mock
}

// AddTags provides a mock function with given fields: _a0
func (_m *MockFakeELB) AddTags(_a0 *elb.AddTagsInput) (*elb.AddTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AddTagsRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) AddTagsRequest(_a0 *elb.AddTagsInput) (*request.Request, *elb.AddTagsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AddTagsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) AddTagsWithContext(_a0 context.Context, _a1 *elb.AddTagsInput, _a2 ...request.Option) (*elb.AddTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ApplySecurityGroupsToLoadBalancer provides a mock function with given fields: _a0
func (_m *MockFakeELB) ApplySecurityGroupsToLoadBalancer(_a0 *elb.ApplySecurityGroupsToLoadBalancerInput) (*elb.ApplySecurityGroupsToLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ApplySecurityGroupsToLoadBalancerRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) ApplySecurityGroupsToLoadBalancerRequest(_a0 *elb.ApplySecurityGroupsToLoadBalancerInput) (*request.Request, *elb.ApplySecurityGroupsToLoadBalancerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ApplySecurityGroupsToLoadBalancerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) ApplySecurityGroupsToLoadBalancerWithContext(_a0 context.Context, _a1 *elb.ApplySecurityGroupsToLoadBalancerInput, _a2 ...request.Option) (*elb.ApplySecurityGroupsToLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AttachLoadBalancerToSubnets provides a mock function with given fields: _a0
func (_m *MockFakeELB) AttachLoadBalancerToSubnets(_a0 *elb.AttachLoadBalancerToSubnetsInput) (*elb.AttachLoadBalancerToSubnetsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AttachLoadBalancerToSubnetsRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) AttachLoadBalancerToSubnetsRequest(_a0 *elb.AttachLoadBalancerToSubnetsInput) (*request.Request, *elb.AttachLoadBalancerToSubnetsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AttachLoadBalancerToSubnetsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) AttachLoadBalancerToSubnetsWithContext(_a0 context.Context, _a1 *elb.AttachLoadBalancerToSubnetsInput, _a2 ...request.Option) (*elb.AttachLoadBalancerToSubnetsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ConfigureHealthCheck provides a mock function with given fields: _a0
func (_m *MockFakeELB) ConfigureHealthCheck(_a0 *elb.ConfigureHealthCheckInput) (*elb.ConfigureHealthCheckOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ConfigureHealthCheckRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) ConfigureHealthCheckRequest(_a0 *elb.ConfigureHealthCheckInput) (*request.Request, *elb.ConfigureHealthCheckOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ConfigureHealthCheckWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) ConfigureHealthCheckWithContext(_a0 context.Context, _a1 *elb.ConfigureHealthCheckInput, _a2 ...request.Option) (*elb.ConfigureHealthCheckOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAppCookieStickinessPolicy provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateAppCookieStickinessPolicy(_a0 *elb.CreateAppCookieStickinessPolicyInput) (*elb.CreateAppCookieStickinessPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAppCookieStickinessPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateAppCookieStickinessPolicyRequest(_a0 *elb.CreateAppCookieStickinessPolicyInput) (*request.Request, *elb.CreateAppCookieStickinessPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAppCookieStickinessPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) CreateAppCookieStickinessPolicyWithContext(_a0 context.Context, _a1 *elb.CreateAppCookieStickinessPolicyInput, _a2 ...request.Option) (*elb.CreateAppCookieStickinessPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLBCookieStickinessPolicy provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateLBCookieStickinessPolicy(_a0 *elb.CreateLBCookieStickinessPolicyInput) (*elb.CreateLBCookieStickinessPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLBCookieStickinessPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateLBCookieStickinessPolicyRequest(_a0 *elb.CreateLBCookieStickinessPolicyInput) (*request.Request, *elb.CreateLBCookieStickinessPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLBCookieStickinessPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) CreateLBCookieStickinessPolicyWithContext(_a0 context.Context, _a1 *elb.CreateLBCookieStickinessPolicyInput, _a2 ...request.Option) (*elb.CreateLBCookieStickinessPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLoadBalancer provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateLoadBalancer(_a0 *elb.CreateLoadBalancerInput) (*elb.CreateLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLoadBalancerListeners provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateLoadBalancerListeners(_a0 *elb.CreateLoadBalancerListenersInput) (*elb.CreateLoadBalancerListenersOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLoadBalancerListenersRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateLoadBalancerListenersRequest(_a0 *elb.CreateLoadBalancerListenersInput) (*request.Request, *elb.CreateLoadBalancerListenersOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLoadBalancerListenersWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) CreateLoadBalancerListenersWithContext(_a0 context.Context, _a1 *elb.CreateLoadBalancerListenersInput, _a2 ...request.Option) (*elb.CreateLoadBalancerListenersOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLoadBalancerPolicy provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateLoadBalancerPolicy(_a0 *elb.CreateLoadBalancerPolicyInput) (*elb.CreateLoadBalancerPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLoadBalancerPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateLoadBalancerPolicyRequest(_a0 *elb.CreateLoadBalancerPolicyInput) (*request.Request, *elb.CreateLoadBalancerPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLoadBalancerPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) CreateLoadBalancerPolicyWithContext(_a0 context.Context, _a1 *elb.CreateLoadBalancerPolicyInput, _a2 ...request.Option) (*elb.CreateLoadBalancerPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLoadBalancerRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) CreateLoadBalancerRequest(_a0 *elb.CreateLoadBalancerInput) (*request.Request, *elb.CreateLoadBalancerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateLoadBalancerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) CreateLoadBalancerWithContext(_a0 context.Context, _a1 *elb.CreateLoadBalancerInput, _a2 ...request.Option) (*elb.CreateLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteLoadBalancer provides a mock function with given fields: _a0
func (_m *MockFakeELB) DeleteLoadBalancer(_a0 *elb.DeleteLoadBalancerInput) (*elb.DeleteLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteLoadBalancerListeners provides a mock function with given fields: _a0
func (_m *MockFakeELB) DeleteLoadBalancerListeners(_a0 *elb.DeleteLoadBalancerListenersInput) (*elb.DeleteLoadBalancerListenersOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteLoadBalancerListenersRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DeleteLoadBalancerListenersRequest(_a0 *elb.DeleteLoadBalancerListenersInput) (*request.Request, *elb.DeleteLoadBalancerListenersOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteLoadBalancerListenersWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DeleteLoadBalancerListenersWithContext(_a0 context.Context, _a1 *elb.DeleteLoadBalancerListenersInput, _a2 ...request.Option) (*elb.DeleteLoadBalancerListenersOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteLoadBalancerPolicy provides a mock function with given fields: _a0
func (_m *MockFakeELB) DeleteLoadBalancerPolicy(_a0 *elb.DeleteLoadBalancerPolicyInput) (*elb.DeleteLoadBalancerPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteLoadBalancerPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DeleteLoadBalancerPolicyRequest(_a0 *elb.DeleteLoadBalancerPolicyInput) (*request.Request, *elb.DeleteLoadBalancerPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteLoadBalancerPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DeleteLoadBalancerPolicyWithContext(_a0 context.Context, _a1 *elb.DeleteLoadBalancerPolicyInput, _a2 ...request.Option) (*elb.DeleteLoadBalancerPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteLoadBalancerRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DeleteLoadBalancerRequest(_a0 *elb.DeleteLoadBalancerInput) (*request.Request, *elb.DeleteLoadBalancerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteLoadBalancerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DeleteLoadBalancerWithContext(_a0 context.Context, _a1 *elb.DeleteLoadBalancerInput, _a2 ...request.Option) (*elb.DeleteLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeregisterInstancesFromLoadBalancer provides a mock function with given fields: _a0
func (_m *MockFakeELB) DeregisterInstancesFromLoadBalancer(_a0 *elb.DeregisterInstancesFromLoadBalancerInput) (*elb.DeregisterInstancesFromLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeregisterInstancesFromLoadBalancerRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DeregisterInstancesFromLoadBalancerRequest(_a0 *elb.DeregisterInstancesFromLoadBalancerInput) (*request.Request, *elb.DeregisterInstancesFromLoadBalancerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeregisterInstancesFromLoadBalancerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DeregisterInstancesFromLoadBalancerWithContext(_a0 context.Context, _a1 *elb.DeregisterInstancesFromLoadBalancerInput, _a2 ...request.Option) (*elb.DeregisterInstancesFromLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeAccountLimits provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeAccountLimits(_a0 *elb.DescribeAccountLimitsInput) (*elb.DescribeAccountLimitsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeAccountLimitsRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeAccountLimitsRequest(_a0 *elb.DescribeAccountLimitsInput) (*request.Request, *elb.DescribeAccountLimitsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeAccountLimitsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DescribeAccountLimitsWithContext(_a0 context.Context, _a1 *elb.DescribeAccountLimitsInput, _a2 ...request.Option) (*elb.DescribeAccountLimitsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeInstanceHealth provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeInstanceHealth(_a0 *elb.DescribeInstanceHealthInput) (*elb.DescribeInstanceHealthOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeInstanceHealthRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeInstanceHealthRequest(_a0 *elb.DescribeInstanceHealthInput) (*request.Request, *elb.DescribeInstanceHealthOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeInstanceHealthWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DescribeInstanceHealthWithContext(_a0 context.Context, _a1 *elb.DescribeInstanceHealthInput, _a2 ...request.Option) (*elb.DescribeInstanceHealthOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancerAttributes provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeLoadBalancerAttributes(_a0 *elb.DescribeLoadBalancerAttributesInput) (*elb.DescribeLoadBalancerAttributesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancerAttributesRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeLoadBalancerAttributesRequest(_a0 *elb.DescribeLoadBalancerAttributesInput) (*request.Request, *elb.DescribeLoadBalancerAttributesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancerAttributesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DescribeLoadBalancerAttributesWithContext(_a0 context.Context, _a1 *elb.DescribeLoadBalancerAttributesInput, _a2 ...request.Option) (*elb.DescribeLoadBalancerAttributesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancerPolicies provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeLoadBalancerPolicies(_a0 *elb.DescribeLoadBalancerPoliciesInput) (*elb.DescribeLoadBalancerPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancerPoliciesRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeLoadBalancerPoliciesRequest(_a0 *elb.DescribeLoadBalancerPoliciesInput) (*request.Request, *elb.DescribeLoadBalancerPoliciesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancerPoliciesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DescribeLoadBalancerPoliciesWithContext(_a0 context.Context, _a1 *elb.DescribeLoadBalancerPoliciesInput, _a2 ...request.Option) (*elb.DescribeLoadBalancerPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancerPolicyTypes provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeLoadBalancerPolicyTypes(_a0 *elb.DescribeLoadBalancerPolicyTypesInput) (*elb.DescribeLoadBalancerPolicyTypesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancerPolicyTypesRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeLoadBalancerPolicyTypesRequest(_a0 *elb.DescribeLoadBalancerPolicyTypesInput) (*request.Request, *elb.DescribeLoadBalancerPolicyTypesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancerPolicyTypesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DescribeLoadBalancerPolicyTypesWithContext(_a0 context.Context, _a1 *elb.DescribeLoadBalancerPolicyTypesInput, _a2 ...request.Option) (*elb.DescribeLoadBalancerPolicyTypesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancers provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeLoadBalancers(_a0 *elb.DescribeLoadBalancersInput) (*elb.DescribeLoadBalancersOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancersPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeELB) DescribeLoadBalancersPages(_a0 *elb.DescribeLoadBalancersInput, _a1 func(*elb.DescribeLoadBalancersOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeLoadBalancersPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeELB) DescribeLoadBalancersPagesWithContext(_a0 context.Context, _a1 *elb.DescribeLoadBalancersInput, _a2 func(*elb.DescribeLoadBalancersOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeLoadBalancersRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeLoadBalancersRequest(_a0 *elb.DescribeLoadBalancersInput) (*request.Request, *elb.DescribeLoadBalancersOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLoadBalancersWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DescribeLoadBalancersWithContext(_a0 context.Context, _a1 *elb.DescribeLoadBalancersInput, _a2 ...request.Option) (*elb.DescribeLoadBalancersOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeTags provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeTags(_a0 *elb.DescribeTagsInput) (*elb.DescribeTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeTagsRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DescribeTagsRequest(_a0 *elb.DescribeTagsInput) (*request.Request, *elb.DescribeTagsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeTagsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DescribeTagsWithContext(_a0 context.Context, _a1 *elb.DescribeTagsInput, _a2 ...request.Option) (*elb.DescribeTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DetachLoadBalancerFromSubnets provides a mock function with given fields: _a0
func (_m *MockFakeELB) DetachLoadBalancerFromSubnets(_a0 *elb.DetachLoadBalancerFromSubnetsInput) (*elb.DetachLoadBalancerFromSubnetsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DetachLoadBalancerFromSubnetsRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DetachLoadBalancerFromSubnetsRequest(_a0 *elb.DetachLoadBalancerFromSubnetsInput) (*request.Request, *elb.DetachLoadBalancerFromSubnetsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DetachLoadBalancerFromSubnetsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DetachLoadBalancerFromSubnetsWithContext(_a0 context.Context, _a1 *elb.DetachLoadBalancerFromSubnetsInput, _a2 ...request.Option) (*elb.DetachLoadBalancerFromSubnetsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableAvailabilityZonesForLoadBalancer provides a mock function with given fields: _a0
func (_m *MockFakeELB) DisableAvailabilityZonesForLoadBalancer(_a0 *elb.DisableAvailabilityZonesForLoadBalancerInput) (*elb.DisableAvailabilityZonesForLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableAvailabilityZonesForLoadBalancerRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) DisableAvailabilityZonesForLoadBalancerRequest(_a0 *elb.DisableAvailabilityZonesForLoadBalancerInput) (*request.Request, *elb.DisableAvailabilityZonesForLoadBalancerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableAvailabilityZonesForLoadBalancerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) DisableAvailabilityZonesForLoadBalancerWithContext(_a0 context.Context, _a1 *elb.DisableAvailabilityZonesForLoadBalancerInput, _a2 ...request.Option) (*elb.DisableAvailabilityZonesForLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableAvailabilityZonesForLoadBalancer provides a mock function with given fields: _a0
func (_m *MockFakeELB) EnableAvailabilityZonesForLoadBalancer(_a0 *elb.EnableAvailabilityZonesForLoadBalancerInput) (*elb.EnableAvailabilityZonesForLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableAvailabilityZonesForLoadBalancerRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) EnableAvailabilityZonesForLoadBalancerRequest(_a0 *elb.EnableAvailabilityZonesForLoadBalancerInput) (*request.Request, *elb.EnableAvailabilityZonesForLoadBalancerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableAvailabilityZonesForLoadBalancerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) EnableAvailabilityZonesForLoadBalancerWithContext(_a0 context.Context, _a1 *elb.EnableAvailabilityZonesForLoadBalancerInput, _a2 ...request.Option) (*elb.EnableAvailabilityZonesForLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ModifyLoadBalancerAttributes provides a mock function with given fields: _a0
func (_m *MockFakeELB) ModifyLoadBalancerAttributes(_a0 *elb.ModifyLoadBalancerAttributesInput) (*elb.ModifyLoadBalancerAttributesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ModifyLoadBalancerAttributesRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) ModifyLoadBalancerAttributesRequest(_a0 *elb.ModifyLoadBalancerAttributesInput) (*request.Request, *elb.ModifyLoadBalancerAttributesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ModifyLoadBalancerAttributesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) ModifyLoadBalancerAttributesWithContext(_a0 context.Context, _a1 *elb.ModifyLoadBalancerAttributesInput, _a2 ...request.Option) (*elb.ModifyLoadBalancerAttributesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterInstancesWithLoadBalancer provides a mock function with given fields: _a0
func (_m *MockFakeELB) RegisterInstancesWithLoadBalancer(_a0 *elb.RegisterInstancesWithLoadBalancerInput) (*elb.RegisterInstancesWithLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterInstancesWithLoadBalancerRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) RegisterInstancesWithLoadBalancerRequest(_a0 *elb.RegisterInstancesWithLoadBalancerInput) (*request.Request, *elb.RegisterInstancesWithLoadBalancerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterInstancesWithLoadBalancerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) RegisterInstancesWithLoadBalancerWithContext(_a0 context.Context, _a1 *elb.RegisterInstancesWithLoadBalancerInput, _a2 ...request.Option) (*elb.RegisterInstancesWithLoadBalancerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveTags provides a mock function with given fields: _a0
func (_m *MockFakeELB) RemoveTags(_a0 *elb.RemoveTagsInput) (*elb.RemoveTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveTagsRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) RemoveTagsRequest(_a0 *elb.RemoveTagsInput) (*request.Request, *elb.RemoveTagsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveTagsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) RemoveTagsWithContext(_a0 context.Context, _a1 *elb.RemoveTagsInput, _a2 ...request.Option) (*elb.RemoveTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLoadBalancerListenerSSLCertificate provides a mock function with given fields: _a0
func (_m *MockFakeELB) SetLoadBalancerListenerSSLCertificate(_a0 *elb.SetLoadBalancerListenerSSLCertificateInput) (*elb.SetLoadBalancerListenerSSLCertificateOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLoadBalancerListenerSSLCertificateRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) SetLoadBalancerListenerSSLCertificateRequest(_a0 *elb.SetLoadBalancerListenerSSLCertificateInput) (*request.Request, *elb.SetLoadBalancerListenerSSLCertificateOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLoadBalancerListenerSSLCertificateWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) SetLoadBalancerListenerSSLCertificateWithContext(_a0 context.Context, _a1 *elb.SetLoadBalancerListenerSSLCertificateInput, _a2 ...request.Option) (*elb.SetLoadBalancerListenerSSLCertificateOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLoadBalancerPoliciesForBackendServer provides a mock function with given fields: _a0
func (_m *MockFakeELB) SetLoadBalancerPoliciesForBackendServer(_a0 *elb.SetLoadBalancerPoliciesForBackendServerInput) (*elb.SetLoadBalancerPoliciesForBackendServerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLoadBalancerPoliciesForBackendServerRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) SetLoadBalancerPoliciesForBackendServerRequest(_a0 *elb.SetLoadBalancerPoliciesForBackendServerInput) (*request.Request, *elb.SetLoadBalancerPoliciesForBackendServerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLoadBalancerPoliciesForBackendServerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) SetLoadBalancerPoliciesForBackendServerWithContext(_a0 context.Context, _a1 *elb.SetLoadBalancerPoliciesForBackendServerInput, _a2 ...request.Option) (*elb.SetLoadBalancerPoliciesForBackendServerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLoadBalancerPoliciesOfListener provides a mock function with given fields: _a0
func (_m *MockFakeELB) SetLoadBalancerPoliciesOfListener(_a0 *elb.SetLoadBalancerPoliciesOfListenerInput) (*elb.SetLoadBalancerPoliciesOfListenerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLoadBalancerPoliciesOfListenerRequest provides a mock function with given fields: _a0
func (_m *MockFakeELB) SetLoadBalancerPoliciesOfListenerRequest(_a0 *elb.SetLoadBalancerPoliciesOfListenerInput) (*request.Request, *elb.SetLoadBalancerPoliciesOfListenerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetLoadBalancerPoliciesOfListenerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) SetLoadBalancerPoliciesOfListenerWithContext(_a0 context.Context, _a1 *elb.SetLoadBalancerPoliciesOfListenerInput, _a2 ...request.Option) (*elb.SetLoadBalancerPoliciesOfListenerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WaitUntilAnyInstanceInService provides a mock function with given fields: _a0
func (_m *MockFakeELB) WaitUntilAnyInstanceInService(_a0 *elb.DescribeInstanceHealthInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilAnyInstanceInServiceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) WaitUntilAnyInstanceInServiceWithContext(_a0 context.Context, _a1 *elb.DescribeInstanceHealthInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilInstanceDeregistered provides a mock function with given fields: _a0
func (_m *MockFakeELB) WaitUntilInstanceDeregistered(_a0 *elb.DescribeInstanceHealthInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilInstanceDeregisteredWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) WaitUntilInstanceDeregisteredWithContext(_a0 context.Context, _a1 *elb.DescribeInstanceHealthInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilInstanceInService provides a mock function with given fields: _a0
func (_m *MockFakeELB) WaitUntilInstanceInService(_a0 *elb.DescribeInstanceHealthInput) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitUntilInstanceInServiceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeELB) WaitUntilInstanceInServiceWithContext(_a0 context.Context, _a1 *elb.DescribeInstanceHealthInput, _a2 ...request.WaiterOption) error {
	_ = "STUB: not implemented"
	return nil
}

type mockConstructorTestingTNewMockFakeELB interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFakeELB creates a new instance of MockFakeELB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFakeELB(t mockConstructorTestingTNewMockFakeELB) *MockFakeELB {
	_ = "STUB: not implemented"
	return nil
}
