// Code generated by mockery v2.28.1. DO NOT EDIT.

package aws

import (
	context "context"

	apigatewayv2 "github.com/aws/aws-sdk-go/service/apigatewayv2"

	mock "github.com/stretchr/testify/mock"

	request "github.com/aws/aws-sdk-go/aws/request"
)

// MockFakeApiGatewayV2 is an autogenerated mock type for the FakeApiGatewayV2 type
type MockFakeApiGatewayV2 struct {
	mock.Mock
}

// CreateApi provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateApi(_a0 *apigatewayv2.CreateApiInput) (*apigatewayv2.CreateApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateApiMapping provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateApiMapping(_a0 *apigatewayv2.CreateApiMappingInput) (*apigatewayv2.CreateApiMappingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateApiMappingRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateApiMappingRequest(_a0 *apigatewayv2.CreateApiMappingInput) (*request.Request, *apigatewayv2.CreateApiMappingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateApiMappingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateApiMappingWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateApiMappingInput, _a2 ...request.Option) (*apigatewayv2.CreateApiMappingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateApiRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateApiRequest(_a0 *apigatewayv2.CreateApiInput) (*request.Request, *apigatewayv2.CreateApiOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateApiWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateApiWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateApiInput, _a2 ...request.Option) (*apigatewayv2.CreateApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAuthorizer provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateAuthorizer(_a0 *apigatewayv2.CreateAuthorizerInput) (*apigatewayv2.CreateAuthorizerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAuthorizerRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateAuthorizerRequest(_a0 *apigatewayv2.CreateAuthorizerInput) (*request.Request, *apigatewayv2.CreateAuthorizerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateAuthorizerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateAuthorizerWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateAuthorizerInput, _a2 ...request.Option) (*apigatewayv2.CreateAuthorizerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDeployment provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateDeployment(_a0 *apigatewayv2.CreateDeploymentInput) (*apigatewayv2.CreateDeploymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDeploymentRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateDeploymentRequest(_a0 *apigatewayv2.CreateDeploymentInput) (*request.Request, *apigatewayv2.CreateDeploymentOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDeploymentWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateDeploymentWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateDeploymentInput, _a2 ...request.Option) (*apigatewayv2.CreateDeploymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDomainName provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateDomainName(_a0 *apigatewayv2.CreateDomainNameInput) (*apigatewayv2.CreateDomainNameOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDomainNameRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateDomainNameRequest(_a0 *apigatewayv2.CreateDomainNameInput) (*request.Request, *apigatewayv2.CreateDomainNameOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDomainNameWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateDomainNameWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateDomainNameInput, _a2 ...request.Option) (*apigatewayv2.CreateDomainNameOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateIntegration provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateIntegration(_a0 *apigatewayv2.CreateIntegrationInput) (*apigatewayv2.CreateIntegrationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateIntegrationRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateIntegrationRequest(_a0 *apigatewayv2.CreateIntegrationInput) (*request.Request, *apigatewayv2.CreateIntegrationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateIntegrationResponse provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateIntegrationResponse(_a0 *apigatewayv2.CreateIntegrationResponseInput) (*apigatewayv2.CreateIntegrationResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateIntegrationResponseRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateIntegrationResponseRequest(_a0 *apigatewayv2.CreateIntegrationResponseInput) (*request.Request, *apigatewayv2.CreateIntegrationResponseOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateIntegrationResponseWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateIntegrationResponseWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateIntegrationResponseInput, _a2 ...request.Option) (*apigatewayv2.CreateIntegrationResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateIntegrationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateIntegrationWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateIntegrationInput, _a2 ...request.Option) (*apigatewayv2.CreateIntegrationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateModel provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateModel(_a0 *apigatewayv2.CreateModelInput) (*apigatewayv2.CreateModelOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateModelRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateModelRequest(_a0 *apigatewayv2.CreateModelInput) (*request.Request, *apigatewayv2.CreateModelOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateModelWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateModelWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateModelInput, _a2 ...request.Option) (*apigatewayv2.CreateModelOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRoute provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateRoute(_a0 *apigatewayv2.CreateRouteInput) (*apigatewayv2.CreateRouteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRouteRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateRouteRequest(_a0 *apigatewayv2.CreateRouteInput) (*request.Request, *apigatewayv2.CreateRouteOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRouteResponse provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateRouteResponse(_a0 *apigatewayv2.CreateRouteResponseInput) (*apigatewayv2.CreateRouteResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRouteResponseRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateRouteResponseRequest(_a0 *apigatewayv2.CreateRouteResponseInput) (*request.Request, *apigatewayv2.CreateRouteResponseOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRouteResponseWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateRouteResponseWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateRouteResponseInput, _a2 ...request.Option) (*apigatewayv2.CreateRouteResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRouteWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateRouteWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateRouteInput, _a2 ...request.Option) (*apigatewayv2.CreateRouteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateStage provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateStage(_a0 *apigatewayv2.CreateStageInput) (*apigatewayv2.CreateStageOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateStageRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateStageRequest(_a0 *apigatewayv2.CreateStageInput) (*request.Request, *apigatewayv2.CreateStageOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateStageWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateStageWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateStageInput, _a2 ...request.Option) (*apigatewayv2.CreateStageOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateVpcLink provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateVpcLink(_a0 *apigatewayv2.CreateVpcLinkInput) (*apigatewayv2.CreateVpcLinkOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateVpcLinkRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) CreateVpcLinkRequest(_a0 *apigatewayv2.CreateVpcLinkInput) (*request.Request, *apigatewayv2.CreateVpcLinkOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateVpcLinkWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) CreateVpcLinkWithContext(_a0 context.Context, _a1 *apigatewayv2.CreateVpcLinkInput, _a2 ...request.Option) (*apigatewayv2.CreateVpcLinkOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessLogSettings provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteAccessLogSettings(_a0 *apigatewayv2.DeleteAccessLogSettingsInput) (*apigatewayv2.DeleteAccessLogSettingsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessLogSettingsRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteAccessLogSettingsRequest(_a0 *apigatewayv2.DeleteAccessLogSettingsInput) (*request.Request, *apigatewayv2.DeleteAccessLogSettingsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAccessLogSettingsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteAccessLogSettingsWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteAccessLogSettingsInput, _a2 ...request.Option) (*apigatewayv2.DeleteAccessLogSettingsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteApi provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteApi(_a0 *apigatewayv2.DeleteApiInput) (*apigatewayv2.DeleteApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteApiMapping provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteApiMapping(_a0 *apigatewayv2.DeleteApiMappingInput) (*apigatewayv2.DeleteApiMappingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteApiMappingRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteApiMappingRequest(_a0 *apigatewayv2.DeleteApiMappingInput) (*request.Request, *apigatewayv2.DeleteApiMappingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteApiMappingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteApiMappingWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteApiMappingInput, _a2 ...request.Option) (*apigatewayv2.DeleteApiMappingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteApiRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteApiRequest(_a0 *apigatewayv2.DeleteApiInput) (*request.Request, *apigatewayv2.DeleteApiOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteApiWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteApiWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteApiInput, _a2 ...request.Option) (*apigatewayv2.DeleteApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAuthorizer provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteAuthorizer(_a0 *apigatewayv2.DeleteAuthorizerInput) (*apigatewayv2.DeleteAuthorizerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAuthorizerRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteAuthorizerRequest(_a0 *apigatewayv2.DeleteAuthorizerInput) (*request.Request, *apigatewayv2.DeleteAuthorizerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAuthorizerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteAuthorizerWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteAuthorizerInput, _a2 ...request.Option) (*apigatewayv2.DeleteAuthorizerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCorsConfiguration provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteCorsConfiguration(_a0 *apigatewayv2.DeleteCorsConfigurationInput) (*apigatewayv2.DeleteCorsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCorsConfigurationRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteCorsConfigurationRequest(_a0 *apigatewayv2.DeleteCorsConfigurationInput) (*request.Request, *apigatewayv2.DeleteCorsConfigurationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteCorsConfigurationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteCorsConfigurationWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteCorsConfigurationInput, _a2 ...request.Option) (*apigatewayv2.DeleteCorsConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteDeployment provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteDeployment(_a0 *apigatewayv2.DeleteDeploymentInput) (*apigatewayv2.DeleteDeploymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteDeploymentRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteDeploymentRequest(_a0 *apigatewayv2.DeleteDeploymentInput) (*request.Request, *apigatewayv2.DeleteDeploymentOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteDeploymentWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteDeploymentWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteDeploymentInput, _a2 ...request.Option) (*apigatewayv2.DeleteDeploymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteDomainName provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteDomainName(_a0 *apigatewayv2.DeleteDomainNameInput) (*apigatewayv2.DeleteDomainNameOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteDomainNameRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteDomainNameRequest(_a0 *apigatewayv2.DeleteDomainNameInput) (*request.Request, *apigatewayv2.DeleteDomainNameOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteDomainNameWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteDomainNameWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteDomainNameInput, _a2 ...request.Option) (*apigatewayv2.DeleteDomainNameOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteIntegration provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteIntegration(_a0 *apigatewayv2.DeleteIntegrationInput) (*apigatewayv2.DeleteIntegrationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteIntegrationRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteIntegrationRequest(_a0 *apigatewayv2.DeleteIntegrationInput) (*request.Request, *apigatewayv2.DeleteIntegrationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteIntegrationResponse provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteIntegrationResponse(_a0 *apigatewayv2.DeleteIntegrationResponseInput) (*apigatewayv2.DeleteIntegrationResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteIntegrationResponseRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteIntegrationResponseRequest(_a0 *apigatewayv2.DeleteIntegrationResponseInput) (*request.Request, *apigatewayv2.DeleteIntegrationResponseOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteIntegrationResponseWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteIntegrationResponseWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteIntegrationResponseInput, _a2 ...request.Option) (*apigatewayv2.DeleteIntegrationResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteIntegrationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteIntegrationWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteIntegrationInput, _a2 ...request.Option) (*apigatewayv2.DeleteIntegrationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteModel provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteModel(_a0 *apigatewayv2.DeleteModelInput) (*apigatewayv2.DeleteModelOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteModelRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteModelRequest(_a0 *apigatewayv2.DeleteModelInput) (*request.Request, *apigatewayv2.DeleteModelOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteModelWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteModelWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteModelInput, _a2 ...request.Option) (*apigatewayv2.DeleteModelOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRoute provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteRoute(_a0 *apigatewayv2.DeleteRouteInput) (*apigatewayv2.DeleteRouteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteRouteRequest(_a0 *apigatewayv2.DeleteRouteInput) (*request.Request, *apigatewayv2.DeleteRouteOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteRequestParameter provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteRouteRequestParameter(_a0 *apigatewayv2.DeleteRouteRequestParameterInput) (*apigatewayv2.DeleteRouteRequestParameterOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteRequestParameterRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteRouteRequestParameterRequest(_a0 *apigatewayv2.DeleteRouteRequestParameterInput) (*request.Request, *apigatewayv2.DeleteRouteRequestParameterOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteRequestParameterWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteRouteRequestParameterWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteRouteRequestParameterInput, _a2 ...request.Option) (*apigatewayv2.DeleteRouteRequestParameterOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteResponse provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteRouteResponse(_a0 *apigatewayv2.DeleteRouteResponseInput) (*apigatewayv2.DeleteRouteResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteResponseRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteRouteResponseRequest(_a0 *apigatewayv2.DeleteRouteResponseInput) (*request.Request, *apigatewayv2.DeleteRouteResponseOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteResponseWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteRouteResponseWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteRouteResponseInput, _a2 ...request.Option) (*apigatewayv2.DeleteRouteResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteSettings provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteRouteSettings(_a0 *apigatewayv2.DeleteRouteSettingsInput) (*apigatewayv2.DeleteRouteSettingsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteSettingsRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteRouteSettingsRequest(_a0 *apigatewayv2.DeleteRouteSettingsInput) (*request.Request, *apigatewayv2.DeleteRouteSettingsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteSettingsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteRouteSettingsWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteRouteSettingsInput, _a2 ...request.Option) (*apigatewayv2.DeleteRouteSettingsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteRouteWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteRouteWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteRouteInput, _a2 ...request.Option) (*apigatewayv2.DeleteRouteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStage provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteStage(_a0 *apigatewayv2.DeleteStageInput) (*apigatewayv2.DeleteStageOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStageRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteStageRequest(_a0 *apigatewayv2.DeleteStageInput) (*request.Request, *apigatewayv2.DeleteStageOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteStageWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteStageWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteStageInput, _a2 ...request.Option) (*apigatewayv2.DeleteStageOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteVpcLink provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteVpcLink(_a0 *apigatewayv2.DeleteVpcLinkInput) (*apigatewayv2.DeleteVpcLinkOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteVpcLinkRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) DeleteVpcLinkRequest(_a0 *apigatewayv2.DeleteVpcLinkInput) (*request.Request, *apigatewayv2.DeleteVpcLinkOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteVpcLinkWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) DeleteVpcLinkWithContext(_a0 context.Context, _a1 *apigatewayv2.DeleteVpcLinkInput, _a2 ...request.Option) (*apigatewayv2.DeleteVpcLinkOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ExportApi provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) ExportApi(_a0 *apigatewayv2.ExportApiInput) (*apigatewayv2.ExportApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ExportApiRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) ExportApiRequest(_a0 *apigatewayv2.ExportApiInput) (*request.Request, *apigatewayv2.ExportApiOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ExportApiWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) ExportApiWithContext(_a0 context.Context, _a1 *apigatewayv2.ExportApiInput, _a2 ...request.Option) (*apigatewayv2.ExportApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApi provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetApi(_a0 *apigatewayv2.GetApiInput) (*apigatewayv2.GetApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApiMapping provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetApiMapping(_a0 *apigatewayv2.GetApiMappingInput) (*apigatewayv2.GetApiMappingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApiMappingRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetApiMappingRequest(_a0 *apigatewayv2.GetApiMappingInput) (*request.Request, *apigatewayv2.GetApiMappingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApiMappingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetApiMappingWithContext(_a0 context.Context, _a1 *apigatewayv2.GetApiMappingInput, _a2 ...request.Option) (*apigatewayv2.GetApiMappingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApiMappings provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetApiMappings(_a0 *apigatewayv2.GetApiMappingsInput) (*apigatewayv2.GetApiMappingsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApiMappingsRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetApiMappingsRequest(_a0 *apigatewayv2.GetApiMappingsInput) (*request.Request, *apigatewayv2.GetApiMappingsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApiMappingsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetApiMappingsWithContext(_a0 context.Context, _a1 *apigatewayv2.GetApiMappingsInput, _a2 ...request.Option) (*apigatewayv2.GetApiMappingsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApiRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetApiRequest(_a0 *apigatewayv2.GetApiInput) (*request.Request, *apigatewayv2.GetApiOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApiWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetApiWithContext(_a0 context.Context, _a1 *apigatewayv2.GetApiInput, _a2 ...request.Option) (*apigatewayv2.GetApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApis provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetApis(_a0 *apigatewayv2.GetApisInput) (*apigatewayv2.GetApisOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApisRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetApisRequest(_a0 *apigatewayv2.GetApisInput) (*request.Request, *apigatewayv2.GetApisOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetApisWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetApisWithContext(_a0 context.Context, _a1 *apigatewayv2.GetApisInput, _a2 ...request.Option) (*apigatewayv2.GetApisOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAuthorizer provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetAuthorizer(_a0 *apigatewayv2.GetAuthorizerInput) (*apigatewayv2.GetAuthorizerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAuthorizerRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetAuthorizerRequest(_a0 *apigatewayv2.GetAuthorizerInput) (*request.Request, *apigatewayv2.GetAuthorizerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAuthorizerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetAuthorizerWithContext(_a0 context.Context, _a1 *apigatewayv2.GetAuthorizerInput, _a2 ...request.Option) (*apigatewayv2.GetAuthorizerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAuthorizers provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetAuthorizers(_a0 *apigatewayv2.GetAuthorizersInput) (*apigatewayv2.GetAuthorizersOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAuthorizersRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetAuthorizersRequest(_a0 *apigatewayv2.GetAuthorizersInput) (*request.Request, *apigatewayv2.GetAuthorizersOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAuthorizersWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetAuthorizersWithContext(_a0 context.Context, _a1 *apigatewayv2.GetAuthorizersInput, _a2 ...request.Option) (*apigatewayv2.GetAuthorizersOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeployment provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetDeployment(_a0 *apigatewayv2.GetDeploymentInput) (*apigatewayv2.GetDeploymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeploymentRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetDeploymentRequest(_a0 *apigatewayv2.GetDeploymentInput) (*request.Request, *apigatewayv2.GetDeploymentOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeploymentWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetDeploymentWithContext(_a0 context.Context, _a1 *apigatewayv2.GetDeploymentInput, _a2 ...request.Option) (*apigatewayv2.GetDeploymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeployments provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetDeployments(_a0 *apigatewayv2.GetDeploymentsInput) (*apigatewayv2.GetDeploymentsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeploymentsRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetDeploymentsRequest(_a0 *apigatewayv2.GetDeploymentsInput) (*request.Request, *apigatewayv2.GetDeploymentsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeploymentsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetDeploymentsWithContext(_a0 context.Context, _a1 *apigatewayv2.GetDeploymentsInput, _a2 ...request.Option) (*apigatewayv2.GetDeploymentsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDomainName provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetDomainName(_a0 *apigatewayv2.GetDomainNameInput) (*apigatewayv2.GetDomainNameOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDomainNameRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetDomainNameRequest(_a0 *apigatewayv2.GetDomainNameInput) (*request.Request, *apigatewayv2.GetDomainNameOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDomainNameWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetDomainNameWithContext(_a0 context.Context, _a1 *apigatewayv2.GetDomainNameInput, _a2 ...request.Option) (*apigatewayv2.GetDomainNameOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDomainNames provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetDomainNames(_a0 *apigatewayv2.GetDomainNamesInput) (*apigatewayv2.GetDomainNamesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDomainNamesRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetDomainNamesRequest(_a0 *apigatewayv2.GetDomainNamesInput) (*request.Request, *apigatewayv2.GetDomainNamesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDomainNamesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetDomainNamesWithContext(_a0 context.Context, _a1 *apigatewayv2.GetDomainNamesInput, _a2 ...request.Option) (*apigatewayv2.GetDomainNamesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegration provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetIntegration(_a0 *apigatewayv2.GetIntegrationInput) (*apigatewayv2.GetIntegrationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetIntegrationRequest(_a0 *apigatewayv2.GetIntegrationInput) (*request.Request, *apigatewayv2.GetIntegrationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationResponse provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetIntegrationResponse(_a0 *apigatewayv2.GetIntegrationResponseInput) (*apigatewayv2.GetIntegrationResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationResponseRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetIntegrationResponseRequest(_a0 *apigatewayv2.GetIntegrationResponseInput) (*request.Request, *apigatewayv2.GetIntegrationResponseOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationResponseWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetIntegrationResponseWithContext(_a0 context.Context, _a1 *apigatewayv2.GetIntegrationResponseInput, _a2 ...request.Option) (*apigatewayv2.GetIntegrationResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationResponses provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetIntegrationResponses(_a0 *apigatewayv2.GetIntegrationResponsesInput) (*apigatewayv2.GetIntegrationResponsesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationResponsesRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetIntegrationResponsesRequest(_a0 *apigatewayv2.GetIntegrationResponsesInput) (*request.Request, *apigatewayv2.GetIntegrationResponsesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationResponsesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetIntegrationResponsesWithContext(_a0 context.Context, _a1 *apigatewayv2.GetIntegrationResponsesInput, _a2 ...request.Option) (*apigatewayv2.GetIntegrationResponsesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetIntegrationWithContext(_a0 context.Context, _a1 *apigatewayv2.GetIntegrationInput, _a2 ...request.Option) (*apigatewayv2.GetIntegrationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrations provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetIntegrations(_a0 *apigatewayv2.GetIntegrationsInput) (*apigatewayv2.GetIntegrationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationsRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetIntegrationsRequest(_a0 *apigatewayv2.GetIntegrationsInput) (*request.Request, *apigatewayv2.GetIntegrationsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIntegrationsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetIntegrationsWithContext(_a0 context.Context, _a1 *apigatewayv2.GetIntegrationsInput, _a2 ...request.Option) (*apigatewayv2.GetIntegrationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetModel provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetModel(_a0 *apigatewayv2.GetModelInput) (*apigatewayv2.GetModelOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetModelRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetModelRequest(_a0 *apigatewayv2.GetModelInput) (*request.Request, *apigatewayv2.GetModelOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetModelTemplate provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetModelTemplate(_a0 *apigatewayv2.GetModelTemplateInput) (*apigatewayv2.GetModelTemplateOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetModelTemplateRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetModelTemplateRequest(_a0 *apigatewayv2.GetModelTemplateInput) (*request.Request, *apigatewayv2.GetModelTemplateOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetModelTemplateWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetModelTemplateWithContext(_a0 context.Context, _a1 *apigatewayv2.GetModelTemplateInput, _a2 ...request.Option) (*apigatewayv2.GetModelTemplateOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetModelWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetModelWithContext(_a0 context.Context, _a1 *apigatewayv2.GetModelInput, _a2 ...request.Option) (*apigatewayv2.GetModelOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetModels provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetModels(_a0 *apigatewayv2.GetModelsInput) (*apigatewayv2.GetModelsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetModelsRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetModelsRequest(_a0 *apigatewayv2.GetModelsInput) (*request.Request, *apigatewayv2.GetModelsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetModelsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetModelsWithContext(_a0 context.Context, _a1 *apigatewayv2.GetModelsInput, _a2 ...request.Option) (*apigatewayv2.GetModelsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRoute provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetRoute(_a0 *apigatewayv2.GetRouteInput) (*apigatewayv2.GetRouteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRouteRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetRouteRequest(_a0 *apigatewayv2.GetRouteInput) (*request.Request, *apigatewayv2.GetRouteOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRouteResponse provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetRouteResponse(_a0 *apigatewayv2.GetRouteResponseInput) (*apigatewayv2.GetRouteResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRouteResponseRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetRouteResponseRequest(_a0 *apigatewayv2.GetRouteResponseInput) (*request.Request, *apigatewayv2.GetRouteResponseOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRouteResponseWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetRouteResponseWithContext(_a0 context.Context, _a1 *apigatewayv2.GetRouteResponseInput, _a2 ...request.Option) (*apigatewayv2.GetRouteResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRouteResponses provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetRouteResponses(_a0 *apigatewayv2.GetRouteResponsesInput) (*apigatewayv2.GetRouteResponsesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRouteResponsesRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetRouteResponsesRequest(_a0 *apigatewayv2.GetRouteResponsesInput) (*request.Request, *apigatewayv2.GetRouteResponsesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRouteResponsesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetRouteResponsesWithContext(_a0 context.Context, _a1 *apigatewayv2.GetRouteResponsesInput, _a2 ...request.Option) (*apigatewayv2.GetRouteResponsesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRouteWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetRouteWithContext(_a0 context.Context, _a1 *apigatewayv2.GetRouteInput, _a2 ...request.Option) (*apigatewayv2.GetRouteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRoutes provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetRoutes(_a0 *apigatewayv2.GetRoutesInput) (*apigatewayv2.GetRoutesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRoutesRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetRoutesRequest(_a0 *apigatewayv2.GetRoutesInput) (*request.Request, *apigatewayv2.GetRoutesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRoutesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetRoutesWithContext(_a0 context.Context, _a1 *apigatewayv2.GetRoutesInput, _a2 ...request.Option) (*apigatewayv2.GetRoutesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStage provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetStage(_a0 *apigatewayv2.GetStageInput) (*apigatewayv2.GetStageOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStageRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetStageRequest(_a0 *apigatewayv2.GetStageInput) (*request.Request, *apigatewayv2.GetStageOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStageWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetStageWithContext(_a0 context.Context, _a1 *apigatewayv2.GetStageInput, _a2 ...request.Option) (*apigatewayv2.GetStageOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStages provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetStages(_a0 *apigatewayv2.GetStagesInput) (*apigatewayv2.GetStagesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStagesRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetStagesRequest(_a0 *apigatewayv2.GetStagesInput) (*request.Request, *apigatewayv2.GetStagesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetStagesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetStagesWithContext(_a0 context.Context, _a1 *apigatewayv2.GetStagesInput, _a2 ...request.Option) (*apigatewayv2.GetStagesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetTags provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetTags(_a0 *apigatewayv2.GetTagsInput) (*apigatewayv2.GetTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetTagsRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetTagsRequest(_a0 *apigatewayv2.GetTagsInput) (*request.Request, *apigatewayv2.GetTagsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetTagsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetTagsWithContext(_a0 context.Context, _a1 *apigatewayv2.GetTagsInput, _a2 ...request.Option) (*apigatewayv2.GetTagsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetVpcLink provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetVpcLink(_a0 *apigatewayv2.GetVpcLinkInput) (*apigatewayv2.GetVpcLinkOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetVpcLinkRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetVpcLinkRequest(_a0 *apigatewayv2.GetVpcLinkInput) (*request.Request, *apigatewayv2.GetVpcLinkOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetVpcLinkWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetVpcLinkWithContext(_a0 context.Context, _a1 *apigatewayv2.GetVpcLinkInput, _a2 ...request.Option) (*apigatewayv2.GetVpcLinkOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetVpcLinks provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetVpcLinks(_a0 *apigatewayv2.GetVpcLinksInput) (*apigatewayv2.GetVpcLinksOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetVpcLinksRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) GetVpcLinksRequest(_a0 *apigatewayv2.GetVpcLinksInput) (*request.Request, *apigatewayv2.GetVpcLinksOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetVpcLinksWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) GetVpcLinksWithContext(_a0 context.Context, _a1 *apigatewayv2.GetVpcLinksInput, _a2 ...request.Option) (*apigatewayv2.GetVpcLinksOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImportApi provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) ImportApi(_a0 *apigatewayv2.ImportApiInput) (*apigatewayv2.ImportApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImportApiRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) ImportApiRequest(_a0 *apigatewayv2.ImportApiInput) (*request.Request, *apigatewayv2.ImportApiOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImportApiWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) ImportApiWithContext(_a0 context.Context, _a1 *apigatewayv2.ImportApiInput, _a2 ...request.Option) (*apigatewayv2.ImportApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReimportApi provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) ReimportApi(_a0 *apigatewayv2.ReimportApiInput) (*apigatewayv2.ReimportApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReimportApiRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) ReimportApiRequest(_a0 *apigatewayv2.ReimportApiInput) (*request.Request, *apigatewayv2.ReimportApiOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReimportApiWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) ReimportApiWithContext(_a0 context.Context, _a1 *apigatewayv2.ReimportApiInput, _a2 ...request.Option) (*apigatewayv2.ReimportApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResetAuthorizersCache provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) ResetAuthorizersCache(_a0 *apigatewayv2.ResetAuthorizersCacheInput) (*apigatewayv2.ResetAuthorizersCacheOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResetAuthorizersCacheRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) ResetAuthorizersCacheRequest(_a0 *apigatewayv2.ResetAuthorizersCacheInput) (*request.Request, *apigatewayv2.ResetAuthorizersCacheOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResetAuthorizersCacheWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) ResetAuthorizersCacheWithContext(_a0 context.Context, _a1 *apigatewayv2.ResetAuthorizersCacheInput, _a2 ...request.Option) (*apigatewayv2.ResetAuthorizersCacheOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TagResource provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) TagResource(_a0 *apigatewayv2.TagResourceInput) (*apigatewayv2.TagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TagResourceRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) TagResourceRequest(_a0 *apigatewayv2.TagResourceInput) (*request.Request, *apigatewayv2.TagResourceOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TagResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) TagResourceWithContext(_a0 context.Context, _a1 *apigatewayv2.TagResourceInput, _a2 ...request.Option) (*apigatewayv2.TagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UntagResource provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UntagResource(_a0 *apigatewayv2.UntagResourceInput) (*apigatewayv2.UntagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UntagResourceRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UntagResourceRequest(_a0 *apigatewayv2.UntagResourceInput) (*request.Request, *apigatewayv2.UntagResourceOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UntagResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UntagResourceWithContext(_a0 context.Context, _a1 *apigatewayv2.UntagResourceInput, _a2 ...request.Option) (*apigatewayv2.UntagResourceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateApi provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateApi(_a0 *apigatewayv2.UpdateApiInput) (*apigatewayv2.UpdateApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateApiMapping provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateApiMapping(_a0 *apigatewayv2.UpdateApiMappingInput) (*apigatewayv2.UpdateApiMappingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateApiMappingRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateApiMappingRequest(_a0 *apigatewayv2.UpdateApiMappingInput) (*request.Request, *apigatewayv2.UpdateApiMappingOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateApiMappingWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateApiMappingWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateApiMappingInput, _a2 ...request.Option) (*apigatewayv2.UpdateApiMappingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateApiRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateApiRequest(_a0 *apigatewayv2.UpdateApiInput) (*request.Request, *apigatewayv2.UpdateApiOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateApiWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateApiWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateApiInput, _a2 ...request.Option) (*apigatewayv2.UpdateApiOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateAuthorizer provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateAuthorizer(_a0 *apigatewayv2.UpdateAuthorizerInput) (*apigatewayv2.UpdateAuthorizerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateAuthorizerRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateAuthorizerRequest(_a0 *apigatewayv2.UpdateAuthorizerInput) (*request.Request, *apigatewayv2.UpdateAuthorizerOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateAuthorizerWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateAuthorizerWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateAuthorizerInput, _a2 ...request.Option) (*apigatewayv2.UpdateAuthorizerOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDeployment provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateDeployment(_a0 *apigatewayv2.UpdateDeploymentInput) (*apigatewayv2.UpdateDeploymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDeploymentRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateDeploymentRequest(_a0 *apigatewayv2.UpdateDeploymentInput) (*request.Request, *apigatewayv2.UpdateDeploymentOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDeploymentWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateDeploymentWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateDeploymentInput, _a2 ...request.Option) (*apigatewayv2.UpdateDeploymentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDomainName provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateDomainName(_a0 *apigatewayv2.UpdateDomainNameInput) (*apigatewayv2.UpdateDomainNameOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDomainNameRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateDomainNameRequest(_a0 *apigatewayv2.UpdateDomainNameInput) (*request.Request, *apigatewayv2.UpdateDomainNameOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDomainNameWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateDomainNameWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateDomainNameInput, _a2 ...request.Option) (*apigatewayv2.UpdateDomainNameOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateIntegration provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateIntegration(_a0 *apigatewayv2.UpdateIntegrationInput) (*apigatewayv2.UpdateIntegrationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateIntegrationRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateIntegrationRequest(_a0 *apigatewayv2.UpdateIntegrationInput) (*request.Request, *apigatewayv2.UpdateIntegrationOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateIntegrationResponse provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateIntegrationResponse(_a0 *apigatewayv2.UpdateIntegrationResponseInput) (*apigatewayv2.UpdateIntegrationResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateIntegrationResponseRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateIntegrationResponseRequest(_a0 *apigatewayv2.UpdateIntegrationResponseInput) (*request.Request, *apigatewayv2.UpdateIntegrationResponseOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateIntegrationResponseWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateIntegrationResponseWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateIntegrationResponseInput, _a2 ...request.Option) (*apigatewayv2.UpdateIntegrationResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateIntegrationWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateIntegrationWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateIntegrationInput, _a2 ...request.Option) (*apigatewayv2.UpdateIntegrationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateModel provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateModel(_a0 *apigatewayv2.UpdateModelInput) (*apigatewayv2.UpdateModelOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateModelRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateModelRequest(_a0 *apigatewayv2.UpdateModelInput) (*request.Request, *apigatewayv2.UpdateModelOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateModelWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateModelWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateModelInput, _a2 ...request.Option) (*apigatewayv2.UpdateModelOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRoute provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateRoute(_a0 *apigatewayv2.UpdateRouteInput) (*apigatewayv2.UpdateRouteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRouteRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateRouteRequest(_a0 *apigatewayv2.UpdateRouteInput) (*request.Request, *apigatewayv2.UpdateRouteOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRouteResponse provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateRouteResponse(_a0 *apigatewayv2.UpdateRouteResponseInput) (*apigatewayv2.UpdateRouteResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRouteResponseRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateRouteResponseRequest(_a0 *apigatewayv2.UpdateRouteResponseInput) (*request.Request, *apigatewayv2.UpdateRouteResponseOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRouteResponseWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateRouteResponseWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateRouteResponseInput, _a2 ...request.Option) (*apigatewayv2.UpdateRouteResponseOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRouteWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateRouteWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateRouteInput, _a2 ...request.Option) (*apigatewayv2.UpdateRouteOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateStage provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateStage(_a0 *apigatewayv2.UpdateStageInput) (*apigatewayv2.UpdateStageOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateStageRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateStageRequest(_a0 *apigatewayv2.UpdateStageInput) (*request.Request, *apigatewayv2.UpdateStageOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateStageWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateStageWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateStageInput, _a2 ...request.Option) (*apigatewayv2.UpdateStageOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateVpcLink provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateVpcLink(_a0 *apigatewayv2.UpdateVpcLinkInput) (*apigatewayv2.UpdateVpcLinkOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateVpcLinkRequest provides a mock function with given fields: _a0
func (_m *MockFakeApiGatewayV2) UpdateVpcLinkRequest(_a0 *apigatewayv2.UpdateVpcLinkInput) (*request.Request, *apigatewayv2.UpdateVpcLinkOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateVpcLinkWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApiGatewayV2) UpdateVpcLinkWithContext(_a0 context.Context, _a1 *apigatewayv2.UpdateVpcLinkInput, _a2 ...request.Option) (*apigatewayv2.UpdateVpcLinkOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockFakeApiGatewayV2 interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFakeApiGatewayV2 creates a new instance of MockFakeApiGatewayV2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFakeApiGatewayV2(t mockConstructorTestingTNewMockFakeApiGatewayV2) *MockFakeApiGatewayV2 {
	_ = "STUB: not implemented"
	return nil
}
