// Code generated by mockery v2.28.1. DO NOT EDIT.

package aws

import (
	context "context"

	applicationautoscaling "github.com/aws/aws-sdk-go/service/applicationautoscaling"

	mock "github.com/stretchr/testify/mock"

	request "github.com/aws/aws-sdk-go/aws/request"
)

// MockFakeApplicationAutoScaling is an autogenerated mock type for the FakeApplicationAutoScaling type
type MockFakeApplicationAutoScaling struct {
	mock.Mock
}

// DeleteScalingPolicy provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DeleteScalingPolicy(_a0 *applicationautoscaling.DeleteScalingPolicyInput) (*applicationautoscaling.DeleteScalingPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteScalingPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DeleteScalingPolicyRequest(_a0 *applicationautoscaling.DeleteScalingPolicyInput) (*request.Request, *applicationautoscaling.DeleteScalingPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteScalingPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) DeleteScalingPolicyWithContext(_a0 context.Context, _a1 *applicationautoscaling.DeleteScalingPolicyInput, _a2 ...request.Option) (*applicationautoscaling.DeleteScalingPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteScheduledAction provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DeleteScheduledAction(_a0 *applicationautoscaling.DeleteScheduledActionInput) (*applicationautoscaling.DeleteScheduledActionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteScheduledActionRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DeleteScheduledActionRequest(_a0 *applicationautoscaling.DeleteScheduledActionInput) (*request.Request, *applicationautoscaling.DeleteScheduledActionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteScheduledActionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) DeleteScheduledActionWithContext(_a0 context.Context, _a1 *applicationautoscaling.DeleteScheduledActionInput, _a2 ...request.Option) (*applicationautoscaling.DeleteScheduledActionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeregisterScalableTarget provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DeregisterScalableTarget(_a0 *applicationautoscaling.DeregisterScalableTargetInput) (*applicationautoscaling.DeregisterScalableTargetOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeregisterScalableTargetRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DeregisterScalableTargetRequest(_a0 *applicationautoscaling.DeregisterScalableTargetInput) (*request.Request, *applicationautoscaling.DeregisterScalableTargetOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeregisterScalableTargetWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) DeregisterScalableTargetWithContext(_a0 context.Context, _a1 *applicationautoscaling.DeregisterScalableTargetInput, _a2 ...request.Option) (*applicationautoscaling.DeregisterScalableTargetOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScalableTargets provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DescribeScalableTargets(_a0 *applicationautoscaling.DescribeScalableTargetsInput) (*applicationautoscaling.DescribeScalableTargetsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScalableTargetsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeApplicationAutoScaling) DescribeScalableTargetsPages(_a0 *applicationautoscaling.DescribeScalableTargetsInput, _a1 func(*applicationautoscaling.DescribeScalableTargetsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeScalableTargetsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeApplicationAutoScaling) DescribeScalableTargetsPagesWithContext(_a0 context.Context, _a1 *applicationautoscaling.DescribeScalableTargetsInput, _a2 func(*applicationautoscaling.DescribeScalableTargetsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeScalableTargetsRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DescribeScalableTargetsRequest(_a0 *applicationautoscaling.DescribeScalableTargetsInput) (*request.Request, *applicationautoscaling.DescribeScalableTargetsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScalableTargetsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) DescribeScalableTargetsWithContext(_a0 context.Context, _a1 *applicationautoscaling.DescribeScalableTargetsInput, _a2 ...request.Option) (*applicationautoscaling.DescribeScalableTargetsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScalingActivities provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DescribeScalingActivities(_a0 *applicationautoscaling.DescribeScalingActivitiesInput) (*applicationautoscaling.DescribeScalingActivitiesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScalingActivitiesPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeApplicationAutoScaling) DescribeScalingActivitiesPages(_a0 *applicationautoscaling.DescribeScalingActivitiesInput, _a1 func(*applicationautoscaling.DescribeScalingActivitiesOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeScalingActivitiesPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeApplicationAutoScaling) DescribeScalingActivitiesPagesWithContext(_a0 context.Context, _a1 *applicationautoscaling.DescribeScalingActivitiesInput, _a2 func(*applicationautoscaling.DescribeScalingActivitiesOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeScalingActivitiesRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DescribeScalingActivitiesRequest(_a0 *applicationautoscaling.DescribeScalingActivitiesInput) (*request.Request, *applicationautoscaling.DescribeScalingActivitiesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScalingActivitiesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) DescribeScalingActivitiesWithContext(_a0 context.Context, _a1 *applicationautoscaling.DescribeScalingActivitiesInput, _a2 ...request.Option) (*applicationautoscaling.DescribeScalingActivitiesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScalingPolicies provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DescribeScalingPolicies(_a0 *applicationautoscaling.DescribeScalingPoliciesInput) (*applicationautoscaling.DescribeScalingPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScalingPoliciesPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeApplicationAutoScaling) DescribeScalingPoliciesPages(_a0 *applicationautoscaling.DescribeScalingPoliciesInput, _a1 func(*applicationautoscaling.DescribeScalingPoliciesOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeScalingPoliciesPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeApplicationAutoScaling) DescribeScalingPoliciesPagesWithContext(_a0 context.Context, _a1 *applicationautoscaling.DescribeScalingPoliciesInput, _a2 func(*applicationautoscaling.DescribeScalingPoliciesOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeScalingPoliciesRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DescribeScalingPoliciesRequest(_a0 *applicationautoscaling.DescribeScalingPoliciesInput) (*request.Request, *applicationautoscaling.DescribeScalingPoliciesOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScalingPoliciesWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) DescribeScalingPoliciesWithContext(_a0 context.Context, _a1 *applicationautoscaling.DescribeScalingPoliciesInput, _a2 ...request.Option) (*applicationautoscaling.DescribeScalingPoliciesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScheduledActions provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DescribeScheduledActions(_a0 *applicationautoscaling.DescribeScheduledActionsInput) (*applicationautoscaling.DescribeScheduledActionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScheduledActionsPages provides a mock function with given fields: _a0, _a1
func (_m *MockFakeApplicationAutoScaling) DescribeScheduledActionsPages(_a0 *applicationautoscaling.DescribeScheduledActionsInput, _a1 func(*applicationautoscaling.DescribeScheduledActionsOutput, bool) bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeScheduledActionsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockFakeApplicationAutoScaling) DescribeScheduledActionsPagesWithContext(_a0 context.Context, _a1 *applicationautoscaling.DescribeScheduledActionsInput, _a2 func(*applicationautoscaling.DescribeScheduledActionsOutput, bool) bool, _a3 ...request.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeScheduledActionsRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) DescribeScheduledActionsRequest(_a0 *applicationautoscaling.DescribeScheduledActionsInput) (*request.Request, *applicationautoscaling.DescribeScheduledActionsOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeScheduledActionsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) DescribeScheduledActionsWithContext(_a0 context.Context, _a1 *applicationautoscaling.DescribeScheduledActionsInput, _a2 ...request.Option) (*applicationautoscaling.DescribeScheduledActionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutScalingPolicy provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) PutScalingPolicy(_a0 *applicationautoscaling.PutScalingPolicyInput) (*applicationautoscaling.PutScalingPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutScalingPolicyRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) PutScalingPolicyRequest(_a0 *applicationautoscaling.PutScalingPolicyInput) (*request.Request, *applicationautoscaling.PutScalingPolicyOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutScalingPolicyWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) PutScalingPolicyWithContext(_a0 context.Context, _a1 *applicationautoscaling.PutScalingPolicyInput, _a2 ...request.Option) (*applicationautoscaling.PutScalingPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutScheduledAction provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) PutScheduledAction(_a0 *applicationautoscaling.PutScheduledActionInput) (*applicationautoscaling.PutScheduledActionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutScheduledActionRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) PutScheduledActionRequest(_a0 *applicationautoscaling.PutScheduledActionInput) (*request.Request, *applicationautoscaling.PutScheduledActionOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutScheduledActionWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) PutScheduledActionWithContext(_a0 context.Context, _a1 *applicationautoscaling.PutScheduledActionInput, _a2 ...request.Option) (*applicationautoscaling.PutScheduledActionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterScalableTarget provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) RegisterScalableTarget(_a0 *applicationautoscaling.RegisterScalableTargetInput) (*applicationautoscaling.RegisterScalableTargetOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterScalableTargetRequest provides a mock function with given fields: _a0
func (_m *MockFakeApplicationAutoScaling) RegisterScalableTargetRequest(_a0 *applicationautoscaling.RegisterScalableTargetInput) (*request.Request, *applicationautoscaling.RegisterScalableTargetOutput) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterScalableTargetWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFakeApplicationAutoScaling) RegisterScalableTargetWithContext(_a0 context.Context, _a1 *applicationautoscaling.RegisterScalableTargetInput, _a2 ...request.Option) (*applicationautoscaling.RegisterScalableTargetOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockFakeApplicationAutoScaling interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFakeApplicationAutoScaling creates a new instance of MockFakeApplicationAutoScaling. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFakeApplicationAutoScaling(t mockConstructorTestingTNewMockFakeApplicationAutoScaling) *MockFakeApplicationAutoScaling {
	_ = "STUB: not implemented"
	return nil
}
