// Code generated by mockery v2.28.1. DO NOT EDIT.

package output

import mock "github.com/stretchr/testify/mock"

// MockProgress is an autogenerated mock type for the Progress type
type MockProgress struct {
	mock.Mock
}

// Inc provides a mock function with given fields:
func (_m *MockProgress) Inc() {
	_ = "STUB: not implemented"

	// Start provides a mock function with given fields:
	return
}

func (_m *MockProgress) Start() {
	_ = "STUB: not implemented"

	// Stop provides a mock function with given fields:
	return
}

func (_m *MockProgress) Stop() {
	_ = "STUB: not implemented"

	// Val provides a mock function with given fields:
	return
}

func (_m *MockProgress) Val() uint64 { _ = "STUB: not implemented"; return 0 }

type mockConstructorTestingTNewMockProgress interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockProgress creates a new instance of MockProgress. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockProgress(t mockConstructorTestingTNewMockProgress) *MockProgress {
	_ = "STUB: not implemented"
	return nil
}
