// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armcontainerregistry "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerregistry/armcontainerregistry"
	mock "github.com/stretchr/testify/mock"
)

// mockRegistryClient is an autogenerated mock type for the registryClient type
type mockRegistryClient struct {
	mock.Mock
}

// List provides a mock function with given fields: options
func (_m *mockRegistryClient) List(options *armcontainerregistry.RegistriesListOptions) registryListAllPager {
	_ = "STUB: not implemented"
	return *new(registryListAllPager)
}

type mockConstructorTestingTnewMockRegistryClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockRegistryClient creates a new instance of mockRegistryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockRegistryClient(t mockConstructorTestingTnewMockRegistryClient) *mockRegistryClient {
	_ = "STUB: not implemented"
	return nil
}
