// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	context "context"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"

	mock "github.com/stretchr/testify/mock"
)

// mockNetworkSecurityGroupsListAllPager is an autogenerated mock type for the networkSecurityGroupsListAllPager type
type mockNetworkSecurityGroupsListAllPager struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *mockNetworkSecurityGroupsListAllPager) Err() error { _ = "STUB: not implemented"; return nil }

// NextPage provides a mock function with given fields: ctx
func (_m *mockNetworkSecurityGroupsListAllPager) NextPage(ctx context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// PageResponse provides a mock function with given fields:
func (_m *mockNetworkSecurityGroupsListAllPager) PageResponse() armnetwork.NetworkSecurityGroupsListAllResponse {
	_ = "STUB: not implemented"
	return *new(armnetwork.NetworkSecurityGroupsListAllResponse)
}

type mockConstructorTestingTnewMockNetworkSecurityGroupsListAllPager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockNetworkSecurityGroupsListAllPager creates a new instance of mockNetworkSecurityGroupsListAllPager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockNetworkSecurityGroupsListAllPager(t mockConstructorTestingTnewMockNetworkSecurityGroupsListAllPager) *mockNetworkSecurityGroupsListAllPager {
	_ = "STUB: not implemented"
	return nil
}
