// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	context "context"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"

	mock "github.com/stretchr/testify/mock"
)

// mockLoadBalancerRulesListAllPager is an autogenerated mock type for the loadBalancerRulesListAllPager type
type mockLoadBalancerRulesListAllPager struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *mockLoadBalancerRulesListAllPager) Err() error { _ = "STUB: not implemented"; return nil }

// NextPage provides a mock function with given fields: ctx
func (_m *mockLoadBalancerRulesListAllPager) NextPage(ctx context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// PageResponse provides a mock function with given fields:
func (_m *mockLoadBalancerRulesListAllPager) PageResponse() armnetwork.LoadBalancerLoadBalancingRulesListResponse {
	_ = "STUB: not implemented"
	return *new(armnetwork.LoadBalancerLoadBalancingRulesListResponse)
}

type mockConstructorTestingTnewMockLoadBalancerRulesListAllPager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockLoadBalancerRulesListAllPager creates a new instance of mockLoadBalancerRulesListAllPager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockLoadBalancerRulesListAllPager(t mockConstructorTestingTnewMockLoadBalancerRulesListAllPager) *mockLoadBalancerRulesListAllPager {
	_ = "STUB: not implemented"
	return nil
}
