// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armstorage "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage"
	mock "github.com/stretchr/testify/mock"
)

// mockBlobContainerClient is an autogenerated mock type for the blobContainerClient type
type mockBlobContainerClient struct {
	mock.Mock
}

// List provides a mock function with given fields: resourceGroupName, accountName, options
func (_m *mockBlobContainerClient) List(resourceGroupName string, accountName string, options *armstorage.BlobContainersListOptions) blobContainerListPager {
	_ = "STUB: not implemented"
	return *new(blobContainerListPager)
}

type mockConstructorTestingTnewMockBlobContainerClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockBlobContainerClient creates a new instance of mockBlobContainerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockBlobContainerClient(t mockConstructorTestingTnewMockBlobContainerClient) *mockBlobContainerClient {
	_ = "STUB: not implemented"
	return nil
}
