// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"
	mock "github.com/stretchr/testify/mock"
)

// mockNetworkSecurityGroupsClient is an autogenerated mock type for the networkSecurityGroupsClient type
type mockNetworkSecurityGroupsClient struct {
	mock.Mock
}

// ListAll provides a mock function with given fields: options
func (_m *mockNetworkSecurityGroupsClient) ListAll(options *armnetwork.NetworkSecurityGroupsListAllOptions) networkSecurityGroupsListAllPager {
	_ = "STUB: not implemented"
	return *new(networkSecurityGroupsListAllPager)
}

type mockConstructorTestingTnewMockNetworkSecurityGroupsClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockNetworkSecurityGroupsClient creates a new instance of mockNetworkSecurityGroupsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockNetworkSecurityGroupsClient(t mockConstructorTestingTnewMockNetworkSecurityGroupsClient) *mockNetworkSecurityGroupsClient {
	_ = "STUB: not implemented"
	return nil
}
