// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armcontainerregistry "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerregistry/armcontainerregistry"
	mock "github.com/stretchr/testify/mock"
)

// MockContainerRegistryRepository is an autogenerated mock type for the ContainerRegistryRepository type
type MockContainerRegistryRepository struct {
	mock.Mock
}

// ListAllContainerRegistries provides a mock function with given fields:
func (_m *MockContainerRegistryRepository) ListAllContainerRegistries() ([]*armcontainerregistry.Registry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockContainerRegistryRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockContainerRegistryRepository creates a new instance of MockContainerRegistryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockContainerRegistryRepository(t mockConstructorTestingTNewMockContainerRegistryRepository) *MockContainerRegistryRepository {
	_ = "STUB: not implemented"
	return nil
}
