// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	context "context"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"

	mock "github.com/stretchr/testify/mock"
)

// mockFirewallsListAllPager is an autogenerated mock type for the firewallsListAllPager type
type mockFirewallsListAllPager struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *mockFirewallsListAllPager) Err() error { _ = "STUB: not implemented"; return nil }

// NextPage provides a mock function with given fields: ctx
func (_m *mockFirewallsListAllPager) NextPage(ctx context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// PageResponse provides a mock function with given fields:
func (_m *mockFirewallsListAllPager) PageResponse() armnetwork.AzureFirewallsListAllResponse {
	_ = "STUB: not implemented"
	return *new(armnetwork.AzureFirewallsListAllResponse)
}

type mockConstructorTestingTnewMockFirewallsListAllPager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockFirewallsListAllPager creates a new instance of mockFirewallsListAllPager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockFirewallsListAllPager(t mockConstructorTestingTnewMockFirewallsListAllPager) *mockFirewallsListAllPager {
	_ = "STUB: not implemented"
	return nil
}
