// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armresources "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
	mock "github.com/stretchr/testify/mock"
)

// mockResourcesClient is an autogenerated mock type for the resourcesClient type
type mockResourcesClient struct {
	mock.Mock
}

// List provides a mock function with given fields: options
func (_m *mockResourcesClient) List(options *armresources.ResourceGroupsListOptions) resourcesListPager {
	_ = "STUB: not implemented"
	return *new(resourcesListPager)
}

type mockConstructorTestingTnewMockResourcesClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockResourcesClient creates a new instance of mockResourcesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockResourcesClient(t mockConstructorTestingTnewMockResourcesClient) *mockResourcesClient {
	_ = "STUB: not implemented"
	return nil
}
