// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armstorage "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage"
	mock "github.com/stretchr/testify/mock"
)

// MockStorageRespository is an autogenerated mock type for the StorageRespository type
type MockStorageRespository struct {
	mock.Mock
}

// ListAllStorageAccount provides a mock function with given fields:
func (_m *MockStorageRespository) ListAllStorageAccount() ([]*armstorage.StorageAccount, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllStorageContainer provides a mock function with given fields: account
func (_m *MockStorageRespository) ListAllStorageContainer(account *armstorage.StorageAccount) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockStorageRespository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockStorageRespository creates a new instance of MockStorageRespository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockStorageRespository(t mockConstructorTestingTNewMockStorageRespository) *MockStorageRespository {
	_ = "STUB: not implemented"
	return nil
}
