// Code generated by mockery v2.28.1. DO NOT EDIT.

package resource

import (
	enumerationresource "github.com/snyk/driftctl/enumeration/resource"
	mock "github.com/stretchr/testify/mock"
)

// MockIaCSupplier is an autogenerated mock type for the IaCSupplier type
type MockIaCSupplier struct {
	mock.Mock
}

// Resources provides a mock function with given fields:
func (_m *MockIaCSupplier) Resources() ([]*enumerationresource.Resource, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SourceCount provides a mock function with given fields:
func (_m *MockIaCSupplier) SourceCount() uint { _ = "STUB: not implemented"; return 0 }

type mockConstructorTestingTNewMockIaCSupplier interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIaCSupplier creates a new instance of MockIaCSupplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIaCSupplier(t mockConstructorTestingTNewMockIaCSupplier) *MockIaCSupplier {
	_ = "STUB: not implemented"
	return nil
}
