// Code generated by mockery v2.28.1. DO NOT EDIT.

package http

import (
	nethttp "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

// Do provides a mock function with given fields: req
func (_m *MockHTTPClient) Do(req *nethttp.Request) (*nethttp.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockHTTPClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHTTPClient creates a new instance of MockHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHTTPClient(t mockConstructorTestingTNewMockHTTPClient) *MockHTTPClient {
	_ = "STUB: not implemented"
	return nil
}
