// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	s3 "github.com/aws/aws-sdk-go/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// MockS3Repository is an autogenerated mock type for the S3Repository type
type MockS3Repository struct {
	mock.Mock
}

// GetBucketLocation provides a mock function with given fields: bucketName
func (_m *MockS3Repository) GetBucketLocation(bucketName string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetBucketNotification provides a mock function with given fields: bucketName, region
func (_m *MockS3Repository) GetBucketNotification(bucketName string, region string) (*s3.NotificationConfiguration, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPolicy provides a mock function with given fields: bucketName, region
func (_m *MockS3Repository) GetBucketPolicy(bucketName string, region string) (*string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBucketPublicAccessBlock provides a mock function with given fields: bucketName, region
func (_m *MockS3Repository) GetBucketPublicAccessBlock(bucketName string, region string) (*s3.PublicAccessBlockConfiguration, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllBuckets provides a mock function with given fields:
func (_m *MockS3Repository) ListAllBuckets() ([]*s3.Bucket, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketAnalyticsConfigurations provides a mock function with given fields: bucket, region
func (_m *MockS3Repository) ListBucketAnalyticsConfigurations(bucket *s3.Bucket, region string) ([]*s3.AnalyticsConfiguration, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketInventoryConfigurations provides a mock function with given fields: bucket, region
func (_m *MockS3Repository) ListBucketInventoryConfigurations(bucket *s3.Bucket, region string) ([]*s3.InventoryConfiguration, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListBucketMetricsConfigurations provides a mock function with given fields: bucket, region
func (_m *MockS3Repository) ListBucketMetricsConfigurations(bucket *s3.Bucket, region string) ([]*s3.MetricsConfiguration, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockS3Repository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockS3Repository creates a new instance of MockS3Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockS3Repository(t mockConstructorTestingTNewMockS3Repository) *MockS3Repository {
	_ = "STUB: not implemented"
	return nil
}
