// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	sns "github.com/aws/aws-sdk-go/service/sns"
	mock "github.com/stretchr/testify/mock"
)

// MockSNSRepository is an autogenerated mock type for the SNSRepository type
type MockSNSRepository struct {
	mock.Mock
}

// ListAllSubscriptions provides a mock function with given fields:
func (_m *MockSNSRepository) ListAllSubscriptions() ([]*sns.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllTopics provides a mock function with given fields:
func (_m *MockSNSRepository) ListAllTopics() ([]*sns.Topic, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockSNSRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSNSRepository creates a new instance of MockSNSRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSNSRepository(t mockConstructorTestingTNewMockSNSRepository) *MockSNSRepository {
	_ = "STUB: not implemented"
	return nil
}
