// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	rds "github.com/aws/aws-sdk-go/service/rds"
	mock "github.com/stretchr/testify/mock"
)

// MockRDSRepository is an autogenerated mock type for the RDSRepository type
type MockRDSRepository struct {
	mock.Mock
}

// ListAllDBClusters provides a mock function with given fields:
func (_m *MockRDSRepository) ListAllDBClusters() ([]*rds.DBCluster, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllDBInstances provides a mock function with given fields:
func (_m *MockRDSRepository) ListAllDBInstances() ([]*rds.DBInstance, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllDBSubnetGroups provides a mock function with given fields:
func (_m *MockRDSRepository) ListAllDBSubnetGroups() ([]*rds.DBSubnetGroup, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockRDSRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRDSRepository creates a new instance of MockRDSRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRDSRepository(t mockConstructorTestingTNewMockRDSRepository) *MockRDSRepository {
	_ = "STUB: not implemented"
	return nil
}
