// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	sqs "github.com/aws/aws-sdk-go/service/sqs"
	mock "github.com/stretchr/testify/mock"
)

// MockSQSRepository is an autogenerated mock type for the SQSRepository type
type MockSQSRepository struct {
	mock.Mock
}

// GetQueueAttributes provides a mock function with given fields: url
func (_m *MockSQSRepository) GetQueueAttributes(url string) (*sqs.GetQueueAttributesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllQueues provides a mock function with given fields:
func (_m *MockSQSRepository) ListAllQueues() ([]*string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockSQSRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSQSRepository creates a new instance of MockSQSRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSQSRepository(t mockConstructorTestingTNewMockSQSRepository) *MockSQSRepository {
	_ = "STUB: not implemented"
	return nil
}
