// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	apigatewayv2 "github.com/aws/aws-sdk-go/service/apigatewayv2"
	mock "github.com/stretchr/testify/mock"
)

// MockApiGatewayV2Repository is an autogenerated mock type for the ApiGatewayV2Repository type
type MockApiGatewayV2Repository struct {
	mock.Mock
}

// ListAllApiAuthorizers provides a mock function with given fields: _a0
func (_m *MockApiGatewayV2Repository) ListAllApiAuthorizers(_a0 string) ([]*apigatewayv2.Authorizer, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllApiDeployments provides a mock function with given fields: apiId
func (_m *MockApiGatewayV2Repository) ListAllApiDeployments(apiId *string) ([]*apigatewayv2.Deployment, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllApiIntegrationResponses provides a mock function with given fields: _a0, _a1
func (_m *MockApiGatewayV2Repository) ListAllApiIntegrationResponses(_a0 string, _a1 string) ([]*apigatewayv2.IntegrationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllApiIntegrations provides a mock function with given fields: _a0
func (_m *MockApiGatewayV2Repository) ListAllApiIntegrations(_a0 string) ([]*apigatewayv2.Integration, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllApiMappings provides a mock function with given fields: _a0
func (_m *MockApiGatewayV2Repository) ListAllApiMappings(_a0 string) ([]*apigatewayv2.ApiMapping, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllApiModels provides a mock function with given fields: _a0
func (_m *MockApiGatewayV2Repository) ListAllApiModels(_a0 string) ([]*apigatewayv2.Model, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllApiRouteResponses provides a mock function with given fields: _a0, _a1
func (_m *MockApiGatewayV2Repository) ListAllApiRouteResponses(_a0 string, _a1 string) ([]*apigatewayv2.RouteResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllApiRoutes provides a mock function with given fields: apiId
func (_m *MockApiGatewayV2Repository) ListAllApiRoutes(apiId *string) ([]*apigatewayv2.Route, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllApiStages provides a mock function with given fields: _a0
func (_m *MockApiGatewayV2Repository) ListAllApiStages(_a0 string) ([]*apigatewayv2.Stage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllApis provides a mock function with given fields:
func (_m *MockApiGatewayV2Repository) ListAllApis() ([]*apigatewayv2.Api, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllVpcLinks provides a mock function with given fields:
func (_m *MockApiGatewayV2Repository) ListAllVpcLinks() ([]*apigatewayv2.VpcLink, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockApiGatewayV2Repository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockApiGatewayV2Repository creates a new instance of MockApiGatewayV2Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockApiGatewayV2Repository(t mockConstructorTestingTNewMockApiGatewayV2Repository) *MockApiGatewayV2Repository {
	_ = "STUB: not implemented"
	return nil
}
