// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	kms "github.com/aws/aws-sdk-go/service/kms"
	mock "github.com/stretchr/testify/mock"
)

// MockKMSRepository is an autogenerated mock type for the KMSRepository type
type MockKMSRepository struct {
	mock.Mock
}

// ListAllAliases provides a mock function with given fields:
func (_m *MockKMSRepository) ListAllAliases() ([]*kms.AliasListEntry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllKeys provides a mock function with given fields:
func (_m *MockKMSRepository) ListAllKeys() ([]*kms.KeyListEntry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockKMSRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockKMSRepository creates a new instance of MockKMSRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockKMSRepository(t mockConstructorTestingTNewMockKMSRepository) *MockKMSRepository {
	_ = "STUB: not implemented"
	return nil
}
