// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	ecr "github.com/aws/aws-sdk-go/service/ecr"
	mock "github.com/stretchr/testify/mock"
)

// MockECRRepository is an autogenerated mock type for the ECRRepository type
type MockECRRepository struct {
	mock.Mock
}

// GetRepositoryPolicy provides a mock function with given fields: _a0
func (_m *MockECRRepository) GetRepositoryPolicy(_a0 *ecr.Repository) (*ecr.GetRepositoryPolicyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllRepositories provides a mock function with given fields:
func (_m *MockECRRepository) ListAllRepositories() ([]*ecr.Repository, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockECRRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockECRRepository creates a new instance of MockECRRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockECRRepository(t mockConstructorTestingTNewMockECRRepository) *MockECRRepository {
	_ = "STUB: not implemented"
	return nil
}
