// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	ec2 "github.com/aws/aws-sdk-go/service/ec2"
	mock "github.com/stretchr/testify/mock"
)

// MockEC2Repository is an autogenerated mock type for the EC2Repository type
type MockEC2Repository struct {
	mock.Mock
}

// DescribeLaunchTemplates provides a mock function with given fields:
func (_m *MockEC2Repository) DescribeLaunchTemplates() ([]*ec2.LaunchTemplate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// IsEbsEncryptionEnabledByDefault provides a mock function with given fields:
func (_m *MockEC2Repository) IsEbsEncryptionEnabledByDefault() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// ListAllAddresses provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllAddresses() ([]*ec2.Address, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllAddressesAssociation provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllAddressesAssociation() ([]*ec2.Address, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllImages provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllImages() ([]*ec2.Image, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllInstances provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllInstances() ([]*ec2.Instance, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllInternetGateways provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllInternetGateways() ([]*ec2.InternetGateway, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllKeyPairs provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllKeyPairs() ([]*ec2.KeyPairInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllNatGateways provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllNatGateways() ([]*ec2.NatGateway, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllNetworkACLs provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllNetworkACLs() ([]*ec2.NetworkAcl, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllRouteTables provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllRouteTables() ([]*ec2.RouteTable, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllSecurityGroups provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllSecurityGroups() ([]*ec2.SecurityGroup, []*ec2.SecurityGroup, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// ListAllSnapshots provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllSnapshots() ([]*ec2.Snapshot, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListAllSubnets provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllSubnets() ([]*ec2.Subnet, []*ec2.Subnet, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// ListAllVPCs provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllVPCs() ([]*ec2.Vpc, []*ec2.Vpc, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// ListAllVolumes provides a mock function with given fields:
func (_m *MockEC2Repository) ListAllVolumes() ([]*ec2.Volume, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockEC2Repository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEC2Repository creates a new instance of MockEC2Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEC2Repository(t mockConstructorTestingTNewMockEC2Repository) *MockEC2Repository {
	_ = "STUB: not implemented"
	return nil
}
