// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	cloudfront "github.com/aws/aws-sdk-go/service/cloudfront"
	mock "github.com/stretchr/testify/mock"
)

// MockCloudfrontRepository is an autogenerated mock type for the CloudfrontRepository type
type MockCloudfrontRepository struct {
	mock.Mock
}

// ListAllDistributions provides a mock function with given fields:
func (_m *MockCloudfrontRepository) ListAllDistributions() ([]*cloudfront.DistributionSummary, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockCloudfrontRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCloudfrontRepository creates a new instance of MockCloudfrontRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCloudfrontRepository(t mockConstructorTestingTNewMockCloudfrontRepository) *MockCloudfrontRepository {
	_ = "STUB: not implemented"
	return nil
}
