// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	mock "github.com/stretchr/testify/mock"
	asset "google.golang.org/genproto/googleapis/cloud/asset/v1"
)

// MockAssetRepository is an autogenerated mock type for the AssetRepository type
type MockAssetRepository struct {
	mock.Mock
}

// SearchAllAddresses provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllAddresses() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllBigtableInstances provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllBigtableInstances() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllBigtableTables provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllBigtableTables() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllBuckets provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllBuckets() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllCloudRunServices provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllCloudRunServices() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllDNSManagedZones provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllDNSManagedZones() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllDatasets provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllDatasets() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllDisks provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllDisks() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllFirewalls provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllFirewalls() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllForwardingRules provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllForwardingRules() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllFunctions provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllFunctions() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllGlobalAddresses provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllGlobalAddresses() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllGlobalForwardingRules provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllGlobalForwardingRules() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllHealthChecks provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllHealthChecks() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllImages provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllImages() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllInstanceGroupManagers provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllInstanceGroupManagers() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllInstanceGroups provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllInstanceGroups() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllInstances provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllInstances() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllNetworks provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllNetworks() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllNodeGroups provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllNodeGroups() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllRouters provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllRouters() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllSQLDatabaseInstances provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllSQLDatabaseInstances() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllSslCertificates provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllSslCertificates() ([]*asset.Asset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllSubnetworks provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllSubnetworks() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchAllTables provides a mock function with given fields:
func (_m *MockAssetRepository) SearchAllTables() ([]*asset.ResourceSearchResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockAssetRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAssetRepository creates a new instance of MockAssetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAssetRepository(t mockConstructorTestingTNewMockAssetRepository) *MockAssetRepository {
	_ = "STUB: not implemented"
	return nil
}
