// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// MockCloudResourceManagerRepository is an autogenerated mock type for the CloudResourceManagerRepository type
type MockCloudResourceManagerRepository struct {
	mock.Mock
}

// ListProjectsBindings provides a mock function with given fields:
func (_m *MockCloudResourceManagerRepository) ListProjectsBindings() (map[string]map[string][]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockConstructorTestingTNewMockCloudResourceManagerRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCloudResourceManagerRepository creates a new instance of MockCloudResourceManagerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCloudResourceManagerRepository(t mockConstructorTestingTNewMockCloudResourceManagerRepository) *MockCloudResourceManagerRepository {
	_ = "STUB: not implemented"
	return nil
}
