// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	tfe "github.com/hashicorp/go-tfe"
)

// Workspaces is an autogenerated mock type for the Workspaces type
type Workspaces struct {
	mock.Mock
}

// AddRemoteStateConsumers provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) AddRemoteStateConsumers(ctx context.Context, workspaceID string, options tfe.WorkspaceAddRemoteStateConsumersOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// AddTags provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) AddTags(ctx context.Context, workspaceID string, options tfe.WorkspaceAddTagsOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// AssignSSHKey provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) AssignSSHKey(ctx context.Context, workspaceID string, options tfe.WorkspaceAssignSSHKeyOptions) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Create provides a mock function with given fields: ctx, organization, options
func (_m *Workspaces) Create(ctx context.Context, organization string, options tfe.WorkspaceCreateOptions) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Delete provides a mock function with given fields: ctx, organization, workspace
func (_m *Workspaces) Delete(ctx context.Context, organization string, workspace string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteByID provides a mock function with given fields: ctx, workspaceID
func (_m *Workspaces) DeleteByID(ctx context.Context, workspaceID string) error {
	_ = "STUB: not implemented"
	return nil
}

// ForceUnlock provides a mock function with given fields: ctx, workspaceID
func (_m *Workspaces) ForceUnlock(ctx context.Context, workspaceID string) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List provides a mock function with given fields: ctx, organization, options
func (_m *Workspaces) List(ctx context.Context, organization string, options tfe.WorkspaceListOptions) (*tfe.WorkspaceList, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Lock provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) Lock(ctx context.Context, workspaceID string, options tfe.WorkspaceLockOptions) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Read provides a mock function with given fields: ctx, organization, workspace
func (_m *Workspaces) Read(ctx context.Context, organization string, workspace string) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadByID provides a mock function with given fields: ctx, workspaceID
func (_m *Workspaces) ReadByID(ctx context.Context, workspaceID string) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadByIDWithOptions provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) ReadByIDWithOptions(ctx context.Context, workspaceID string, options *tfe.WorkspaceReadOptions) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadWithOptions provides a mock function with given fields: ctx, organization, workspace, options
func (_m *Workspaces) ReadWithOptions(ctx context.Context, organization string, workspace string, options *tfe.WorkspaceReadOptions) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Readme provides a mock function with given fields: ctx, workspaceID
func (_m *Workspaces) Readme(ctx context.Context, workspaceID string) (io.Reader, error) {
	_ = "STUB: not implemented"
	return *new(io.Reader), nil
}

// RemoteStateConsumers provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) RemoteStateConsumers(ctx context.Context, workspaceID string, options *tfe.RemoteStateConsumersListOptions) (*tfe.WorkspaceList, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveRemoteStateConsumers provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) RemoveRemoteStateConsumers(ctx context.Context, workspaceID string, options tfe.WorkspaceRemoveRemoteStateConsumersOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// RemoveTags provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) RemoveTags(ctx context.Context, workspaceID string, options tfe.WorkspaceRemoveTagsOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// RemoveVCSConnection provides a mock function with given fields: ctx, organization, workspace
func (_m *Workspaces) RemoveVCSConnection(ctx context.Context, organization string, workspace string) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveVCSConnectionByID provides a mock function with given fields: ctx, workspaceID
func (_m *Workspaces) RemoveVCSConnectionByID(ctx context.Context, workspaceID string) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Tags provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) Tags(ctx context.Context, workspaceID string, options tfe.WorkspaceTagListOptions) (*tfe.TagList, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnassignSSHKey provides a mock function with given fields: ctx, workspaceID
func (_m *Workspaces) UnassignSSHKey(ctx context.Context, workspaceID string) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Unlock provides a mock function with given fields: ctx, workspaceID
func (_m *Workspaces) Unlock(ctx context.Context, workspaceID string) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Update provides a mock function with given fields: ctx, organization, workspace, options
func (_m *Workspaces) Update(ctx context.Context, organization string, workspace string, options tfe.WorkspaceUpdateOptions) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateByID provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) UpdateByID(ctx context.Context, workspaceID string, options tfe.WorkspaceUpdateOptions) (*tfe.Workspace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRemoteStateConsumers provides a mock function with given fields: ctx, workspaceID, options
func (_m *Workspaces) UpdateRemoteStateConsumers(ctx context.Context, workspaceID string, options tfe.WorkspaceUpdateRemoteStateConsumersOptions) error {
	_ = "STUB: not implemented"
	return nil
}
