// Code generated by mockery v2.28.1. DO NOT EDIT.

package cache

import mock "github.com/stretchr/testify/mock"

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *MockCache) Get(_a0 string) interface{} { _ = "STUB: not implemented"; return nil }

// GetAndLock provides a mock function with given fields: _a0
func (_m *MockCache) GetAndLock(_a0 string) interface{} { _ = "STUB: not implemented"; return nil }

// Len provides a mock function with given fields:
func (_m *MockCache) Len() int { _ = "STUB: not implemented"; return 0 }

// Put provides a mock function with given fields: _a0, _a1
func (_m *MockCache) Put(_a0 string, _a1 interface{}) bool { _ = "STUB: not implemented"; return false }

// Unlock provides a mock function with given fields: _a0
func (_m *MockCache) Unlock(_a0 string) { _ = "STUB: not implemented"; return }

type mockConstructorTestingTNewMockCache interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCache(t mockConstructorTestingTNewMockCache) *MockCache {
	_ = "STUB: not implemented"
	return nil
}
